import {
  // auth
  authReducer,
  AUTH_STATE_KEY,
  doSignup,
  doLogin,
  logout,
  checkAuth,
  selectAuth,
  // boldr
  boldrReducer,
  BOLDR_STATE_KEY,
  selectBoldr,
  // menu
  menuReducer,
  MENU_STATE_KEY,
  selectMenus,
  selectMainMenu,
  makeSelectMainMenu,
  fetchMainMenu,
  fetchMainMenuIfNeeded,
  updateMenuDetails,
  addMenuDetail,
  // settings
  settingsReducer,
  SETTINGS_STATE_KEY,
  selectSettings,
  selectSettingFromList,
  fetchSettingsIfNeeded,
  fetchSettings,
  updateBoldrSettings,
  arrayOfSetting,
  setting,
  // ui
  uiReducer,
  UI_STATE_KEY,
  makeSelectUi,
  changeLayout,
  showModal,
  hideModal,
  setMobileDevice,
  makeSelectMobile,
  toggleDrawer,
  // media
  mediaReducer,
  MEDIA_STATE_KEY,
  fetchMediaIfNeeded,
  getMedia,
  getMediaType,
  selectMedia,
  toggleMedia,
  editMedia,
  deleteMedia,
  uploadMediaFile,
  media,
  arrayOfMedia,
  // users
  usersReducer,
  USERS_STATE_KEY,
  fetchProfileIfNeeded,
  fetchProfile,
  selectMe,
  forgotPassword,
  resetPassword,
  verifyAccount,
  editProfile,
  selectUsers,
  selectProfile,
  makeSelectCurrentProfile,
  makeSelectUser,
  // notifications
  notificationReducer,
  sendNotification,
  dismissNotification,
  clearNotification,
  // entities
  entitiesReducer,
} from './modules';

import rootReducer from './reducers';
import configureStore from './store';

export {
  rootReducer,
  configureStore,
  // auth
  authReducer,
  AUTH_STATE_KEY,
  doSignup,
  doLogin,
  logout,
  checkAuth,
  selectAuth,
  // boldr
  boldrReducer,
  BOLDR_STATE_KEY,
  selectBoldr,
  // menu
  menuReducer,
  MENU_STATE_KEY,
  selectMenus,
  selectMainMenu,
  makeSelectMainMenu,
  fetchMainMenu,
  fetchMainMenuIfNeeded,
  updateMenuDetails,
  addMenuDetail,
  // settings
  settingsReducer,
  SETTINGS_STATE_KEY,
  selectSettings,
  selectSettingFromList,
  fetchSettingsIfNeeded,
  fetchSettings,
  updateBoldrSettings,
  arrayOfSetting,
  setting,
  // ui
  uiReducer,
  UI_STATE_KEY,
  makeSelectUi,
  changeLayout,
  showModal,
  hideModal,
  setMobileDevice,
  makeSelectMobile,
  toggleDrawer,
  // media
  mediaReducer,
  MEDIA_STATE_KEY,
  fetchMediaIfNeeded,
  getMedia,
  getMediaType,
  selectMedia,
  toggleMedia,
  editMedia,
  deleteMedia,
  uploadMediaFile,
  media,
  arrayOfMedia,
  // users
  usersReducer,
  USERS_STATE_KEY,
  fetchProfileIfNeeded,
  fetchProfile,
  selectMe,
  forgotPassword,
  resetPassword,
  verifyAccount,
  editProfile,
  selectUsers,
  selectProfile,
  makeSelectCurrentProfile,
  makeSelectUser,
  // notifications
  notificationReducer,
  sendNotification,
  dismissNotification,
  clearNotification,
  // entities
  entitiesReducer,
};
