export default {
  entityMap: {
    '0': {
      type: 'LINK',
      mutability: 'MUTABLE',
      data: {
        url: 'https://raw.githubusercontent.com/strues/boldr/master/LICENSE',
      },
    },
    '1': {
      type: 'LINK',
      mutability: 'MUTABLE',
      data: {
        url: 'https://raw.githubusercontent.com/strues/boldr/master/LICENSE',
      },
    },
  },
  blocks: [
    {
      key: 'ag6qs',
      text: 'BoldrEditor',
      type: 'header-two',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '59kd9',
      text:
        "BoldrEditor is a ReactJS Rich Text editor built on top of Facebook's draft.js featuring:",
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'bqjdr',
      text: 'Good usability',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '1pdm1',
      text: 'A nice default base of plugins',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '1sd0p',
      text: 'Extensibility.',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'c4sc5',
      text:
        'It is easy to customize the sidebar, disabling or including new items, and the media blocks are rendered with a beautiful component:',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '9vgd',
      text: '',
      type: 'atomic',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {
        type: 'image',
        src: 'http://i.magaimg.net/img/1f5w.jpg',
        caption: 'Picture from StockSnap.io',
        rightsHolder: 'By Tim Marshall',
        display: 'big',
      },
    },
    {
      key: '350ub',
      text: 'Docs',
      type: 'header-two',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'cc4j7',
      text: 'You can find the docs here.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 22,
          length: 4,
          key: 0,
        },
      ],
      data: {},
    },
    {
      key: 'gcc6',
      text: 'License',
      type: 'header-two',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'kst0',
      text: 'Boldr is MIT licensed.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 13,
          length: 3,
          key: 1,
        },
      ],
      data: {},
    },
    {
      key: '6i98s',
      text: 'Sample plugin',
      type: 'header-two',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '5kvgb',
      text: '',
      type: 'atomic',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {
        articles: [
          {
            key: 'd759h',
            title: 'Boldr stuff',
            link: 'https://github.com/strues/boldr',
          },
          {
            key: 'don8q',
            title: 'Writing custom plugins',
            link: 'https://boldr.io',
          },
        ],
        type: 'related-articles',
      },
    },
    {
      key: '3q8fu',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
  ],
};
