// flow-typed signature: 6b42c60b74f395ca135e5af218b8cc38
// flow-typed version: <<STUB>>/@boldr/auth_v^0.1.0-alpha.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@boldr/auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@boldr/auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@boldr/auth/lib/boldr-auth.node.commonjs' {
  declare module.exports: any;
}

declare module '@boldr/auth/lib/boldr-auth.node.esmodules' {
  declare module.exports: any;
}

declare module '@boldr/auth/src/index' {
  declare module.exports: any;
}

declare module '@boldr/auth/src/storage/index' {
  declare module.exports: any;
}

declare module '@boldr/auth/src/storage/storage' {
  declare module.exports: any;
}

declare module '@boldr/auth/src/storage/storage.test' {
  declare module.exports: any;
}

declare module '@boldr/auth/src/token' {
  declare module.exports: any;
}

declare module '@boldr/auth/src/token.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@boldr/auth/lib/boldr-auth.node.commonjs.js' {
  declare module.exports: $Exports<'@boldr/auth/lib/boldr-auth.node.commonjs'>;
}
declare module '@boldr/auth/lib/boldr-auth.node.esmodules.js' {
  declare module.exports: $Exports<'@boldr/auth/lib/boldr-auth.node.esmodules'>;
}
declare module '@boldr/auth/src/index.js' {
  declare module.exports: $Exports<'@boldr/auth/src/index'>;
}
declare module '@boldr/auth/src/storage/index.js' {
  declare module.exports: $Exports<'@boldr/auth/src/storage/index'>;
}
declare module '@boldr/auth/src/storage/storage.js' {
  declare module.exports: $Exports<'@boldr/auth/src/storage/storage'>;
}
declare module '@boldr/auth/src/storage/storage.test.js' {
  declare module.exports: $Exports<'@boldr/auth/src/storage/storage.test'>;
}
declare module '@boldr/auth/src/token.js' {
  declare module.exports: $Exports<'@boldr/auth/src/token'>;
}
declare module '@boldr/auth/src/token.test.js' {
  declare module.exports: $Exports<'@boldr/auth/src/token.test'>;
}
