// flow-typed signature: 60cdd3532875094f945304736792447f
// flow-typed version: <<STUB>>/@boldr/core_v^0.1.0-alpha.5/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@boldr/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@boldr/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@boldr/core/lib/boldr-core.browser.es2015.esm' {
  declare module.exports: any;
}

declare module '@boldr/core/lib/boldr-core.browser.es5.esm' {
  declare module.exports: any;
}

declare module '@boldr/core/lib/boldr-core.node.es2015.cjs' {
  declare module.exports: any;
}

declare module '@boldr/core/lib/boldr-core.node.es2015.esm' {
  declare module.exports: any;
}

declare module '@boldr/core/lib/boldr-core.node.es5.cjs' {
  declare module.exports: any;
}

declare module '@boldr/core/lib/boldr-core.node.es5.esm' {
  declare module.exports: any;
}

declare module '@boldr/core/src/client' {
  declare module.exports: any;
}

declare module '@boldr/core/src/client/renderBoldrApp' {
  declare module.exports: any;
}

declare module '@boldr/core/src/common' {
  declare module.exports: any;
}

declare module '@boldr/core/src/server' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/boldr/actionTypes' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/boldr/index' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/boldr/notifications/index' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/boldr/notifications/notifications' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/boldr/notifications/notifications.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/boldr/reducer' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/boldr/reducer.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/boldr/settings/reducer' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/boldr/ui/actions' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/boldr/ui/actions.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/boldr/ui/index' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/boldr/ui/reducer' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/boldr/ui/reducer.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/createApolloClient' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/createApolloClient.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/createBoldrStore' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/createBoldrStore.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/flattenRoutes' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/RouterConnection' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/validations' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/wrapBoldrApp' {
  declare module.exports: any;
}

declare module '@boldr/core/src/util/batchNetworkInterface' {
  declare module.exports: any;
}

declare module '@boldr/core/src/util/debug' {
  declare module.exports: any;
}

declare module '@boldr/core/src/util/extractFiles' {
  declare module.exports: any;
}

declare module '@boldr/core/src/util/networkInterface' {
  declare module.exports: any;
}

// Filename aliases
declare module '@boldr/core/index' {
  declare module.exports: $Exports<'@boldr/core'>;
}
declare module '@boldr/core/index.js' {
  declare module.exports: $Exports<'@boldr/core'>;
}
declare module '@boldr/core/lib/boldr-core.browser.es2015.esm.js' {
  declare module.exports: $Exports<'@boldr/core/lib/boldr-core.browser.es2015.esm'>;
}
declare module '@boldr/core/lib/boldr-core.browser.es5.esm.js' {
  declare module.exports: $Exports<'@boldr/core/lib/boldr-core.browser.es5.esm'>;
}
declare module '@boldr/core/lib/boldr-core.node.es2015.cjs.js' {
  declare module.exports: $Exports<'@boldr/core/lib/boldr-core.node.es2015.cjs'>;
}
declare module '@boldr/core/lib/boldr-core.node.es2015.esm.js' {
  declare module.exports: $Exports<'@boldr/core/lib/boldr-core.node.es2015.esm'>;
}
declare module '@boldr/core/lib/boldr-core.node.es5.cjs.js' {
  declare module.exports: $Exports<'@boldr/core/lib/boldr-core.node.es5.cjs'>;
}
declare module '@boldr/core/lib/boldr-core.node.es5.esm.js' {
  declare module.exports: $Exports<'@boldr/core/lib/boldr-core.node.es5.esm'>;
}
declare module '@boldr/core/src/client.js' {
  declare module.exports: $Exports<'@boldr/core/src/client'>;
}
declare module '@boldr/core/src/client/renderBoldrApp.js' {
  declare module.exports: $Exports<'@boldr/core/src/client/renderBoldrApp'>;
}
declare module '@boldr/core/src/common.js' {
  declare module.exports: $Exports<'@boldr/core/src/common'>;
}
declare module '@boldr/core/src/server.js' {
  declare module.exports: $Exports<'@boldr/core/src/server'>;
}
declare module '@boldr/core/src/shared/boldr/actionTypes.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/boldr/actionTypes'>;
}
declare module '@boldr/core/src/shared/boldr/index.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/boldr/index'>;
}
declare module '@boldr/core/src/shared/boldr/notifications/index.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/boldr/notifications/index'>;
}
declare module '@boldr/core/src/shared/boldr/notifications/notifications.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/boldr/notifications/notifications'>;
}
declare module '@boldr/core/src/shared/boldr/notifications/notifications.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/boldr/notifications/notifications.test'>;
}
declare module '@boldr/core/src/shared/boldr/reducer.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/boldr/reducer'>;
}
declare module '@boldr/core/src/shared/boldr/reducer.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/boldr/reducer.test'>;
}
declare module '@boldr/core/src/shared/boldr/settings/reducer.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/boldr/settings/reducer'>;
}
declare module '@boldr/core/src/shared/boldr/ui/actions.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/boldr/ui/actions'>;
}
declare module '@boldr/core/src/shared/boldr/ui/actions.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/boldr/ui/actions.test'>;
}
declare module '@boldr/core/src/shared/boldr/ui/index.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/boldr/ui/index'>;
}
declare module '@boldr/core/src/shared/boldr/ui/reducer.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/boldr/ui/reducer'>;
}
declare module '@boldr/core/src/shared/boldr/ui/reducer.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/boldr/ui/reducer.test'>;
}
declare module '@boldr/core/src/shared/createApolloClient.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/createApolloClient'>;
}
declare module '@boldr/core/src/shared/createApolloClient.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/createApolloClient.test'>;
}
declare module '@boldr/core/src/shared/createBoldrStore.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/createBoldrStore'>;
}
declare module '@boldr/core/src/shared/createBoldrStore.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/createBoldrStore.test'>;
}
declare module '@boldr/core/src/shared/flattenRoutes.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/flattenRoutes'>;
}
declare module '@boldr/core/src/shared/RouterConnection.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/RouterConnection'>;
}
declare module '@boldr/core/src/shared/validations.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/validations'>;
}
declare module '@boldr/core/src/shared/wrapBoldrApp.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/wrapBoldrApp'>;
}
declare module '@boldr/core/src/util/batchNetworkInterface.js' {
  declare module.exports: $Exports<'@boldr/core/src/util/batchNetworkInterface'>;
}
declare module '@boldr/core/src/util/debug.js' {
  declare module.exports: $Exports<'@boldr/core/src/util/debug'>;
}
declare module '@boldr/core/src/util/extractFiles.js' {
  declare module.exports: $Exports<'@boldr/core/src/util/extractFiles'>;
}
declare module '@boldr/core/src/util/networkInterface.js' {
  declare module.exports: $Exports<'@boldr/core/src/util/networkInterface'>;
}
