// flow-typed signature: ed7d7e89390234c6bf0b2879f3236890
// flow-typed version: <<STUB>>/@boldr/utils_v^0.1.0-rc.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@boldr/utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@boldr/utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@boldr/utils/__tests__/arrays/addIdToArray.test' {
  declare module.exports: any;
}

declare module '@boldr/utils/__tests__/arrays/flatten.test' {
  declare module.exports: any;
}

declare module '@boldr/utils/__tests__/arrays/merge.test' {
  declare module.exports: any;
}

declare module '@boldr/utils/__tests__/arrays/removeIdFromArray.test' {
  declare module.exports: any;
}

declare module '@boldr/utils/__tests__/arrays/removeNil.test' {
  declare module.exports: any;
}

declare module '@boldr/utils/__tests__/arrays/uniqueArray.test' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/arrays/addIdToArray' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/arrays/concatAll' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/arrays/flatten' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/arrays/merge' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/arrays/reduce' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/arrays/removeEmpty' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/arrays/removeIdFromArray' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/arrays/removeKeyFromNestedArray' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/arrays/removeNil' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/arrays/uniqueArray' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/arrays/zip' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/gql/firstResult' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/gql/jsonResult' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/index' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/logger' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/logic/curry' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/logic/curryN' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/logic/ifElse' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/logic/isPromise' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/logic/onlyIf' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/logic/requiredParam' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/logic/sort' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/logic/tap' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/logic/uniq' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/logic/validateId' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/node/appRoot' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/node/clearConsole' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/node/getDefault' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/node/ifIsFile' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/node/logDeep' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/objects/filterEmpty' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/objects/getField' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/objects/mergeDeep' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/objects/removeByKey' {
  declare module.exports: any;
}

declare module '@boldr/utils/lib/strings/toTitle' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/arrays/addIdToArray' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/arrays/concatAll' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/arrays/flatten' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/arrays/merge' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/arrays/reduce' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/arrays/removeEmpty' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/arrays/removeIdFromArray' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/arrays/removeKeyFromNestedArray' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/arrays/removeNil' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/arrays/uniqueArray' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/arrays/zip' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/gql/firstResult' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/gql/jsonResult' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/index' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/logger' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/logic/curry' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/logic/curryN' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/logic/ifElse' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/logic/isPromise' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/logic/onlyIf' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/logic/requiredParam' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/logic/sort' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/logic/tap' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/logic/uniq' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/logic/validateId' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/node/appRoot' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/node/clearConsole' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/node/getDefault' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/node/ifIsFile' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/node/logDeep' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/objects/filterEmpty' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/objects/getField' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/objects/mergeDeep' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/objects/removeByKey' {
  declare module.exports: any;
}

declare module '@boldr/utils/src/strings/toTitle' {
  declare module.exports: any;
}

// Filename aliases
declare module '@boldr/utils/__tests__/arrays/addIdToArray.test.js' {
  declare module.exports: $Exports<'@boldr/utils/__tests__/arrays/addIdToArray.test'>;
}
declare module '@boldr/utils/__tests__/arrays/flatten.test.js' {
  declare module.exports: $Exports<'@boldr/utils/__tests__/arrays/flatten.test'>;
}
declare module '@boldr/utils/__tests__/arrays/merge.test.js' {
  declare module.exports: $Exports<'@boldr/utils/__tests__/arrays/merge.test'>;
}
declare module '@boldr/utils/__tests__/arrays/removeIdFromArray.test.js' {
  declare module.exports: $Exports<'@boldr/utils/__tests__/arrays/removeIdFromArray.test'>;
}
declare module '@boldr/utils/__tests__/arrays/removeNil.test.js' {
  declare module.exports: $Exports<'@boldr/utils/__tests__/arrays/removeNil.test'>;
}
declare module '@boldr/utils/__tests__/arrays/uniqueArray.test.js' {
  declare module.exports: $Exports<'@boldr/utils/__tests__/arrays/uniqueArray.test'>;
}
declare module '@boldr/utils/lib/arrays/addIdToArray.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/arrays/addIdToArray'>;
}
declare module '@boldr/utils/lib/arrays/concatAll.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/arrays/concatAll'>;
}
declare module '@boldr/utils/lib/arrays/flatten.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/arrays/flatten'>;
}
declare module '@boldr/utils/lib/arrays/merge.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/arrays/merge'>;
}
declare module '@boldr/utils/lib/arrays/reduce.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/arrays/reduce'>;
}
declare module '@boldr/utils/lib/arrays/removeEmpty.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/arrays/removeEmpty'>;
}
declare module '@boldr/utils/lib/arrays/removeIdFromArray.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/arrays/removeIdFromArray'>;
}
declare module '@boldr/utils/lib/arrays/removeKeyFromNestedArray.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/arrays/removeKeyFromNestedArray'>;
}
declare module '@boldr/utils/lib/arrays/removeNil.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/arrays/removeNil'>;
}
declare module '@boldr/utils/lib/arrays/uniqueArray.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/arrays/uniqueArray'>;
}
declare module '@boldr/utils/lib/arrays/zip.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/arrays/zip'>;
}
declare module '@boldr/utils/lib/gql/firstResult.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/gql/firstResult'>;
}
declare module '@boldr/utils/lib/gql/jsonResult.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/gql/jsonResult'>;
}
declare module '@boldr/utils/lib/index.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/index'>;
}
declare module '@boldr/utils/lib/logger.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/logger'>;
}
declare module '@boldr/utils/lib/logic/curry.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/logic/curry'>;
}
declare module '@boldr/utils/lib/logic/curryN.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/logic/curryN'>;
}
declare module '@boldr/utils/lib/logic/ifElse.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/logic/ifElse'>;
}
declare module '@boldr/utils/lib/logic/isPromise.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/logic/isPromise'>;
}
declare module '@boldr/utils/lib/logic/onlyIf.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/logic/onlyIf'>;
}
declare module '@boldr/utils/lib/logic/requiredParam.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/logic/requiredParam'>;
}
declare module '@boldr/utils/lib/logic/sort.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/logic/sort'>;
}
declare module '@boldr/utils/lib/logic/tap.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/logic/tap'>;
}
declare module '@boldr/utils/lib/logic/uniq.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/logic/uniq'>;
}
declare module '@boldr/utils/lib/logic/validateId.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/logic/validateId'>;
}
declare module '@boldr/utils/lib/node/appRoot.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/node/appRoot'>;
}
declare module '@boldr/utils/lib/node/clearConsole.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/node/clearConsole'>;
}
declare module '@boldr/utils/lib/node/getDefault.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/node/getDefault'>;
}
declare module '@boldr/utils/lib/node/ifIsFile.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/node/ifIsFile'>;
}
declare module '@boldr/utils/lib/node/logDeep.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/node/logDeep'>;
}
declare module '@boldr/utils/lib/objects/filterEmpty.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/objects/filterEmpty'>;
}
declare module '@boldr/utils/lib/objects/getField.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/objects/getField'>;
}
declare module '@boldr/utils/lib/objects/mergeDeep.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/objects/mergeDeep'>;
}
declare module '@boldr/utils/lib/objects/removeByKey.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/objects/removeByKey'>;
}
declare module '@boldr/utils/lib/strings/toTitle.js' {
  declare module.exports: $Exports<'@boldr/utils/lib/strings/toTitle'>;
}
declare module '@boldr/utils/src/arrays/addIdToArray.js' {
  declare module.exports: $Exports<'@boldr/utils/src/arrays/addIdToArray'>;
}
declare module '@boldr/utils/src/arrays/concatAll.js' {
  declare module.exports: $Exports<'@boldr/utils/src/arrays/concatAll'>;
}
declare module '@boldr/utils/src/arrays/flatten.js' {
  declare module.exports: $Exports<'@boldr/utils/src/arrays/flatten'>;
}
declare module '@boldr/utils/src/arrays/merge.js' {
  declare module.exports: $Exports<'@boldr/utils/src/arrays/merge'>;
}
declare module '@boldr/utils/src/arrays/reduce.js' {
  declare module.exports: $Exports<'@boldr/utils/src/arrays/reduce'>;
}
declare module '@boldr/utils/src/arrays/removeEmpty.js' {
  declare module.exports: $Exports<'@boldr/utils/src/arrays/removeEmpty'>;
}
declare module '@boldr/utils/src/arrays/removeIdFromArray.js' {
  declare module.exports: $Exports<'@boldr/utils/src/arrays/removeIdFromArray'>;
}
declare module '@boldr/utils/src/arrays/removeKeyFromNestedArray.js' {
  declare module.exports: $Exports<'@boldr/utils/src/arrays/removeKeyFromNestedArray'>;
}
declare module '@boldr/utils/src/arrays/removeNil.js' {
  declare module.exports: $Exports<'@boldr/utils/src/arrays/removeNil'>;
}
declare module '@boldr/utils/src/arrays/uniqueArray.js' {
  declare module.exports: $Exports<'@boldr/utils/src/arrays/uniqueArray'>;
}
declare module '@boldr/utils/src/arrays/zip.js' {
  declare module.exports: $Exports<'@boldr/utils/src/arrays/zip'>;
}
declare module '@boldr/utils/src/gql/firstResult.js' {
  declare module.exports: $Exports<'@boldr/utils/src/gql/firstResult'>;
}
declare module '@boldr/utils/src/gql/jsonResult.js' {
  declare module.exports: $Exports<'@boldr/utils/src/gql/jsonResult'>;
}
declare module '@boldr/utils/src/index.js' {
  declare module.exports: $Exports<'@boldr/utils/src/index'>;
}
declare module '@boldr/utils/src/logger.js' {
  declare module.exports: $Exports<'@boldr/utils/src/logger'>;
}
declare module '@boldr/utils/src/logic/curry.js' {
  declare module.exports: $Exports<'@boldr/utils/src/logic/curry'>;
}
declare module '@boldr/utils/src/logic/curryN.js' {
  declare module.exports: $Exports<'@boldr/utils/src/logic/curryN'>;
}
declare module '@boldr/utils/src/logic/ifElse.js' {
  declare module.exports: $Exports<'@boldr/utils/src/logic/ifElse'>;
}
declare module '@boldr/utils/src/logic/isPromise.js' {
  declare module.exports: $Exports<'@boldr/utils/src/logic/isPromise'>;
}
declare module '@boldr/utils/src/logic/onlyIf.js' {
  declare module.exports: $Exports<'@boldr/utils/src/logic/onlyIf'>;
}
declare module '@boldr/utils/src/logic/requiredParam.js' {
  declare module.exports: $Exports<'@boldr/utils/src/logic/requiredParam'>;
}
declare module '@boldr/utils/src/logic/sort.js' {
  declare module.exports: $Exports<'@boldr/utils/src/logic/sort'>;
}
declare module '@boldr/utils/src/logic/tap.js' {
  declare module.exports: $Exports<'@boldr/utils/src/logic/tap'>;
}
declare module '@boldr/utils/src/logic/uniq.js' {
  declare module.exports: $Exports<'@boldr/utils/src/logic/uniq'>;
}
declare module '@boldr/utils/src/logic/validateId.js' {
  declare module.exports: $Exports<'@boldr/utils/src/logic/validateId'>;
}
declare module '@boldr/utils/src/node/appRoot.js' {
  declare module.exports: $Exports<'@boldr/utils/src/node/appRoot'>;
}
declare module '@boldr/utils/src/node/clearConsole.js' {
  declare module.exports: $Exports<'@boldr/utils/src/node/clearConsole'>;
}
declare module '@boldr/utils/src/node/getDefault.js' {
  declare module.exports: $Exports<'@boldr/utils/src/node/getDefault'>;
}
declare module '@boldr/utils/src/node/ifIsFile.js' {
  declare module.exports: $Exports<'@boldr/utils/src/node/ifIsFile'>;
}
declare module '@boldr/utils/src/node/logDeep.js' {
  declare module.exports: $Exports<'@boldr/utils/src/node/logDeep'>;
}
declare module '@boldr/utils/src/objects/filterEmpty.js' {
  declare module.exports: $Exports<'@boldr/utils/src/objects/filterEmpty'>;
}
declare module '@boldr/utils/src/objects/getField.js' {
  declare module.exports: $Exports<'@boldr/utils/src/objects/getField'>;
}
declare module '@boldr/utils/src/objects/mergeDeep.js' {
  declare module.exports: $Exports<'@boldr/utils/src/objects/mergeDeep'>;
}
declare module '@boldr/utils/src/objects/removeByKey.js' {
  declare module.exports: $Exports<'@boldr/utils/src/objects/removeByKey'>;
}
declare module '@boldr/utils/src/strings/toTitle.js' {
  declare module.exports: $Exports<'@boldr/utils/src/strings/toTitle'>;
}
