module.exports = {
  verbose: true,
  moduleNameMapper: {
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      './internal/jest/fileMock.js',
    '\\.(css|scss)$': 'identity-obj-proxy',
  },
  moduleFileExtensions: ['js', 'jsx'],
  moduleDirectories: ['node_modules', 'packages', 'project'],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/__fixtures__/',
    '<rootDir>/packages/editor',
    '<rootDir>/packages/*/(internal|build|lib|dist|.boldr)/',
    '<rootDir>/project/(internal|build|lib|dist|.boldr)/',
    '/__snapshots__/',
  ],
  testEnvironment: 'jsdom',
  setupTestFrameworkScriptFile: './node_modules/jest-enzyme/lib/index.js',
  setupFiles: ['raf/polyfill', './internal/jest/setup.js'],
  transform: {
    '^.+\\.jsx?$': './internal/jest/transform.js',
    '\\.(gql|graphql)$': 'jest-transform-graphql',
  },
  collectCoverage: false,
  collectCoverageFrom: [
    'packages/core/src/**/*.js',
    'packages/config/src/**/*.js',
    'project/src/**/*.js',
    'packages/utils/src/**/*.js',
    '!packages/utils/src/node/*.js',
    '!packages/core/src/util/*.js',
    '!packages/core/src/apollo/batchNetworkInterface.js',
    '!packages/core/src/apollo/networkInterface.js',
    '!packages/core/src/apollo/extractFiles.js',
    '!packages/core/src/client/configBrowser.js',
    '!packages/core/src/client.js',
    '!packages/core/src/common.js',
    '!packages/core/src/server.js',
    '!project/src/clientEntry.js',
    '!project/src/serverEntry.js',
    '!project/src/theme/*.js',
    '!packages/**/index.js',
  ],
  coveragePathIgnorePatterns: [
    '/flow-typed/',
    '/__fixtures__/',
    '<rootDir>/packages/tools/',
    '<rootDir>/packages/server/',
    '<rootDir>/packages/cli',
    '<rootDir>/node_modules/',
    '<rootDir>/packages/*/node_modules/',
  ],
  coverageDirectory: 'coverage',
};
