// flow-typed signature: 88b793a69019fbf76dd7c4ac406dc7ce
// flow-typed version: <<STUB>>/animate-components_v^0.9.4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'animate-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'animate-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'animate-components/dist/animations/Bingo/index' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/Bingo/styledBingo' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/bounce/index' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/bounce/styledBounce' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/expanse/index' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/expanse/styledExpanse' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/fade/index' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/fade/styledFade' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/flip/index' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/flip/styledFlip' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/HOC' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/lightspeed/index' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/lightspeed/styledLight' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/merge' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/perspective/index' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/perspective/styledPerspective' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/rotate/index' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/rotate/styledRotate' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/slide/index' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/slide/styledSlide' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/special' {
  declare module.exports: any;
}

declare module 'animate-components/dist/animations/styledSpecial' {
  declare module.exports: any;
}

declare module 'animate-components/dist/mods/getElementType' {
  declare module.exports: any;
}

declare module 'animate-components/dist/utils/mergeValidators' {
  declare module.exports: any;
}

declare module 'animate-components/dist/utils/propsValidator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'animate-components/dist/animations/Bingo/index.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/Bingo/index'>;
}
declare module 'animate-components/dist/animations/Bingo/styledBingo.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/Bingo/styledBingo'>;
}
declare module 'animate-components/dist/animations/bounce/index.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/bounce/index'>;
}
declare module 'animate-components/dist/animations/bounce/styledBounce.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/bounce/styledBounce'>;
}
declare module 'animate-components/dist/animations/expanse/index.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/expanse/index'>;
}
declare module 'animate-components/dist/animations/expanse/styledExpanse.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/expanse/styledExpanse'>;
}
declare module 'animate-components/dist/animations/fade/index.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/fade/index'>;
}
declare module 'animate-components/dist/animations/fade/styledFade.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/fade/styledFade'>;
}
declare module 'animate-components/dist/animations/flip/index.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/flip/index'>;
}
declare module 'animate-components/dist/animations/flip/styledFlip.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/flip/styledFlip'>;
}
declare module 'animate-components/dist/animations/HOC.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/HOC'>;
}
declare module 'animate-components/dist/animations/lightspeed/index.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/lightspeed/index'>;
}
declare module 'animate-components/dist/animations/lightspeed/styledLight.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/lightspeed/styledLight'>;
}
declare module 'animate-components/dist/animations/merge.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/merge'>;
}
declare module 'animate-components/dist/animations/perspective/index.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/perspective/index'>;
}
declare module 'animate-components/dist/animations/perspective/styledPerspective.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/perspective/styledPerspective'>;
}
declare module 'animate-components/dist/animations/rotate/index.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/rotate/index'>;
}
declare module 'animate-components/dist/animations/rotate/styledRotate.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/rotate/styledRotate'>;
}
declare module 'animate-components/dist/animations/slide/index.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/slide/index'>;
}
declare module 'animate-components/dist/animations/slide/styledSlide.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/slide/styledSlide'>;
}
declare module 'animate-components/dist/animations/special.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/special'>;
}
declare module 'animate-components/dist/animations/styledSpecial.js' {
  declare module.exports: $Exports<'animate-components/dist/animations/styledSpecial'>;
}
declare module 'animate-components/dist/mods/getElementType.js' {
  declare module.exports: $Exports<'animate-components/dist/mods/getElementType'>;
}
declare module 'animate-components/dist/utils/mergeValidators.js' {
  declare module.exports: $Exports<'animate-components/dist/utils/mergeValidators'>;
}
declare module 'animate-components/dist/utils/propsValidator.js' {
  declare module.exports: $Exports<'animate-components/dist/utils/propsValidator'>;
}
declare module 'animate-components/index' {
  declare module.exports: $Exports<'animate-components'>;
}
declare module 'animate-components/index.js' {
  declare module.exports: $Exports<'animate-components'>;
}
