// flow-typed signature: ac9f1c37156ef29b6be1d3fd171ca012
// flow-typed version: <<STUB>>/apidoc-markdown_v^0.2.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apidoc-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'apidoc-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'apidoc-markdown/index' {
  declare module.exports: $Exports<'apidoc-markdown'>;
}
declare module 'apidoc-markdown/index.js' {
  declare module.exports: $Exports<'apidoc-markdown'>;
}
