// flow-typed signature: a3a52c5973134000b2abaedd8328a430
// flow-typed version: <<STUB>>/babel-preset-boldr_v^0.9.6/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-boldr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-boldr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-boldr/browser' {
  declare module.exports: any;
}

declare module 'babel-preset-boldr/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-boldr/browser.js' {
  declare module.exports: $Exports<'babel-preset-boldr/browser'>;
}
declare module 'babel-preset-boldr/index' {
  declare module.exports: $Exports<'babel-preset-boldr'>;
}
declare module 'babel-preset-boldr/index.js' {
  declare module.exports: $Exports<'babel-preset-boldr'>;
}
declare module 'babel-preset-boldr/node.js' {
  declare module.exports: $Exports<'babel-preset-boldr/node'>;
}
