// flow-typed signature: 9f3c9a0e0133eec02fbf66ef6375f4de
// flow-typed version: <<STUB>>/babel-preset-boldr_v0.1.4/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-boldr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-boldr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-boldr/index' {
  declare module.exports: $Exports<'babel-preset-boldr'>;
}
declare module 'babel-preset-boldr/index.js' {
  declare module.exports: $Exports<'babel-preset-boldr'>;
}
