// flow-typed signature: 4a995d7fe175abde6bc6f88d5a09b0c4
// flow-typed version: <<STUB>>/babel-code-frame_v^6.22.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-code-frame'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-code-frame' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-code-frame/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-code-frame/lib/index.js' {
  declare module.exports: $Exports<'babel-code-frame/lib/index'>;
}
