// flow-typed signature: ebcb259b12061f2bae221fc138c6ab40
// flow-typed version: <<STUB>>/babel-plugin-dual-import_v^1.1.1/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-dual-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-dual-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-dual-import/importCss' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-dual-import/importCss.js' {
  declare module.exports: $Exports<'babel-plugin-dual-import/importCss'>;
}
declare module 'babel-plugin-dual-import/index' {
  declare module.exports: $Exports<'babel-plugin-dual-import'>;
}
declare module 'babel-plugin-dual-import/index.js' {
  declare module.exports: $Exports<'babel-plugin-dual-import'>;
}
