// flow-typed signature: d4d792b341e1bef238744d5a5c2845dd
// flow-typed version: <<STUB>>/boldr-editor_v^0.6.6/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boldr-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'boldr-editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boldr-editor/lib/BoldrEditor' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/controls/BlockStyle/BlockStyle' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/controls/BlockStyle/index' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/controls/CustomBlock/CustomBlock' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/controls/CustomBlock/index' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/controls/helpers' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/controls/index' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/controls/InlineStyle/index' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/controls/InlineStyle/InlineStyle' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/controls/StyleButton/index' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/controls/StyleButton/StyleButton' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/decorators/defaultDecorator' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Blockquote' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Blockquote.test' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Bold' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Bold.test' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Codeblock' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Codeblock.test' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/H1' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/H1.test' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/H2' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/H2.test' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/H3' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/H3.test' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/H4' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/H4.test' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/H5' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/H5.test' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/H6' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/H6.test' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/index' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Italic' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Italic.test' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Link' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Link.test' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Monospace' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Monospace.test' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/OrderedList' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/OrderedList.test' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Photo' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Photo.test' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Underline' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Underline.test' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/UnorderedList' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/UnorderedList.test' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Video' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/icons/Video.test' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/index' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/lib/EditorValue' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/plugins/ImgBlockPlugin/ImgBlockPlugin' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/plugins/ImgBlockPlugin/index' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/plugins/index' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/plugins/VidBlockPlugin/index' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/plugins/VidBlockPlugin/VidBlockPlugin' {
  declare module.exports: any;
}

declare module 'boldr-editor/lib/Renderer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boldr-editor/lib/BoldrEditor.js' {
  declare module.exports: $Exports<'boldr-editor/lib/BoldrEditor'>;
}
declare module 'boldr-editor/lib/controls/BlockStyle/BlockStyle.js' {
  declare module.exports: $Exports<'boldr-editor/lib/controls/BlockStyle/BlockStyle'>;
}
declare module 'boldr-editor/lib/controls/BlockStyle/index.js' {
  declare module.exports: $Exports<'boldr-editor/lib/controls/BlockStyle/index'>;
}
declare module 'boldr-editor/lib/controls/CustomBlock/CustomBlock.js' {
  declare module.exports: $Exports<'boldr-editor/lib/controls/CustomBlock/CustomBlock'>;
}
declare module 'boldr-editor/lib/controls/CustomBlock/index.js' {
  declare module.exports: $Exports<'boldr-editor/lib/controls/CustomBlock/index'>;
}
declare module 'boldr-editor/lib/controls/helpers.js' {
  declare module.exports: $Exports<'boldr-editor/lib/controls/helpers'>;
}
declare module 'boldr-editor/lib/controls/index.js' {
  declare module.exports: $Exports<'boldr-editor/lib/controls/index'>;
}
declare module 'boldr-editor/lib/controls/InlineStyle/index.js' {
  declare module.exports: $Exports<'boldr-editor/lib/controls/InlineStyle/index'>;
}
declare module 'boldr-editor/lib/controls/InlineStyle/InlineStyle.js' {
  declare module.exports: $Exports<'boldr-editor/lib/controls/InlineStyle/InlineStyle'>;
}
declare module 'boldr-editor/lib/controls/StyleButton/index.js' {
  declare module.exports: $Exports<'boldr-editor/lib/controls/StyleButton/index'>;
}
declare module 'boldr-editor/lib/controls/StyleButton/StyleButton.js' {
  declare module.exports: $Exports<'boldr-editor/lib/controls/StyleButton/StyleButton'>;
}
declare module 'boldr-editor/lib/decorators/defaultDecorator.js' {
  declare module.exports: $Exports<'boldr-editor/lib/decorators/defaultDecorator'>;
}
declare module 'boldr-editor/lib/icons/Blockquote.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Blockquote'>;
}
declare module 'boldr-editor/lib/icons/Blockquote.test.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Blockquote.test'>;
}
declare module 'boldr-editor/lib/icons/Bold.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Bold'>;
}
declare module 'boldr-editor/lib/icons/Bold.test.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Bold.test'>;
}
declare module 'boldr-editor/lib/icons/Codeblock.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Codeblock'>;
}
declare module 'boldr-editor/lib/icons/Codeblock.test.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Codeblock.test'>;
}
declare module 'boldr-editor/lib/icons/H1.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/H1'>;
}
declare module 'boldr-editor/lib/icons/H1.test.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/H1.test'>;
}
declare module 'boldr-editor/lib/icons/H2.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/H2'>;
}
declare module 'boldr-editor/lib/icons/H2.test.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/H2.test'>;
}
declare module 'boldr-editor/lib/icons/H3.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/H3'>;
}
declare module 'boldr-editor/lib/icons/H3.test.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/H3.test'>;
}
declare module 'boldr-editor/lib/icons/H4.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/H4'>;
}
declare module 'boldr-editor/lib/icons/H4.test.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/H4.test'>;
}
declare module 'boldr-editor/lib/icons/H5.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/H5'>;
}
declare module 'boldr-editor/lib/icons/H5.test.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/H5.test'>;
}
declare module 'boldr-editor/lib/icons/H6.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/H6'>;
}
declare module 'boldr-editor/lib/icons/H6.test.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/H6.test'>;
}
declare module 'boldr-editor/lib/icons/index.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/index'>;
}
declare module 'boldr-editor/lib/icons/Italic.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Italic'>;
}
declare module 'boldr-editor/lib/icons/Italic.test.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Italic.test'>;
}
declare module 'boldr-editor/lib/icons/Link.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Link'>;
}
declare module 'boldr-editor/lib/icons/Link.test.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Link.test'>;
}
declare module 'boldr-editor/lib/icons/Monospace.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Monospace'>;
}
declare module 'boldr-editor/lib/icons/Monospace.test.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Monospace.test'>;
}
declare module 'boldr-editor/lib/icons/OrderedList.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/OrderedList'>;
}
declare module 'boldr-editor/lib/icons/OrderedList.test.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/OrderedList.test'>;
}
declare module 'boldr-editor/lib/icons/Photo.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Photo'>;
}
declare module 'boldr-editor/lib/icons/Photo.test.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Photo.test'>;
}
declare module 'boldr-editor/lib/icons/Underline.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Underline'>;
}
declare module 'boldr-editor/lib/icons/Underline.test.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Underline.test'>;
}
declare module 'boldr-editor/lib/icons/UnorderedList.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/UnorderedList'>;
}
declare module 'boldr-editor/lib/icons/UnorderedList.test.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/UnorderedList.test'>;
}
declare module 'boldr-editor/lib/icons/Video.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Video'>;
}
declare module 'boldr-editor/lib/icons/Video.test.js' {
  declare module.exports: $Exports<'boldr-editor/lib/icons/Video.test'>;
}
declare module 'boldr-editor/lib/index.js' {
  declare module.exports: $Exports<'boldr-editor/lib/index'>;
}
declare module 'boldr-editor/lib/lib/EditorValue.js' {
  declare module.exports: $Exports<'boldr-editor/lib/lib/EditorValue'>;
}
declare module 'boldr-editor/lib/plugins/ImgBlockPlugin/ImgBlockPlugin.js' {
  declare module.exports: $Exports<'boldr-editor/lib/plugins/ImgBlockPlugin/ImgBlockPlugin'>;
}
declare module 'boldr-editor/lib/plugins/ImgBlockPlugin/index.js' {
  declare module.exports: $Exports<'boldr-editor/lib/plugins/ImgBlockPlugin/index'>;
}
declare module 'boldr-editor/lib/plugins/index.js' {
  declare module.exports: $Exports<'boldr-editor/lib/plugins/index'>;
}
declare module 'boldr-editor/lib/plugins/VidBlockPlugin/index.js' {
  declare module.exports: $Exports<'boldr-editor/lib/plugins/VidBlockPlugin/index'>;
}
declare module 'boldr-editor/lib/plugins/VidBlockPlugin/VidBlockPlugin.js' {
  declare module.exports: $Exports<'boldr-editor/lib/plugins/VidBlockPlugin/VidBlockPlugin'>;
}
declare module 'boldr-editor/lib/Renderer.js' {
  declare module.exports: $Exports<'boldr-editor/lib/Renderer'>;
}
