// flow-typed signature: 0ee144f13316d27ca4b9e1110acdd696
// flow-typed version: <<STUB>>/boldr-utils_v0.3.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boldr-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'boldr-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boldr-utils/dist/arrays/addIdToArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/arrays/flatten' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/arrays/joinAnd' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/arrays/merge' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/arrays/removeIdFromArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/arrays/removeKeyFromNestedArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/arrays/removeNil' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/arrays/stringifiedArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/arrays/uniqueArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/arrays/validateArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/dom/getPositionedParent' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/dom/getViewportSize' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/dom/isBrowser' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/gql/errors' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/gql/firstResult' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/gql/jsonResult' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/index' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/logger' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/logic/ifElse' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/logic/isPromise' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/logic/requiredParam' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/logic/sort' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/logic/typeOf' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/logic/uniq' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/logic/validateId' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/node/appRoot' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/node/clearConsole' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/node/ifIsFile' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/node/logDeep' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/objects/filterEmpty' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/objects/filterWithRules' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/objects/getField' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/objects/getIn' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/objects/mergeDeep' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/objects/removeByKey' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/objects/setIn' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/state/reduceKey' {
  declare module.exports: any;
}

declare module 'boldr-utils/dist/strings/toTitle' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/arrays/addIdToArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/arrays/flatten' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/arrays/joinAnd' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/arrays/merge' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/arrays/removeIdFromArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/arrays/removeKeyFromNestedArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/arrays/removeNil' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/arrays/stringifiedArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/arrays/uniqueArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/arrays/validateArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/dom/getPositionedParent' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/dom/getViewportSize' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/dom/isBrowser' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/gql/errors' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/gql/firstResult' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/gql/jsonResult' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/index' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/logger' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/logic/ifElse' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/logic/isPromise' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/logic/requiredParam' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/logic/sort' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/logic/typeOf' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/logic/uniq' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/logic/validateId' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/node/appRoot' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/node/clearConsole' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/node/ifIsFile' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/node/logDeep' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/objects/filterEmpty' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/objects/filterWithRules' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/objects/getField' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/objects/getIn' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/objects/mergeDeep' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/objects/removeByKey' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/objects/setIn' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/state/reduceKey' {
  declare module.exports: any;
}

declare module 'boldr-utils/es/strings/toTitle' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/arrays/addIdToArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/arrays/flatten' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/arrays/joinAnd' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/arrays/merge' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/arrays/removeIdFromArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/arrays/removeKeyFromNestedArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/arrays/removeNil' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/arrays/stringifiedArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/arrays/uniqueArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/arrays/validateArray' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/dom/getPositionedParent' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/dom/getViewportSize' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/dom/isBrowser' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/gql/errors' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/gql/firstResult' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/gql/jsonResult' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/index' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/logger' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/logic/ifElse' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/logic/isPromise' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/logic/requiredParam' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/logic/sort' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/logic/typeOf' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/logic/uniq' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/logic/validateId' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/node/appRoot' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/node/clearConsole' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/node/ifIsFile' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/node/logDeep' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/objects/filterEmpty' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/objects/filterWithRules' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/objects/getField' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/objects/getIn' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/objects/mergeDeep' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/objects/removeByKey' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/objects/setIn' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/state/reduceKey' {
  declare module.exports: any;
}

declare module 'boldr-utils/src/strings/toTitle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boldr-utils/dist/arrays/addIdToArray.js' {
  declare module.exports: $Exports<'boldr-utils/dist/arrays/addIdToArray'>;
}
declare module 'boldr-utils/dist/arrays/flatten.js' {
  declare module.exports: $Exports<'boldr-utils/dist/arrays/flatten'>;
}
declare module 'boldr-utils/dist/arrays/joinAnd.js' {
  declare module.exports: $Exports<'boldr-utils/dist/arrays/joinAnd'>;
}
declare module 'boldr-utils/dist/arrays/merge.js' {
  declare module.exports: $Exports<'boldr-utils/dist/arrays/merge'>;
}
declare module 'boldr-utils/dist/arrays/removeIdFromArray.js' {
  declare module.exports: $Exports<'boldr-utils/dist/arrays/removeIdFromArray'>;
}
declare module 'boldr-utils/dist/arrays/removeKeyFromNestedArray.js' {
  declare module.exports: $Exports<'boldr-utils/dist/arrays/removeKeyFromNestedArray'>;
}
declare module 'boldr-utils/dist/arrays/removeNil.js' {
  declare module.exports: $Exports<'boldr-utils/dist/arrays/removeNil'>;
}
declare module 'boldr-utils/dist/arrays/stringifiedArray.js' {
  declare module.exports: $Exports<'boldr-utils/dist/arrays/stringifiedArray'>;
}
declare module 'boldr-utils/dist/arrays/uniqueArray.js' {
  declare module.exports: $Exports<'boldr-utils/dist/arrays/uniqueArray'>;
}
declare module 'boldr-utils/dist/arrays/validateArray.js' {
  declare module.exports: $Exports<'boldr-utils/dist/arrays/validateArray'>;
}
declare module 'boldr-utils/dist/dom/getPositionedParent.js' {
  declare module.exports: $Exports<'boldr-utils/dist/dom/getPositionedParent'>;
}
declare module 'boldr-utils/dist/dom/getViewportSize.js' {
  declare module.exports: $Exports<'boldr-utils/dist/dom/getViewportSize'>;
}
declare module 'boldr-utils/dist/dom/isBrowser.js' {
  declare module.exports: $Exports<'boldr-utils/dist/dom/isBrowser'>;
}
declare module 'boldr-utils/dist/gql/errors.js' {
  declare module.exports: $Exports<'boldr-utils/dist/gql/errors'>;
}
declare module 'boldr-utils/dist/gql/firstResult.js' {
  declare module.exports: $Exports<'boldr-utils/dist/gql/firstResult'>;
}
declare module 'boldr-utils/dist/gql/jsonResult.js' {
  declare module.exports: $Exports<'boldr-utils/dist/gql/jsonResult'>;
}
declare module 'boldr-utils/dist/index.js' {
  declare module.exports: $Exports<'boldr-utils/dist/index'>;
}
declare module 'boldr-utils/dist/logger.js' {
  declare module.exports: $Exports<'boldr-utils/dist/logger'>;
}
declare module 'boldr-utils/dist/logic/ifElse.js' {
  declare module.exports: $Exports<'boldr-utils/dist/logic/ifElse'>;
}
declare module 'boldr-utils/dist/logic/isPromise.js' {
  declare module.exports: $Exports<'boldr-utils/dist/logic/isPromise'>;
}
declare module 'boldr-utils/dist/logic/requiredParam.js' {
  declare module.exports: $Exports<'boldr-utils/dist/logic/requiredParam'>;
}
declare module 'boldr-utils/dist/logic/sort.js' {
  declare module.exports: $Exports<'boldr-utils/dist/logic/sort'>;
}
declare module 'boldr-utils/dist/logic/typeOf.js' {
  declare module.exports: $Exports<'boldr-utils/dist/logic/typeOf'>;
}
declare module 'boldr-utils/dist/logic/uniq.js' {
  declare module.exports: $Exports<'boldr-utils/dist/logic/uniq'>;
}
declare module 'boldr-utils/dist/logic/validateId.js' {
  declare module.exports: $Exports<'boldr-utils/dist/logic/validateId'>;
}
declare module 'boldr-utils/dist/node/appRoot.js' {
  declare module.exports: $Exports<'boldr-utils/dist/node/appRoot'>;
}
declare module 'boldr-utils/dist/node/clearConsole.js' {
  declare module.exports: $Exports<'boldr-utils/dist/node/clearConsole'>;
}
declare module 'boldr-utils/dist/node/ifIsFile.js' {
  declare module.exports: $Exports<'boldr-utils/dist/node/ifIsFile'>;
}
declare module 'boldr-utils/dist/node/logDeep.js' {
  declare module.exports: $Exports<'boldr-utils/dist/node/logDeep'>;
}
declare module 'boldr-utils/dist/objects/filterEmpty.js' {
  declare module.exports: $Exports<'boldr-utils/dist/objects/filterEmpty'>;
}
declare module 'boldr-utils/dist/objects/filterWithRules.js' {
  declare module.exports: $Exports<'boldr-utils/dist/objects/filterWithRules'>;
}
declare module 'boldr-utils/dist/objects/getField.js' {
  declare module.exports: $Exports<'boldr-utils/dist/objects/getField'>;
}
declare module 'boldr-utils/dist/objects/getIn.js' {
  declare module.exports: $Exports<'boldr-utils/dist/objects/getIn'>;
}
declare module 'boldr-utils/dist/objects/mergeDeep.js' {
  declare module.exports: $Exports<'boldr-utils/dist/objects/mergeDeep'>;
}
declare module 'boldr-utils/dist/objects/removeByKey.js' {
  declare module.exports: $Exports<'boldr-utils/dist/objects/removeByKey'>;
}
declare module 'boldr-utils/dist/objects/setIn.js' {
  declare module.exports: $Exports<'boldr-utils/dist/objects/setIn'>;
}
declare module 'boldr-utils/dist/state/reduceKey.js' {
  declare module.exports: $Exports<'boldr-utils/dist/state/reduceKey'>;
}
declare module 'boldr-utils/dist/strings/toTitle.js' {
  declare module.exports: $Exports<'boldr-utils/dist/strings/toTitle'>;
}
declare module 'boldr-utils/es/arrays/addIdToArray.js' {
  declare module.exports: $Exports<'boldr-utils/es/arrays/addIdToArray'>;
}
declare module 'boldr-utils/es/arrays/flatten.js' {
  declare module.exports: $Exports<'boldr-utils/es/arrays/flatten'>;
}
declare module 'boldr-utils/es/arrays/joinAnd.js' {
  declare module.exports: $Exports<'boldr-utils/es/arrays/joinAnd'>;
}
declare module 'boldr-utils/es/arrays/merge.js' {
  declare module.exports: $Exports<'boldr-utils/es/arrays/merge'>;
}
declare module 'boldr-utils/es/arrays/removeIdFromArray.js' {
  declare module.exports: $Exports<'boldr-utils/es/arrays/removeIdFromArray'>;
}
declare module 'boldr-utils/es/arrays/removeKeyFromNestedArray.js' {
  declare module.exports: $Exports<'boldr-utils/es/arrays/removeKeyFromNestedArray'>;
}
declare module 'boldr-utils/es/arrays/removeNil.js' {
  declare module.exports: $Exports<'boldr-utils/es/arrays/removeNil'>;
}
declare module 'boldr-utils/es/arrays/stringifiedArray.js' {
  declare module.exports: $Exports<'boldr-utils/es/arrays/stringifiedArray'>;
}
declare module 'boldr-utils/es/arrays/uniqueArray.js' {
  declare module.exports: $Exports<'boldr-utils/es/arrays/uniqueArray'>;
}
declare module 'boldr-utils/es/arrays/validateArray.js' {
  declare module.exports: $Exports<'boldr-utils/es/arrays/validateArray'>;
}
declare module 'boldr-utils/es/dom/getPositionedParent.js' {
  declare module.exports: $Exports<'boldr-utils/es/dom/getPositionedParent'>;
}
declare module 'boldr-utils/es/dom/getViewportSize.js' {
  declare module.exports: $Exports<'boldr-utils/es/dom/getViewportSize'>;
}
declare module 'boldr-utils/es/dom/isBrowser.js' {
  declare module.exports: $Exports<'boldr-utils/es/dom/isBrowser'>;
}
declare module 'boldr-utils/es/gql/errors.js' {
  declare module.exports: $Exports<'boldr-utils/es/gql/errors'>;
}
declare module 'boldr-utils/es/gql/firstResult.js' {
  declare module.exports: $Exports<'boldr-utils/es/gql/firstResult'>;
}
declare module 'boldr-utils/es/gql/jsonResult.js' {
  declare module.exports: $Exports<'boldr-utils/es/gql/jsonResult'>;
}
declare module 'boldr-utils/es/index.js' {
  declare module.exports: $Exports<'boldr-utils/es/index'>;
}
declare module 'boldr-utils/es/logger.js' {
  declare module.exports: $Exports<'boldr-utils/es/logger'>;
}
declare module 'boldr-utils/es/logic/ifElse.js' {
  declare module.exports: $Exports<'boldr-utils/es/logic/ifElse'>;
}
declare module 'boldr-utils/es/logic/isPromise.js' {
  declare module.exports: $Exports<'boldr-utils/es/logic/isPromise'>;
}
declare module 'boldr-utils/es/logic/requiredParam.js' {
  declare module.exports: $Exports<'boldr-utils/es/logic/requiredParam'>;
}
declare module 'boldr-utils/es/logic/sort.js' {
  declare module.exports: $Exports<'boldr-utils/es/logic/sort'>;
}
declare module 'boldr-utils/es/logic/typeOf.js' {
  declare module.exports: $Exports<'boldr-utils/es/logic/typeOf'>;
}
declare module 'boldr-utils/es/logic/uniq.js' {
  declare module.exports: $Exports<'boldr-utils/es/logic/uniq'>;
}
declare module 'boldr-utils/es/logic/validateId.js' {
  declare module.exports: $Exports<'boldr-utils/es/logic/validateId'>;
}
declare module 'boldr-utils/es/node/appRoot.js' {
  declare module.exports: $Exports<'boldr-utils/es/node/appRoot'>;
}
declare module 'boldr-utils/es/node/clearConsole.js' {
  declare module.exports: $Exports<'boldr-utils/es/node/clearConsole'>;
}
declare module 'boldr-utils/es/node/ifIsFile.js' {
  declare module.exports: $Exports<'boldr-utils/es/node/ifIsFile'>;
}
declare module 'boldr-utils/es/node/logDeep.js' {
  declare module.exports: $Exports<'boldr-utils/es/node/logDeep'>;
}
declare module 'boldr-utils/es/objects/filterEmpty.js' {
  declare module.exports: $Exports<'boldr-utils/es/objects/filterEmpty'>;
}
declare module 'boldr-utils/es/objects/filterWithRules.js' {
  declare module.exports: $Exports<'boldr-utils/es/objects/filterWithRules'>;
}
declare module 'boldr-utils/es/objects/getField.js' {
  declare module.exports: $Exports<'boldr-utils/es/objects/getField'>;
}
declare module 'boldr-utils/es/objects/getIn.js' {
  declare module.exports: $Exports<'boldr-utils/es/objects/getIn'>;
}
declare module 'boldr-utils/es/objects/mergeDeep.js' {
  declare module.exports: $Exports<'boldr-utils/es/objects/mergeDeep'>;
}
declare module 'boldr-utils/es/objects/removeByKey.js' {
  declare module.exports: $Exports<'boldr-utils/es/objects/removeByKey'>;
}
declare module 'boldr-utils/es/objects/setIn.js' {
  declare module.exports: $Exports<'boldr-utils/es/objects/setIn'>;
}
declare module 'boldr-utils/es/state/reduceKey.js' {
  declare module.exports: $Exports<'boldr-utils/es/state/reduceKey'>;
}
declare module 'boldr-utils/es/strings/toTitle.js' {
  declare module.exports: $Exports<'boldr-utils/es/strings/toTitle'>;
}
declare module 'boldr-utils/src/arrays/addIdToArray.js' {
  declare module.exports: $Exports<'boldr-utils/src/arrays/addIdToArray'>;
}
declare module 'boldr-utils/src/arrays/flatten.js' {
  declare module.exports: $Exports<'boldr-utils/src/arrays/flatten'>;
}
declare module 'boldr-utils/src/arrays/joinAnd.js' {
  declare module.exports: $Exports<'boldr-utils/src/arrays/joinAnd'>;
}
declare module 'boldr-utils/src/arrays/merge.js' {
  declare module.exports: $Exports<'boldr-utils/src/arrays/merge'>;
}
declare module 'boldr-utils/src/arrays/removeIdFromArray.js' {
  declare module.exports: $Exports<'boldr-utils/src/arrays/removeIdFromArray'>;
}
declare module 'boldr-utils/src/arrays/removeKeyFromNestedArray.js' {
  declare module.exports: $Exports<'boldr-utils/src/arrays/removeKeyFromNestedArray'>;
}
declare module 'boldr-utils/src/arrays/removeNil.js' {
  declare module.exports: $Exports<'boldr-utils/src/arrays/removeNil'>;
}
declare module 'boldr-utils/src/arrays/stringifiedArray.js' {
  declare module.exports: $Exports<'boldr-utils/src/arrays/stringifiedArray'>;
}
declare module 'boldr-utils/src/arrays/uniqueArray.js' {
  declare module.exports: $Exports<'boldr-utils/src/arrays/uniqueArray'>;
}
declare module 'boldr-utils/src/arrays/validateArray.js' {
  declare module.exports: $Exports<'boldr-utils/src/arrays/validateArray'>;
}
declare module 'boldr-utils/src/dom/getPositionedParent.js' {
  declare module.exports: $Exports<'boldr-utils/src/dom/getPositionedParent'>;
}
declare module 'boldr-utils/src/dom/getViewportSize.js' {
  declare module.exports: $Exports<'boldr-utils/src/dom/getViewportSize'>;
}
declare module 'boldr-utils/src/dom/isBrowser.js' {
  declare module.exports: $Exports<'boldr-utils/src/dom/isBrowser'>;
}
declare module 'boldr-utils/src/gql/errors.js' {
  declare module.exports: $Exports<'boldr-utils/src/gql/errors'>;
}
declare module 'boldr-utils/src/gql/firstResult.js' {
  declare module.exports: $Exports<'boldr-utils/src/gql/firstResult'>;
}
declare module 'boldr-utils/src/gql/jsonResult.js' {
  declare module.exports: $Exports<'boldr-utils/src/gql/jsonResult'>;
}
declare module 'boldr-utils/src/index.js' {
  declare module.exports: $Exports<'boldr-utils/src/index'>;
}
declare module 'boldr-utils/src/logger.js' {
  declare module.exports: $Exports<'boldr-utils/src/logger'>;
}
declare module 'boldr-utils/src/logic/ifElse.js' {
  declare module.exports: $Exports<'boldr-utils/src/logic/ifElse'>;
}
declare module 'boldr-utils/src/logic/isPromise.js' {
  declare module.exports: $Exports<'boldr-utils/src/logic/isPromise'>;
}
declare module 'boldr-utils/src/logic/requiredParam.js' {
  declare module.exports: $Exports<'boldr-utils/src/logic/requiredParam'>;
}
declare module 'boldr-utils/src/logic/sort.js' {
  declare module.exports: $Exports<'boldr-utils/src/logic/sort'>;
}
declare module 'boldr-utils/src/logic/typeOf.js' {
  declare module.exports: $Exports<'boldr-utils/src/logic/typeOf'>;
}
declare module 'boldr-utils/src/logic/uniq.js' {
  declare module.exports: $Exports<'boldr-utils/src/logic/uniq'>;
}
declare module 'boldr-utils/src/logic/validateId.js' {
  declare module.exports: $Exports<'boldr-utils/src/logic/validateId'>;
}
declare module 'boldr-utils/src/node/appRoot.js' {
  declare module.exports: $Exports<'boldr-utils/src/node/appRoot'>;
}
declare module 'boldr-utils/src/node/clearConsole.js' {
  declare module.exports: $Exports<'boldr-utils/src/node/clearConsole'>;
}
declare module 'boldr-utils/src/node/ifIsFile.js' {
  declare module.exports: $Exports<'boldr-utils/src/node/ifIsFile'>;
}
declare module 'boldr-utils/src/node/logDeep.js' {
  declare module.exports: $Exports<'boldr-utils/src/node/logDeep'>;
}
declare module 'boldr-utils/src/objects/filterEmpty.js' {
  declare module.exports: $Exports<'boldr-utils/src/objects/filterEmpty'>;
}
declare module 'boldr-utils/src/objects/filterWithRules.js' {
  declare module.exports: $Exports<'boldr-utils/src/objects/filterWithRules'>;
}
declare module 'boldr-utils/src/objects/getField.js' {
  declare module.exports: $Exports<'boldr-utils/src/objects/getField'>;
}
declare module 'boldr-utils/src/objects/getIn.js' {
  declare module.exports: $Exports<'boldr-utils/src/objects/getIn'>;
}
declare module 'boldr-utils/src/objects/mergeDeep.js' {
  declare module.exports: $Exports<'boldr-utils/src/objects/mergeDeep'>;
}
declare module 'boldr-utils/src/objects/removeByKey.js' {
  declare module.exports: $Exports<'boldr-utils/src/objects/removeByKey'>;
}
declare module 'boldr-utils/src/objects/setIn.js' {
  declare module.exports: $Exports<'boldr-utils/src/objects/setIn'>;
}
declare module 'boldr-utils/src/state/reduceKey.js' {
  declare module.exports: $Exports<'boldr-utils/src/state/reduceKey'>;
}
declare module 'boldr-utils/src/strings/toTitle.js' {
  declare module.exports: $Exports<'boldr-utils/src/strings/toTitle'>;
}
