// flow-typed signature: 939ce22ebd93ec820f045edf2d0c2632
// flow-typed version: <<STUB>>/boldr-config_v^0.1.4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boldr-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'boldr-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boldr-config/lib/boldrConfig' {
  declare module.exports: any;
}

declare module 'boldr-config/lib/displayConfig' {
  declare module.exports: any;
}

declare module 'boldr-config/lib/util/deepExtend' {
  declare module.exports: any;
}

declare module 'boldr-config/src/boldrConfig' {
  declare module.exports: any;
}

declare module 'boldr-config/src/displayConfig' {
  declare module.exports: any;
}

declare module 'boldr-config/src/util/deepExtend' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boldr-config/index' {
  declare module.exports: $Exports<'boldr-config'>;
}
declare module 'boldr-config/index.js' {
  declare module.exports: $Exports<'boldr-config'>;
}
declare module 'boldr-config/lib/boldrConfig.js' {
  declare module.exports: $Exports<'boldr-config/lib/boldrConfig'>;
}
declare module 'boldr-config/lib/displayConfig.js' {
  declare module.exports: $Exports<'boldr-config/lib/displayConfig'>;
}
declare module 'boldr-config/lib/util/deepExtend.js' {
  declare module.exports: $Exports<'boldr-config/lib/util/deepExtend'>;
}
declare module 'boldr-config/src/boldrConfig.js' {
  declare module.exports: $Exports<'boldr-config/src/boldrConfig'>;
}
declare module 'boldr-config/src/displayConfig.js' {
  declare module.exports: $Exports<'boldr-config/src/displayConfig'>;
}
declare module 'boldr-config/src/util/deepExtend.js' {
  declare module.exports: $Exports<'boldr-config/src/util/deepExtend'>;
}
