// flow-typed signature: 07bc56d42915526b93e2d086b0d641bd
// flow-typed version: <<STUB>>/boldr-core_v0.0.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boldr-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'boldr-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boldr-core/es/config/defaultConfig' {
  declare module.exports: any;
}

declare module 'boldr-core/es/config/loadConfig' {
  declare module.exports: any;
}

declare module 'boldr-core/es/config/paths' {
  declare module.exports: any;
}

declare module 'boldr-core/es/engine' {
  declare module.exports: any;
}

declare module 'boldr-core/es/plugins/watchConfig' {
  declare module.exports: any;
}

declare module 'boldr-core/es/utils/getAssetsManifest' {
  declare module.exports: any;
}

declare module 'boldr-core/lib/config/defaultConfig' {
  declare module.exports: any;
}

declare module 'boldr-core/lib/config/loadConfig' {
  declare module.exports: any;
}

declare module 'boldr-core/lib/config/paths' {
  declare module.exports: any;
}

declare module 'boldr-core/lib/engine' {
  declare module.exports: any;
}

declare module 'boldr-core/lib/plugins/watchConfig' {
  declare module.exports: any;
}

declare module 'boldr-core/lib/utils/getAssetsManifest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boldr-core/es/config/defaultConfig.js' {
  declare module.exports: $Exports<'boldr-core/es/config/defaultConfig'>;
}
declare module 'boldr-core/es/config/loadConfig.js' {
  declare module.exports: $Exports<'boldr-core/es/config/loadConfig'>;
}
declare module 'boldr-core/es/config/paths.js' {
  declare module.exports: $Exports<'boldr-core/es/config/paths'>;
}
declare module 'boldr-core/es/engine.js' {
  declare module.exports: $Exports<'boldr-core/es/engine'>;
}
declare module 'boldr-core/es/plugins/watchConfig.js' {
  declare module.exports: $Exports<'boldr-core/es/plugins/watchConfig'>;
}
declare module 'boldr-core/es/utils/getAssetsManifest.js' {
  declare module.exports: $Exports<'boldr-core/es/utils/getAssetsManifest'>;
}
declare module 'boldr-core/lib/config/defaultConfig.js' {
  declare module.exports: $Exports<'boldr-core/lib/config/defaultConfig'>;
}
declare module 'boldr-core/lib/config/loadConfig.js' {
  declare module.exports: $Exports<'boldr-core/lib/config/loadConfig'>;
}
declare module 'boldr-core/lib/config/paths.js' {
  declare module.exports: $Exports<'boldr-core/lib/config/paths'>;
}
declare module 'boldr-core/lib/engine.js' {
  declare module.exports: $Exports<'boldr-core/lib/engine'>;
}
declare module 'boldr-core/lib/plugins/watchConfig.js' {
  declare module.exports: $Exports<'boldr-core/lib/plugins/watchConfig'>;
}
declare module 'boldr-core/lib/utils/getAssetsManifest.js' {
  declare module.exports: $Exports<'boldr-core/lib/utils/getAssetsManifest'>;
}
