// flow-typed signature: cafaba19aedb70586e06afd06d1a0fed
// flow-typed version: <<STUB>>/boldr-plugin-webpack_v^0.0.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boldr-plugin-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'boldr-plugin-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boldr-plugin-webpack/lib/createBrowserWebpack' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/lib/createNodeWebpack' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/lib/index' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/lib/plugins/buildDevDlls' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/lib/plugins/happyPackPlugin' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/lib/plugins/LoggerPlugin' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/lib/polyfills/browser' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/lib/polyfills/node' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/lib/services/boldrDev' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/lib/services/createCompiler' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/lib/services/createSingleCompiler' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/lib/services/hotClientServer' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/lib/services/hotNodeServer' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/lib/services/serverListener' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/lib/util/loadableBabel' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/lib/util/paths' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/lib/util/postcss.config' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/src/createBrowserWebpack' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/src/createNodeWebpack' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/src/index' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/src/plugins/buildDevDlls' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/src/plugins/happyPackPlugin' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/src/plugins/LoggerPlugin' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/src/polyfills/browser' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/src/polyfills/node' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/src/services/boldrDev' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/src/services/createCompiler' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/src/services/createSingleCompiler' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/src/services/hotClientServer' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/src/services/hotNodeServer' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/src/services/serverListener' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/src/util/loadableBabel' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/src/util/paths' {
  declare module.exports: any;
}

declare module 'boldr-plugin-webpack/src/util/postcss.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boldr-plugin-webpack/lib/createBrowserWebpack.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/lib/createBrowserWebpack'>;
}
declare module 'boldr-plugin-webpack/lib/createNodeWebpack.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/lib/createNodeWebpack'>;
}
declare module 'boldr-plugin-webpack/lib/index.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/lib/index'>;
}
declare module 'boldr-plugin-webpack/lib/plugins/buildDevDlls.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/lib/plugins/buildDevDlls'>;
}
declare module 'boldr-plugin-webpack/lib/plugins/happyPackPlugin.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/lib/plugins/happyPackPlugin'>;
}
declare module 'boldr-plugin-webpack/lib/plugins/LoggerPlugin.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/lib/plugins/LoggerPlugin'>;
}
declare module 'boldr-plugin-webpack/lib/polyfills/browser.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/lib/polyfills/browser'>;
}
declare module 'boldr-plugin-webpack/lib/polyfills/node.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/lib/polyfills/node'>;
}
declare module 'boldr-plugin-webpack/lib/services/boldrDev.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/lib/services/boldrDev'>;
}
declare module 'boldr-plugin-webpack/lib/services/createCompiler.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/lib/services/createCompiler'>;
}
declare module 'boldr-plugin-webpack/lib/services/createSingleCompiler.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/lib/services/createSingleCompiler'>;
}
declare module 'boldr-plugin-webpack/lib/services/hotClientServer.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/lib/services/hotClientServer'>;
}
declare module 'boldr-plugin-webpack/lib/services/hotNodeServer.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/lib/services/hotNodeServer'>;
}
declare module 'boldr-plugin-webpack/lib/services/serverListener.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/lib/services/serverListener'>;
}
declare module 'boldr-plugin-webpack/lib/util/loadableBabel.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/lib/util/loadableBabel'>;
}
declare module 'boldr-plugin-webpack/lib/util/paths.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/lib/util/paths'>;
}
declare module 'boldr-plugin-webpack/lib/util/postcss.config.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/lib/util/postcss.config'>;
}
declare module 'boldr-plugin-webpack/src/createBrowserWebpack.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/src/createBrowserWebpack'>;
}
declare module 'boldr-plugin-webpack/src/createNodeWebpack.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/src/createNodeWebpack'>;
}
declare module 'boldr-plugin-webpack/src/index.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/src/index'>;
}
declare module 'boldr-plugin-webpack/src/plugins/buildDevDlls.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/src/plugins/buildDevDlls'>;
}
declare module 'boldr-plugin-webpack/src/plugins/happyPackPlugin.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/src/plugins/happyPackPlugin'>;
}
declare module 'boldr-plugin-webpack/src/plugins/LoggerPlugin.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/src/plugins/LoggerPlugin'>;
}
declare module 'boldr-plugin-webpack/src/polyfills/browser.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/src/polyfills/browser'>;
}
declare module 'boldr-plugin-webpack/src/polyfills/node.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/src/polyfills/node'>;
}
declare module 'boldr-plugin-webpack/src/services/boldrDev.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/src/services/boldrDev'>;
}
declare module 'boldr-plugin-webpack/src/services/createCompiler.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/src/services/createCompiler'>;
}
declare module 'boldr-plugin-webpack/src/services/createSingleCompiler.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/src/services/createSingleCompiler'>;
}
declare module 'boldr-plugin-webpack/src/services/hotClientServer.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/src/services/hotClientServer'>;
}
declare module 'boldr-plugin-webpack/src/services/hotNodeServer.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/src/services/hotNodeServer'>;
}
declare module 'boldr-plugin-webpack/src/services/serverListener.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/src/services/serverListener'>;
}
declare module 'boldr-plugin-webpack/src/util/loadableBabel.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/src/util/loadableBabel'>;
}
declare module 'boldr-plugin-webpack/src/util/paths.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/src/util/paths'>;
}
declare module 'boldr-plugin-webpack/src/util/postcss.config.js' {
  declare module.exports: $Exports<'boldr-plugin-webpack/src/util/postcss.config'>;
}
