// flow-typed signature: 9f2878808af518e998f1d21d43f81613
// flow-typed version: <<STUB>>/boldr-ui_v^0.4.0-rc.9/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boldr-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'boldr-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boldr-ui/dist/boldrui.min' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Accordion/Accordion' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Accordion/AccordionItem/AccordionItem' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Accordion/AccordionItemBody/AccordionItemBody' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Accordion/AccordionItemTitle/AccordionItemTitle' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Accordion/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Anchor/Anchor' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Anchor/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Avatar/Avatar' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Avatar/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Block/Block' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Block/Block.stories' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Block/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Button/Button' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Button/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Caption/Caption' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Caption/Caption.stories' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Caption/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Card/Card' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Card/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Checkbox/Checkbox' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Checkbox/Group' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Checkbox/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Collapsible/Collapsible' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Collapsible/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/ContentPromo/ContentPromo' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/ContentPromo/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Dashboard/DashboardContent/DashboardContent' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Dashboard/DashboardContent/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Dashboard/DashboardFooter/DashboardFooter' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Dashboard/DashboardFooter/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Dashboard/DashboardMain/DashboardMain' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Dashboard/DashboardMain/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Dashboard/DashboardWrapper/DashboardWrapper' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Dashboard/DashboardWrapper/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Dashboard/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Dialog/Dialog' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Dialog/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Dimmer/Dimmer' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Dimmer/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Divider/Divider' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Divider/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Flag/Flag' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Flag/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/FontIcon/Collapser' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/FontIcon/FontIcon' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/FontIcon/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Footer/Footer' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Footer/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Form/Feedback' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Form/Fields/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Form/Fields/InputField' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Form/Fields/RadioField' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Form/Fields/SelectInput' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Form/Form' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Form/FormCard/FormCard' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Form/FormCard/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Form/FormGroup/FormGroup' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Form/FormGroup/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Form/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Form/InputWrapper' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Form/Label/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Form/Label/Label' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Form/Label/Label.stories' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Form/unknownProps' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Form/validationRules' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Headline/Headline' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Headline/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Hero/Hero' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Hero/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/HorizontalRule/HorizontalRule' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/HorizontalRule/HorizontalRule.stories' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/HorizontalRule/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Icons/BaseIcon' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Icons/Icon' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Icons/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Image/Image' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Image/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Input/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Input/Input' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Input/Input.stories' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Layout/Col/Col' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Layout/Col/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Layout/config' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Layout/createProps' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Layout/Grid/Grid' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Layout/Grid/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Layout/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Layout/Row/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Layout/Row/Row' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Loader/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Loader/Loader' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Modal/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Modal/Modal' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Paper/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Paper/Paper' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Paragraph/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Paragraph/Paragraph' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Paragraph/Paragraph.stories' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Photo/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Photo/Photo' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Photo/Photo.stories' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Select/components/Option' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Select/components/Search' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Select/components/Tag' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Select/constants' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Select/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Select/Popup' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Select/Select' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Select/triggers/Index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Select/triggers/InputTrigger' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Select/triggers/SelectTrigger' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Select/triggers/SimpleTrigger' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Select/triggers/TagsTrigger' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Sidebar/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Sidebar/Sidebar' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Sidebar/SidebarHeader' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Sidebar/SidebarNav' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Sidebar/SidebarNavItem' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Sidebar/SidebarUtils' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Sidebar/SidebarWrapper' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Social/Facebook' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Social/Github' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Social/Google' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Social/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Social/LinkedIn' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Social/Social' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Social/Twitter' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Toggler/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Toggler/Toggler' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Toggler/Toggler.stories' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Topbar/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Topbar/Topbar' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Topbar/TopbarLink' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Topbar/TopbarPlainLink' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Topbar/TopbarSearch' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Tree/components/Checkbox' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Tree/components/Loading' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Tree/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/Tree/Tree' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/View/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/components/View/View' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/index.es' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/theme/index' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/theme/styleClasses' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/theme/theme' {
  declare module.exports: any;
}

declare module 'boldr-ui/lib/types/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boldr-ui/dist/boldrui.min.js' {
  declare module.exports: $Exports<'boldr-ui/dist/boldrui.min'>;
}
declare module 'boldr-ui/lib/components/Accordion/Accordion.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Accordion/Accordion'>;
}
declare module 'boldr-ui/lib/components/Accordion/AccordionItem/AccordionItem.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Accordion/AccordionItem/AccordionItem'>;
}
declare module 'boldr-ui/lib/components/Accordion/AccordionItemBody/AccordionItemBody.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Accordion/AccordionItemBody/AccordionItemBody'>;
}
declare module 'boldr-ui/lib/components/Accordion/AccordionItemTitle/AccordionItemTitle.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Accordion/AccordionItemTitle/AccordionItemTitle'>;
}
declare module 'boldr-ui/lib/components/Accordion/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Accordion/index'>;
}
declare module 'boldr-ui/lib/components/Anchor/Anchor.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Anchor/Anchor'>;
}
declare module 'boldr-ui/lib/components/Anchor/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Anchor/index'>;
}
declare module 'boldr-ui/lib/components/Avatar/Avatar.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Avatar/Avatar'>;
}
declare module 'boldr-ui/lib/components/Avatar/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Avatar/index'>;
}
declare module 'boldr-ui/lib/components/Block/Block.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Block/Block'>;
}
declare module 'boldr-ui/lib/components/Block/Block.stories.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Block/Block.stories'>;
}
declare module 'boldr-ui/lib/components/Block/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Block/index'>;
}
declare module 'boldr-ui/lib/components/Button/Button.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Button/Button'>;
}
declare module 'boldr-ui/lib/components/Button/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Button/index'>;
}
declare module 'boldr-ui/lib/components/Caption/Caption.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Caption/Caption'>;
}
declare module 'boldr-ui/lib/components/Caption/Caption.stories.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Caption/Caption.stories'>;
}
declare module 'boldr-ui/lib/components/Caption/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Caption/index'>;
}
declare module 'boldr-ui/lib/components/Card/Card.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Card/Card'>;
}
declare module 'boldr-ui/lib/components/Card/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Card/index'>;
}
declare module 'boldr-ui/lib/components/Checkbox/Checkbox.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Checkbox/Checkbox'>;
}
declare module 'boldr-ui/lib/components/Checkbox/Group.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Checkbox/Group'>;
}
declare module 'boldr-ui/lib/components/Checkbox/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Checkbox/index'>;
}
declare module 'boldr-ui/lib/components/Collapsible/Collapsible.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Collapsible/Collapsible'>;
}
declare module 'boldr-ui/lib/components/Collapsible/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Collapsible/index'>;
}
declare module 'boldr-ui/lib/components/ContentPromo/ContentPromo.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/ContentPromo/ContentPromo'>;
}
declare module 'boldr-ui/lib/components/ContentPromo/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/ContentPromo/index'>;
}
declare module 'boldr-ui/lib/components/Dashboard/DashboardContent/DashboardContent.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Dashboard/DashboardContent/DashboardContent'>;
}
declare module 'boldr-ui/lib/components/Dashboard/DashboardContent/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Dashboard/DashboardContent/index'>;
}
declare module 'boldr-ui/lib/components/Dashboard/DashboardFooter/DashboardFooter.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Dashboard/DashboardFooter/DashboardFooter'>;
}
declare module 'boldr-ui/lib/components/Dashboard/DashboardFooter/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Dashboard/DashboardFooter/index'>;
}
declare module 'boldr-ui/lib/components/Dashboard/DashboardMain/DashboardMain.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Dashboard/DashboardMain/DashboardMain'>;
}
declare module 'boldr-ui/lib/components/Dashboard/DashboardMain/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Dashboard/DashboardMain/index'>;
}
declare module 'boldr-ui/lib/components/Dashboard/DashboardWrapper/DashboardWrapper.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Dashboard/DashboardWrapper/DashboardWrapper'>;
}
declare module 'boldr-ui/lib/components/Dashboard/DashboardWrapper/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Dashboard/DashboardWrapper/index'>;
}
declare module 'boldr-ui/lib/components/Dashboard/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Dashboard/index'>;
}
declare module 'boldr-ui/lib/components/Dialog/Dialog.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Dialog/Dialog'>;
}
declare module 'boldr-ui/lib/components/Dialog/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Dialog/index'>;
}
declare module 'boldr-ui/lib/components/Dimmer/Dimmer.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Dimmer/Dimmer'>;
}
declare module 'boldr-ui/lib/components/Dimmer/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Dimmer/index'>;
}
declare module 'boldr-ui/lib/components/Divider/Divider.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Divider/Divider'>;
}
declare module 'boldr-ui/lib/components/Divider/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Divider/index'>;
}
declare module 'boldr-ui/lib/components/Flag/Flag.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Flag/Flag'>;
}
declare module 'boldr-ui/lib/components/Flag/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Flag/index'>;
}
declare module 'boldr-ui/lib/components/FontIcon/Collapser.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/FontIcon/Collapser'>;
}
declare module 'boldr-ui/lib/components/FontIcon/FontIcon.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/FontIcon/FontIcon'>;
}
declare module 'boldr-ui/lib/components/FontIcon/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/FontIcon/index'>;
}
declare module 'boldr-ui/lib/components/Footer/Footer.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Footer/Footer'>;
}
declare module 'boldr-ui/lib/components/Footer/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Footer/index'>;
}
declare module 'boldr-ui/lib/components/Form/Feedback.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Form/Feedback'>;
}
declare module 'boldr-ui/lib/components/Form/Fields/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Form/Fields/index'>;
}
declare module 'boldr-ui/lib/components/Form/Fields/InputField.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Form/Fields/InputField'>;
}
declare module 'boldr-ui/lib/components/Form/Fields/RadioField.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Form/Fields/RadioField'>;
}
declare module 'boldr-ui/lib/components/Form/Fields/SelectInput.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Form/Fields/SelectInput'>;
}
declare module 'boldr-ui/lib/components/Form/Form.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Form/Form'>;
}
declare module 'boldr-ui/lib/components/Form/FormCard/FormCard.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Form/FormCard/FormCard'>;
}
declare module 'boldr-ui/lib/components/Form/FormCard/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Form/FormCard/index'>;
}
declare module 'boldr-ui/lib/components/Form/FormGroup/FormGroup.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Form/FormGroup/FormGroup'>;
}
declare module 'boldr-ui/lib/components/Form/FormGroup/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Form/FormGroup/index'>;
}
declare module 'boldr-ui/lib/components/Form/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Form/index'>;
}
declare module 'boldr-ui/lib/components/Form/InputWrapper.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Form/InputWrapper'>;
}
declare module 'boldr-ui/lib/components/Form/Label/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Form/Label/index'>;
}
declare module 'boldr-ui/lib/components/Form/Label/Label.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Form/Label/Label'>;
}
declare module 'boldr-ui/lib/components/Form/Label/Label.stories.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Form/Label/Label.stories'>;
}
declare module 'boldr-ui/lib/components/Form/unknownProps.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Form/unknownProps'>;
}
declare module 'boldr-ui/lib/components/Form/validationRules.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Form/validationRules'>;
}
declare module 'boldr-ui/lib/components/Headline/Headline.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Headline/Headline'>;
}
declare module 'boldr-ui/lib/components/Headline/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Headline/index'>;
}
declare module 'boldr-ui/lib/components/Hero/Hero.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Hero/Hero'>;
}
declare module 'boldr-ui/lib/components/Hero/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Hero/index'>;
}
declare module 'boldr-ui/lib/components/HorizontalRule/HorizontalRule.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/HorizontalRule/HorizontalRule'>;
}
declare module 'boldr-ui/lib/components/HorizontalRule/HorizontalRule.stories.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/HorizontalRule/HorizontalRule.stories'>;
}
declare module 'boldr-ui/lib/components/HorizontalRule/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/HorizontalRule/index'>;
}
declare module 'boldr-ui/lib/components/Icons/BaseIcon.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Icons/BaseIcon'>;
}
declare module 'boldr-ui/lib/components/Icons/Icon.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Icons/Icon'>;
}
declare module 'boldr-ui/lib/components/Icons/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Icons/index'>;
}
declare module 'boldr-ui/lib/components/Image/Image.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Image/Image'>;
}
declare module 'boldr-ui/lib/components/Image/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Image/index'>;
}
declare module 'boldr-ui/lib/components/Input/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Input/index'>;
}
declare module 'boldr-ui/lib/components/Input/Input.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Input/Input'>;
}
declare module 'boldr-ui/lib/components/Input/Input.stories.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Input/Input.stories'>;
}
declare module 'boldr-ui/lib/components/Layout/Col/Col.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Layout/Col/Col'>;
}
declare module 'boldr-ui/lib/components/Layout/Col/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Layout/Col/index'>;
}
declare module 'boldr-ui/lib/components/Layout/config.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Layout/config'>;
}
declare module 'boldr-ui/lib/components/Layout/createProps.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Layout/createProps'>;
}
declare module 'boldr-ui/lib/components/Layout/Grid/Grid.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Layout/Grid/Grid'>;
}
declare module 'boldr-ui/lib/components/Layout/Grid/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Layout/Grid/index'>;
}
declare module 'boldr-ui/lib/components/Layout/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Layout/index'>;
}
declare module 'boldr-ui/lib/components/Layout/Row/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Layout/Row/index'>;
}
declare module 'boldr-ui/lib/components/Layout/Row/Row.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Layout/Row/Row'>;
}
declare module 'boldr-ui/lib/components/Loader/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Loader/index'>;
}
declare module 'boldr-ui/lib/components/Loader/Loader.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Loader/Loader'>;
}
declare module 'boldr-ui/lib/components/Modal/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Modal/index'>;
}
declare module 'boldr-ui/lib/components/Modal/Modal.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Modal/Modal'>;
}
declare module 'boldr-ui/lib/components/Paper/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Paper/index'>;
}
declare module 'boldr-ui/lib/components/Paper/Paper.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Paper/Paper'>;
}
declare module 'boldr-ui/lib/components/Paragraph/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Paragraph/index'>;
}
declare module 'boldr-ui/lib/components/Paragraph/Paragraph.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Paragraph/Paragraph'>;
}
declare module 'boldr-ui/lib/components/Paragraph/Paragraph.stories.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Paragraph/Paragraph.stories'>;
}
declare module 'boldr-ui/lib/components/Photo/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Photo/index'>;
}
declare module 'boldr-ui/lib/components/Photo/Photo.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Photo/Photo'>;
}
declare module 'boldr-ui/lib/components/Photo/Photo.stories.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Photo/Photo.stories'>;
}
declare module 'boldr-ui/lib/components/Select/components/Option.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Select/components/Option'>;
}
declare module 'boldr-ui/lib/components/Select/components/Search.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Select/components/Search'>;
}
declare module 'boldr-ui/lib/components/Select/components/Tag.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Select/components/Tag'>;
}
declare module 'boldr-ui/lib/components/Select/constants.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Select/constants'>;
}
declare module 'boldr-ui/lib/components/Select/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Select/index'>;
}
declare module 'boldr-ui/lib/components/Select/Popup.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Select/Popup'>;
}
declare module 'boldr-ui/lib/components/Select/Select.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Select/Select'>;
}
declare module 'boldr-ui/lib/components/Select/triggers/Index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Select/triggers/Index'>;
}
declare module 'boldr-ui/lib/components/Select/triggers/InputTrigger.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Select/triggers/InputTrigger'>;
}
declare module 'boldr-ui/lib/components/Select/triggers/SelectTrigger.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Select/triggers/SelectTrigger'>;
}
declare module 'boldr-ui/lib/components/Select/triggers/SimpleTrigger.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Select/triggers/SimpleTrigger'>;
}
declare module 'boldr-ui/lib/components/Select/triggers/TagsTrigger.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Select/triggers/TagsTrigger'>;
}
declare module 'boldr-ui/lib/components/Sidebar/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Sidebar/index'>;
}
declare module 'boldr-ui/lib/components/Sidebar/Sidebar.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Sidebar/Sidebar'>;
}
declare module 'boldr-ui/lib/components/Sidebar/SidebarHeader.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Sidebar/SidebarHeader'>;
}
declare module 'boldr-ui/lib/components/Sidebar/SidebarNav.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Sidebar/SidebarNav'>;
}
declare module 'boldr-ui/lib/components/Sidebar/SidebarNavItem.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Sidebar/SidebarNavItem'>;
}
declare module 'boldr-ui/lib/components/Sidebar/SidebarUtils.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Sidebar/SidebarUtils'>;
}
declare module 'boldr-ui/lib/components/Sidebar/SidebarWrapper.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Sidebar/SidebarWrapper'>;
}
declare module 'boldr-ui/lib/components/Social/Facebook.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Social/Facebook'>;
}
declare module 'boldr-ui/lib/components/Social/Github.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Social/Github'>;
}
declare module 'boldr-ui/lib/components/Social/Google.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Social/Google'>;
}
declare module 'boldr-ui/lib/components/Social/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Social/index'>;
}
declare module 'boldr-ui/lib/components/Social/LinkedIn.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Social/LinkedIn'>;
}
declare module 'boldr-ui/lib/components/Social/Social.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Social/Social'>;
}
declare module 'boldr-ui/lib/components/Social/Twitter.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Social/Twitter'>;
}
declare module 'boldr-ui/lib/components/Toggler/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Toggler/index'>;
}
declare module 'boldr-ui/lib/components/Toggler/Toggler.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Toggler/Toggler'>;
}
declare module 'boldr-ui/lib/components/Toggler/Toggler.stories.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Toggler/Toggler.stories'>;
}
declare module 'boldr-ui/lib/components/Topbar/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Topbar/index'>;
}
declare module 'boldr-ui/lib/components/Topbar/Topbar.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Topbar/Topbar'>;
}
declare module 'boldr-ui/lib/components/Topbar/TopbarLink.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Topbar/TopbarLink'>;
}
declare module 'boldr-ui/lib/components/Topbar/TopbarPlainLink.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Topbar/TopbarPlainLink'>;
}
declare module 'boldr-ui/lib/components/Topbar/TopbarSearch.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Topbar/TopbarSearch'>;
}
declare module 'boldr-ui/lib/components/Tree/components/Checkbox.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Tree/components/Checkbox'>;
}
declare module 'boldr-ui/lib/components/Tree/components/Loading.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Tree/components/Loading'>;
}
declare module 'boldr-ui/lib/components/Tree/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Tree/index'>;
}
declare module 'boldr-ui/lib/components/Tree/Tree.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/Tree/Tree'>;
}
declare module 'boldr-ui/lib/components/View/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/View/index'>;
}
declare module 'boldr-ui/lib/components/View/View.js' {
  declare module.exports: $Exports<'boldr-ui/lib/components/View/View'>;
}
declare module 'boldr-ui/lib/index.es.js' {
  declare module.exports: $Exports<'boldr-ui/lib/index.es'>;
}
declare module 'boldr-ui/lib/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/index'>;
}
declare module 'boldr-ui/lib/theme/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/theme/index'>;
}
declare module 'boldr-ui/lib/theme/styleClasses.js' {
  declare module.exports: $Exports<'boldr-ui/lib/theme/styleClasses'>;
}
declare module 'boldr-ui/lib/theme/theme.js' {
  declare module.exports: $Exports<'boldr-ui/lib/theme/theme'>;
}
declare module 'boldr-ui/lib/types/index.js' {
  declare module.exports: $Exports<'boldr-ui/lib/types/index'>;
}
