// flow-typed signature: 1501bc52f758ce674671aa6aa331d315
// flow-typed version: <<STUB>>/boldr-orm_v0.1.7/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boldr-orm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'boldr-orm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boldr-orm/lib/BoldrModel' {
  declare module.exports: any;
}

declare module 'boldr-orm/lib/BoldrQueryBuilder' {
  declare module.exports: any;
}

declare module 'boldr-orm/lib/index' {
  declare module.exports: any;
}

declare module 'boldr-orm/lib/InputError' {
  declare module.exports: any;
}

declare module 'boldr-orm/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boldr-orm/lib/BoldrModel.js' {
  declare module.exports: $Exports<'boldr-orm/lib/BoldrModel'>;
}
declare module 'boldr-orm/lib/BoldrQueryBuilder.js' {
  declare module.exports: $Exports<'boldr-orm/lib/BoldrQueryBuilder'>;
}
declare module 'boldr-orm/lib/index.js' {
  declare module.exports: $Exports<'boldr-orm/lib/index'>;
}
declare module 'boldr-orm/lib/InputError.js' {
  declare module.exports: $Exports<'boldr-orm/lib/InputError'>;
}
declare module 'boldr-orm/lib/utils.js' {
  declare module.exports: $Exports<'boldr-orm/lib/utils'>;
}
