// flow-typed signature: 3571b49235ed5f61008d5f00e8d01105
// flow-typed version: <<STUB>>/cors_v^2.8.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cors/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cors/lib/index.js' {
  declare module.exports: $Exports<'cors/lib/index'>;
}
