// flow-typed signature: 6baf66c9698b26fc52a272cce200c386
// flow-typed version: <<STUB>>/cz-conventional-changelog-emoji_v^0.1.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cz-conventional-changelog-emoji'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cz-conventional-changelog-emoji' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cz-conventional-changelog-emoji/engine' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cz-conventional-changelog-emoji/engine.js' {
  declare module.exports: $Exports<'cz-conventional-changelog-emoji/engine'>;
}
declare module 'cz-conventional-changelog-emoji/index' {
  declare module.exports: $Exports<'cz-conventional-changelog-emoji'>;
}
declare module 'cz-conventional-changelog-emoji/index.js' {
  declare module.exports: $Exports<'cz-conventional-changelog-emoji'>;
}
