// flow-typed signature: 2f9bdbb85f848f94033889783ef75c78
// flow-typed version: <<STUB>>/cz-emoji_v^0.2.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cz-emoji'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cz-emoji' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'cz-emoji/index' {
  declare module.exports: $Exports<'cz-emoji'>;
}
declare module 'cz-emoji/index.js' {
  declare module.exports: $Exports<'cz-emoji'>;
}
