// flow-typed signature: 8439c10af50c5960d2ec2f2eb9f2296e
// flow-typed version: <<STUB>>/draft-js-import-html_v^0.3.1/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-import-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-import-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-import-html/flow-typed/globals' {
  declare module.exports: any;
}

declare module 'draft-js-import-html/lib/main' {
  declare module.exports: any;
}

declare module 'draft-js-import-html/lib/parseHTML' {
  declare module.exports: any;
}

declare module 'draft-js-import-html/lib/stateFromHTML' {
  declare module.exports: any;
}

declare module 'draft-js-import-html/test/init' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-import-html/flow-typed/globals.js' {
  declare module.exports: $Exports<'draft-js-import-html/flow-typed/globals'>;
}
declare module 'draft-js-import-html/lib/main.js' {
  declare module.exports: $Exports<'draft-js-import-html/lib/main'>;
}
declare module 'draft-js-import-html/lib/parseHTML.js' {
  declare module.exports: $Exports<'draft-js-import-html/lib/parseHTML'>;
}
declare module 'draft-js-import-html/lib/stateFromHTML.js' {
  declare module.exports: $Exports<'draft-js-import-html/lib/stateFromHTML'>;
}
declare module 'draft-js-import-html/test/init.js' {
  declare module.exports: $Exports<'draft-js-import-html/test/init'>;
}
