// flow-typed signature: b039df12d48b231c0937289f284a274e
// flow-typed version: <<STUB>>/draft-js-import-html_v^0.3.2/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-import-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-import-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-import-html/lib/main' {
  declare module.exports: any;
}

declare module 'draft-js-import-html/lib/parseHTML' {
  declare module.exports: any;
}

declare module 'draft-js-import-html/lib/stateFromHTML' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-import-html/lib/main.js' {
  declare module.exports: $Exports<'draft-js-import-html/lib/main'>;
}
declare module 'draft-js-import-html/lib/parseHTML.js' {
  declare module.exports: $Exports<'draft-js-import-html/lib/parseHTML'>;
}
declare module 'draft-js-import-html/lib/stateFromHTML.js' {
  declare module.exports: $Exports<'draft-js-import-html/lib/stateFromHTML'>;
}
