// flow-typed signature: af49ce692e6706b35203fa7bcf183653
// flow-typed version: <<STUB>>/eslint-config-boldr_v^0.13.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-boldr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-boldr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-boldr/flowtype' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/import' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/jsx-a11y' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/promise' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/react' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/babel/babel' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/base/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/base/errors' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/base/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/base/node' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/base/strict' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/base/stylistic' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/base/variables' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/flowtype/flowtype' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/import/helpful-warnings' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/import/module-systems' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/import/static-analysis' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/import/style-guide' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/jsx-a11y/jsx-a11y' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/prettier/prettier' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/promise/promise' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/react/jsx' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/react/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-boldr/flowtype.js' {
  declare module.exports: $Exports<'eslint-config-boldr/flowtype'>;
}
declare module 'eslint-config-boldr/import.js' {
  declare module.exports: $Exports<'eslint-config-boldr/import'>;
}
declare module 'eslint-config-boldr/index' {
  declare module.exports: $Exports<'eslint-config-boldr'>;
}
declare module 'eslint-config-boldr/index.js' {
  declare module.exports: $Exports<'eslint-config-boldr'>;
}
declare module 'eslint-config-boldr/jsx-a11y.js' {
  declare module.exports: $Exports<'eslint-config-boldr/jsx-a11y'>;
}
declare module 'eslint-config-boldr/promise.js' {
  declare module.exports: $Exports<'eslint-config-boldr/promise'>;
}
declare module 'eslint-config-boldr/react.js' {
  declare module.exports: $Exports<'eslint-config-boldr/react'>;
}
declare module 'eslint-config-boldr/rules/babel/babel.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/babel/babel'>;
}
declare module 'eslint-config-boldr/rules/base/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/base/best-practices'>;
}
declare module 'eslint-config-boldr/rules/base/errors.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/base/errors'>;
}
declare module 'eslint-config-boldr/rules/base/es6.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/base/es6'>;
}
declare module 'eslint-config-boldr/rules/base/node.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/base/node'>;
}
declare module 'eslint-config-boldr/rules/base/strict.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/base/strict'>;
}
declare module 'eslint-config-boldr/rules/base/stylistic.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/base/stylistic'>;
}
declare module 'eslint-config-boldr/rules/base/variables.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/base/variables'>;
}
declare module 'eslint-config-boldr/rules/flowtype/flowtype.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/flowtype/flowtype'>;
}
declare module 'eslint-config-boldr/rules/import/helpful-warnings.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/import/helpful-warnings'>;
}
declare module 'eslint-config-boldr/rules/import/module-systems.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/import/module-systems'>;
}
declare module 'eslint-config-boldr/rules/import/static-analysis.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/import/static-analysis'>;
}
declare module 'eslint-config-boldr/rules/import/style-guide.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/import/style-guide'>;
}
declare module 'eslint-config-boldr/rules/jsx-a11y/jsx-a11y.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/jsx-a11y/jsx-a11y'>;
}
declare module 'eslint-config-boldr/rules/prettier/prettier.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/prettier/prettier'>;
}
declare module 'eslint-config-boldr/rules/promise/promise.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/promise/promise'>;
}
declare module 'eslint-config-boldr/rules/react/jsx.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/react/jsx'>;
}
declare module 'eslint-config-boldr/rules/react/react.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/react/react'>;
}
