// flow-typed signature: 589a2a2f263db90a62ad5bb976b8bd28
// flow-typed version: <<STUB>>/eslint-config-boldr_v^0.10.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-boldr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-boldr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-boldr/flowtype' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/import' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/jsx-a11y' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/promise' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/react' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/node' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/possible-errors' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/stylistic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-boldr/flowtype.js' {
  declare module.exports: $Exports<'eslint-config-boldr/flowtype'>;
}
declare module 'eslint-config-boldr/import.js' {
  declare module.exports: $Exports<'eslint-config-boldr/import'>;
}
declare module 'eslint-config-boldr/index' {
  declare module.exports: $Exports<'eslint-config-boldr'>;
}
declare module 'eslint-config-boldr/index.js' {
  declare module.exports: $Exports<'eslint-config-boldr'>;
}
declare module 'eslint-config-boldr/jsx-a11y.js' {
  declare module.exports: $Exports<'eslint-config-boldr/jsx-a11y'>;
}
declare module 'eslint-config-boldr/promise.js' {
  declare module.exports: $Exports<'eslint-config-boldr/promise'>;
}
declare module 'eslint-config-boldr/react.js' {
  declare module.exports: $Exports<'eslint-config-boldr/react'>;
}
declare module 'eslint-config-boldr/rules/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/best-practices'>;
}
declare module 'eslint-config-boldr/rules/es6.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/es6'>;
}
declare module 'eslint-config-boldr/rules/node.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/node'>;
}
declare module 'eslint-config-boldr/rules/possible-errors.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/possible-errors'>;
}
declare module 'eslint-config-boldr/rules/stylistic.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/stylistic'>;
}
