// flow-typed signature: 2c037577b4470dd8e65a446f524bf594
// flow-typed version: <<STUB>>/eslint-import-resolver-babel-module_v4.0.0-beta.3/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-babel-module'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-babel-module' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-import-resolver-babel-module/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-import-resolver-babel-module/lib/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-babel-module/lib/index'>;
}
