// flow-typed signature: 16447ee6c5757b1cc95290f28ad21684
// flow-typed version: <<STUB>>/eslint-config-boldr_v1.2.5/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-boldr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-boldr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-boldr/react' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/errors' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/esnext' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/flow' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/import' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/jsx-a11y' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/node' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/style' {
  declare module.exports: any;
}

declare module 'eslint-config-boldr/rules/variables' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-boldr/index' {
  declare module.exports: $Exports<'eslint-config-boldr'>;
}
declare module 'eslint-config-boldr/index.js' {
  declare module.exports: $Exports<'eslint-config-boldr'>;
}
declare module 'eslint-config-boldr/react.js' {
  declare module.exports: $Exports<'eslint-config-boldr/react'>;
}
declare module 'eslint-config-boldr/rules/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/best-practices'>;
}
declare module 'eslint-config-boldr/rules/errors.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/errors'>;
}
declare module 'eslint-config-boldr/rules/esnext.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/esnext'>;
}
declare module 'eslint-config-boldr/rules/flow.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/flow'>;
}
declare module 'eslint-config-boldr/rules/import.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/import'>;
}
declare module 'eslint-config-boldr/rules/jsx-a11y.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/jsx-a11y'>;
}
declare module 'eslint-config-boldr/rules/node.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/node'>;
}
declare module 'eslint-config-boldr/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/react'>;
}
declare module 'eslint-config-boldr/rules/style.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/style'>;
}
declare module 'eslint-config-boldr/rules/variables.js' {
  declare module.exports: $Exports<'eslint-config-boldr/rules/variables'>;
}
