// flow-typed signature: b2a4aada78eda7a31645f1b598e52cff
// flow-typed version: <<STUB>>/fast-sass-loader_v^1.2.5/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-sass-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-sass-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-sass-loader/lib/cache' {
  declare module.exports: any;
}

declare module 'fast-sass-loader/lib/index' {
  declare module.exports: any;
}

declare module 'fast-sass-loader/lib/replace' {
  declare module.exports: any;
}

declare module 'fast-sass-loader/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-sass-loader/lib/cache.js' {
  declare module.exports: $Exports<'fast-sass-loader/lib/cache'>;
}
declare module 'fast-sass-loader/lib/index.js' {
  declare module.exports: $Exports<'fast-sass-loader/lib/index'>;
}
declare module 'fast-sass-loader/lib/replace.js' {
  declare module.exports: $Exports<'fast-sass-loader/lib/replace'>;
}
declare module 'fast-sass-loader/lib/utils.js' {
  declare module.exports: $Exports<'fast-sass-loader/lib/utils'>;
}
