// flow-typed signature: 2cac4f3be49f2e181319020c5aea1871
// flow-typed version: <<STUB>>/fast-async_v6.3.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-async/plugin' {
  declare module.exports: any;
}

declare module 'fast-async/tests/test-input' {
  declare module.exports: any;
}

declare module 'fast-async/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-async/plugin.js' {
  declare module.exports: $Exports<'fast-async/plugin'>;
}
declare module 'fast-async/tests/test-input.js' {
  declare module.exports: $Exports<'fast-async/tests/test-input'>;
}
declare module 'fast-async/tests/test.js' {
  declare module.exports: $Exports<'fast-async/tests/test'>;
}
