// flow-typed signature: 4b2fa75ad0db0c34076915f47432cee4
// flow-typed version: <<STUB>>/formidable_v^1.1.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'formidable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'formidable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'formidable/lib/file' {
  declare module.exports: any;
}

declare module 'formidable/lib/incoming_form' {
  declare module.exports: any;
}

declare module 'formidable/lib/index' {
  declare module.exports: any;
}

declare module 'formidable/lib/json_parser' {
  declare module.exports: any;
}

declare module 'formidable/lib/multipart_parser' {
  declare module.exports: any;
}

declare module 'formidable/lib/octet_parser' {
  declare module.exports: any;
}

declare module 'formidable/lib/querystring_parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'formidable/index' {
  declare module.exports: $Exports<'formidable'>;
}
declare module 'formidable/index.js' {
  declare module.exports: $Exports<'formidable'>;
}
declare module 'formidable/lib/file.js' {
  declare module.exports: $Exports<'formidable/lib/file'>;
}
declare module 'formidable/lib/incoming_form.js' {
  declare module.exports: $Exports<'formidable/lib/incoming_form'>;
}
declare module 'formidable/lib/index.js' {
  declare module.exports: $Exports<'formidable/lib/index'>;
}
declare module 'formidable/lib/json_parser.js' {
  declare module.exports: $Exports<'formidable/lib/json_parser'>;
}
declare module 'formidable/lib/multipart_parser.js' {
  declare module.exports: $Exports<'formidable/lib/multipart_parser'>;
}
declare module 'formidable/lib/octet_parser.js' {
  declare module.exports: $Exports<'formidable/lib/octet_parser'>;
}
declare module 'formidable/lib/querystring_parser.js' {
  declare module.exports: $Exports<'formidable/lib/querystring_parser'>;
}
