// flow-typed signature: a0308a62837a3b91fba1f90e86b47506
// flow-typed version: <<STUB>>/graphql-subscriptions_v0.5.4/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-subscriptions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-subscriptions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-subscriptions/dist/event-emitter-to-async-iterator' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/index' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/pubsub-engine' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/pubsub' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/subscriptions-manager' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/validation' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/with-filter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-subscriptions/dist/event-emitter-to-async-iterator.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/event-emitter-to-async-iterator'>;
}
declare module 'graphql-subscriptions/dist/index.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/index'>;
}
declare module 'graphql-subscriptions/dist/pubsub-engine.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/pubsub-engine'>;
}
declare module 'graphql-subscriptions/dist/pubsub.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/pubsub'>;
}
declare module 'graphql-subscriptions/dist/subscriptions-manager.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/subscriptions-manager'>;
}
declare module 'graphql-subscriptions/dist/validation.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/validation'>;
}
declare module 'graphql-subscriptions/dist/with-filter.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/with-filter'>;
}
