// flow-typed signature: 2981a76962d0b81e7038277b1051ea6b
// flow-typed version: <<STUB>>/griddle-react_vnext/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'griddle-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'griddle-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'griddle-react/dist/module/actions/index' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/Cell' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/CellContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/ColumnDefinition' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/Filter' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/FilterContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/FilterEnhancer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/GriddleConnect' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/index' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/Layout' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/LayoutContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/NextButton' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/NextButtonContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/NextButtonEnhancer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/NoResults' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/NoResultsContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/PageDropdown' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/PageDropdownContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/Pagination' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/PaginationContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/PreviousButton' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/PreviousButtonContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/PreviousButtonEnhancer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/Row' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/RowContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/RowDefinition' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/Settings' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/SettingsContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/SettingsToggle' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/SettingsToggleContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/SettingsWrapper' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/SettingsWrapperContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/Table' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/TableBody' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/TableBodyContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/TableContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/TableHeading' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/TableHeadingCell' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/TableHeadingCellContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/TableHeadingCellEnhancer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/TableHeadingContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/components/Test' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/constants/index' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/index' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/module' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/local/actions/index' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/local/components/index' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/local/components/NextButtonContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/local/components/PageDropdownContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/local/components/PreviousButtonContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/local/components/RowContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/local/components/TableBodyContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/local/components/TableContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/local/components/TableHeadingCellContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/local/components/TableHeadingContainer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/local/index' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/local/reducers/index' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/local/selectors/localSelectors' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/position/actions/index' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/position/components/index' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/position/components/Pagination' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/position/components/SpacerRow' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/position/components/TableBody' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/position/components/TableEnhancer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/position/constants/index' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/position/index' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/position/initial-state' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/position/reducers/index' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/position/selectors/index' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/plugins/position/utils' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/reducers/dataReducer' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/selectors/dataSelectors' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/settingsComponentObjects/ColumnChooser' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/settingsComponentObjects/index' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/settingsComponentObjects/PageSizeSettings' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/utils/columnUtils' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/utils/compositionUtils' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/utils/dataUtils' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/utils/index' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/utils/rowUtils' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/utils/sortUtils' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/module/utils/valueUtils' {
  declare module.exports: any;
}

declare module 'griddle-react/dist/umd/griddle' {
  declare module.exports: any;
}

declare module 'griddle-react/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'griddle-react/dist/module/actions/index.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/actions/index'>;
}
declare module 'griddle-react/dist/module/components/Cell.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/Cell'>;
}
declare module 'griddle-react/dist/module/components/CellContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/CellContainer'>;
}
declare module 'griddle-react/dist/module/components/ColumnDefinition.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/ColumnDefinition'>;
}
declare module 'griddle-react/dist/module/components/Filter.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/Filter'>;
}
declare module 'griddle-react/dist/module/components/FilterContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/FilterContainer'>;
}
declare module 'griddle-react/dist/module/components/FilterEnhancer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/FilterEnhancer'>;
}
declare module 'griddle-react/dist/module/components/GriddleConnect.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/GriddleConnect'>;
}
declare module 'griddle-react/dist/module/components/index.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/index'>;
}
declare module 'griddle-react/dist/module/components/Layout.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/Layout'>;
}
declare module 'griddle-react/dist/module/components/LayoutContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/LayoutContainer'>;
}
declare module 'griddle-react/dist/module/components/NextButton.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/NextButton'>;
}
declare module 'griddle-react/dist/module/components/NextButtonContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/NextButtonContainer'>;
}
declare module 'griddle-react/dist/module/components/NextButtonEnhancer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/NextButtonEnhancer'>;
}
declare module 'griddle-react/dist/module/components/NoResults.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/NoResults'>;
}
declare module 'griddle-react/dist/module/components/NoResultsContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/NoResultsContainer'>;
}
declare module 'griddle-react/dist/module/components/PageDropdown.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/PageDropdown'>;
}
declare module 'griddle-react/dist/module/components/PageDropdownContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/PageDropdownContainer'>;
}
declare module 'griddle-react/dist/module/components/Pagination.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/Pagination'>;
}
declare module 'griddle-react/dist/module/components/PaginationContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/PaginationContainer'>;
}
declare module 'griddle-react/dist/module/components/PreviousButton.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/PreviousButton'>;
}
declare module 'griddle-react/dist/module/components/PreviousButtonContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/PreviousButtonContainer'>;
}
declare module 'griddle-react/dist/module/components/PreviousButtonEnhancer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/PreviousButtonEnhancer'>;
}
declare module 'griddle-react/dist/module/components/Row.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/Row'>;
}
declare module 'griddle-react/dist/module/components/RowContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/RowContainer'>;
}
declare module 'griddle-react/dist/module/components/RowDefinition.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/RowDefinition'>;
}
declare module 'griddle-react/dist/module/components/Settings.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/Settings'>;
}
declare module 'griddle-react/dist/module/components/SettingsContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/SettingsContainer'>;
}
declare module 'griddle-react/dist/module/components/SettingsToggle.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/SettingsToggle'>;
}
declare module 'griddle-react/dist/module/components/SettingsToggleContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/SettingsToggleContainer'>;
}
declare module 'griddle-react/dist/module/components/SettingsWrapper.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/SettingsWrapper'>;
}
declare module 'griddle-react/dist/module/components/SettingsWrapperContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/SettingsWrapperContainer'>;
}
declare module 'griddle-react/dist/module/components/Table.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/Table'>;
}
declare module 'griddle-react/dist/module/components/TableBody.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/TableBody'>;
}
declare module 'griddle-react/dist/module/components/TableBodyContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/TableBodyContainer'>;
}
declare module 'griddle-react/dist/module/components/TableContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/TableContainer'>;
}
declare module 'griddle-react/dist/module/components/TableHeading.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/TableHeading'>;
}
declare module 'griddle-react/dist/module/components/TableHeadingCell.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/TableHeadingCell'>;
}
declare module 'griddle-react/dist/module/components/TableHeadingCellContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/TableHeadingCellContainer'>;
}
declare module 'griddle-react/dist/module/components/TableHeadingCellEnhancer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/TableHeadingCellEnhancer'>;
}
declare module 'griddle-react/dist/module/components/TableHeadingContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/TableHeadingContainer'>;
}
declare module 'griddle-react/dist/module/components/Test.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/components/Test'>;
}
declare module 'griddle-react/dist/module/constants/index.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/constants/index'>;
}
declare module 'griddle-react/dist/module/index.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/index'>;
}
declare module 'griddle-react/dist/module/module.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/module'>;
}
declare module 'griddle-react/dist/module/plugins/local/actions/index.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/local/actions/index'>;
}
declare module 'griddle-react/dist/module/plugins/local/components/index.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/local/components/index'>;
}
declare module 'griddle-react/dist/module/plugins/local/components/NextButtonContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/local/components/NextButtonContainer'>;
}
declare module 'griddle-react/dist/module/plugins/local/components/PageDropdownContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/local/components/PageDropdownContainer'>;
}
declare module 'griddle-react/dist/module/plugins/local/components/PreviousButtonContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/local/components/PreviousButtonContainer'>;
}
declare module 'griddle-react/dist/module/plugins/local/components/RowContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/local/components/RowContainer'>;
}
declare module 'griddle-react/dist/module/plugins/local/components/TableBodyContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/local/components/TableBodyContainer'>;
}
declare module 'griddle-react/dist/module/plugins/local/components/TableContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/local/components/TableContainer'>;
}
declare module 'griddle-react/dist/module/plugins/local/components/TableHeadingCellContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/local/components/TableHeadingCellContainer'>;
}
declare module 'griddle-react/dist/module/plugins/local/components/TableHeadingContainer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/local/components/TableHeadingContainer'>;
}
declare module 'griddle-react/dist/module/plugins/local/index.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/local/index'>;
}
declare module 'griddle-react/dist/module/plugins/local/reducers/index.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/local/reducers/index'>;
}
declare module 'griddle-react/dist/module/plugins/local/selectors/localSelectors.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/local/selectors/localSelectors'>;
}
declare module 'griddle-react/dist/module/plugins/position/actions/index.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/position/actions/index'>;
}
declare module 'griddle-react/dist/module/plugins/position/components/index.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/position/components/index'>;
}
declare module 'griddle-react/dist/module/plugins/position/components/Pagination.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/position/components/Pagination'>;
}
declare module 'griddle-react/dist/module/plugins/position/components/SpacerRow.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/position/components/SpacerRow'>;
}
declare module 'griddle-react/dist/module/plugins/position/components/TableBody.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/position/components/TableBody'>;
}
declare module 'griddle-react/dist/module/plugins/position/components/TableEnhancer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/position/components/TableEnhancer'>;
}
declare module 'griddle-react/dist/module/plugins/position/constants/index.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/position/constants/index'>;
}
declare module 'griddle-react/dist/module/plugins/position/index.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/position/index'>;
}
declare module 'griddle-react/dist/module/plugins/position/initial-state.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/position/initial-state'>;
}
declare module 'griddle-react/dist/module/plugins/position/reducers/index.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/position/reducers/index'>;
}
declare module 'griddle-react/dist/module/plugins/position/selectors/index.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/position/selectors/index'>;
}
declare module 'griddle-react/dist/module/plugins/position/utils.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/plugins/position/utils'>;
}
declare module 'griddle-react/dist/module/reducers/dataReducer.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/reducers/dataReducer'>;
}
declare module 'griddle-react/dist/module/selectors/dataSelectors.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/selectors/dataSelectors'>;
}
declare module 'griddle-react/dist/module/settingsComponentObjects/ColumnChooser.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/settingsComponentObjects/ColumnChooser'>;
}
declare module 'griddle-react/dist/module/settingsComponentObjects/index.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/settingsComponentObjects/index'>;
}
declare module 'griddle-react/dist/module/settingsComponentObjects/PageSizeSettings.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/settingsComponentObjects/PageSizeSettings'>;
}
declare module 'griddle-react/dist/module/utils/columnUtils.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/utils/columnUtils'>;
}
declare module 'griddle-react/dist/module/utils/compositionUtils.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/utils/compositionUtils'>;
}
declare module 'griddle-react/dist/module/utils/dataUtils.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/utils/dataUtils'>;
}
declare module 'griddle-react/dist/module/utils/index.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/utils/index'>;
}
declare module 'griddle-react/dist/module/utils/rowUtils.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/utils/rowUtils'>;
}
declare module 'griddle-react/dist/module/utils/sortUtils.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/utils/sortUtils'>;
}
declare module 'griddle-react/dist/module/utils/valueUtils.js' {
  declare module.exports: $Exports<'griddle-react/dist/module/utils/valueUtils'>;
}
declare module 'griddle-react/dist/umd/griddle.js' {
  declare module.exports: $Exports<'griddle-react/dist/umd/griddle'>;
}
declare module 'griddle-react/webpack.config.js' {
  declare module.exports: $Exports<'griddle-react/webpack.config'>;
}
