// flow-typed signature: 1ad503c786ba52531cece7087860d46d
// flow-typed version: <<STUB>>/ioredis_v^2.4.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ioredis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ioredis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ioredis/benchmarks/single_node' {
  declare module.exports: any;
}

declare module 'ioredis/examples/basic_operations' {
  declare module.exports: any;
}

declare module 'ioredis/lib/cluster/connection_pool' {
  declare module.exports: any;
}

declare module 'ioredis/lib/cluster/delay_queue' {
  declare module.exports: any;
}

declare module 'ioredis/lib/cluster/index' {
  declare module.exports: any;
}

declare module 'ioredis/lib/command' {
  declare module.exports: any;
}

declare module 'ioredis/lib/commander' {
  declare module.exports: any;
}

declare module 'ioredis/lib/connectors/connector' {
  declare module.exports: any;
}

declare module 'ioredis/lib/connectors/sentinel_connector' {
  declare module.exports: any;
}

declare module 'ioredis/lib/pipeline' {
  declare module.exports: any;
}

declare module 'ioredis/lib/redis' {
  declare module.exports: any;
}

declare module 'ioredis/lib/redis/event_handler' {
  declare module.exports: any;
}

declare module 'ioredis/lib/redis/parser' {
  declare module.exports: any;
}

declare module 'ioredis/lib/reply_error' {
  declare module.exports: any;
}

declare module 'ioredis/lib/scan_stream' {
  declare module.exports: any;
}

declare module 'ioredis/lib/script' {
  declare module.exports: any;
}

declare module 'ioredis/lib/subscription_set' {
  declare module.exports: any;
}

declare module 'ioredis/lib/transaction' {
  declare module.exports: any;
}

declare module 'ioredis/lib/utils/index' {
  declare module.exports: any;
}

declare module 'ioredis/test_sentinel' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/auth' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/cluster' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/connection' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/drop_buffer_support' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/exports' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/fatal_error' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/lazy_connect' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/monitor' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/pipeline' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/pub_sub' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/ready_check' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/reconnect_on_error' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/scan_stream' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/scripting' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/select' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/send_command' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/sentinel' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/show_friendly_error_stack' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/string_numbers' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/transaction' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/transformer' {
  declare module.exports: any;
}

declare module 'ioredis/test/functional/watch-exec' {
  declare module.exports: any;
}

declare module 'ioredis/test/helpers/global' {
  declare module.exports: any;
}

declare module 'ioredis/test/helpers/mock_server' {
  declare module.exports: any;
}

declare module 'ioredis/test/unit/cluster' {
  declare module.exports: any;
}

declare module 'ioredis/test/unit/command' {
  declare module.exports: any;
}

declare module 'ioredis/test/unit/commander' {
  declare module.exports: any;
}

declare module 'ioredis/test/unit/connectors/connector' {
  declare module.exports: any;
}

declare module 'ioredis/test/unit/index' {
  declare module.exports: any;
}

declare module 'ioredis/test/unit/redis' {
  declare module.exports: any;
}

declare module 'ioredis/test/unit/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ioredis/benchmarks/single_node.js' {
  declare module.exports: $Exports<'ioredis/benchmarks/single_node'>;
}
declare module 'ioredis/examples/basic_operations.js' {
  declare module.exports: $Exports<'ioredis/examples/basic_operations'>;
}
declare module 'ioredis/index' {
  declare module.exports: $Exports<'ioredis'>;
}
declare module 'ioredis/index.js' {
  declare module.exports: $Exports<'ioredis'>;
}
declare module 'ioredis/lib/cluster/connection_pool.js' {
  declare module.exports: $Exports<'ioredis/lib/cluster/connection_pool'>;
}
declare module 'ioredis/lib/cluster/delay_queue.js' {
  declare module.exports: $Exports<'ioredis/lib/cluster/delay_queue'>;
}
declare module 'ioredis/lib/cluster/index.js' {
  declare module.exports: $Exports<'ioredis/lib/cluster/index'>;
}
declare module 'ioredis/lib/command.js' {
  declare module.exports: $Exports<'ioredis/lib/command'>;
}
declare module 'ioredis/lib/commander.js' {
  declare module.exports: $Exports<'ioredis/lib/commander'>;
}
declare module 'ioredis/lib/connectors/connector.js' {
  declare module.exports: $Exports<'ioredis/lib/connectors/connector'>;
}
declare module 'ioredis/lib/connectors/sentinel_connector.js' {
  declare module.exports: $Exports<'ioredis/lib/connectors/sentinel_connector'>;
}
declare module 'ioredis/lib/pipeline.js' {
  declare module.exports: $Exports<'ioredis/lib/pipeline'>;
}
declare module 'ioredis/lib/redis.js' {
  declare module.exports: $Exports<'ioredis/lib/redis'>;
}
declare module 'ioredis/lib/redis/event_handler.js' {
  declare module.exports: $Exports<'ioredis/lib/redis/event_handler'>;
}
declare module 'ioredis/lib/redis/parser.js' {
  declare module.exports: $Exports<'ioredis/lib/redis/parser'>;
}
declare module 'ioredis/lib/reply_error.js' {
  declare module.exports: $Exports<'ioredis/lib/reply_error'>;
}
declare module 'ioredis/lib/scan_stream.js' {
  declare module.exports: $Exports<'ioredis/lib/scan_stream'>;
}
declare module 'ioredis/lib/script.js' {
  declare module.exports: $Exports<'ioredis/lib/script'>;
}
declare module 'ioredis/lib/subscription_set.js' {
  declare module.exports: $Exports<'ioredis/lib/subscription_set'>;
}
declare module 'ioredis/lib/transaction.js' {
  declare module.exports: $Exports<'ioredis/lib/transaction'>;
}
declare module 'ioredis/lib/utils/index.js' {
  declare module.exports: $Exports<'ioredis/lib/utils/index'>;
}
declare module 'ioredis/test_sentinel.js' {
  declare module.exports: $Exports<'ioredis/test_sentinel'>;
}
declare module 'ioredis/test/functional/auth.js' {
  declare module.exports: $Exports<'ioredis/test/functional/auth'>;
}
declare module 'ioredis/test/functional/cluster.js' {
  declare module.exports: $Exports<'ioredis/test/functional/cluster'>;
}
declare module 'ioredis/test/functional/connection.js' {
  declare module.exports: $Exports<'ioredis/test/functional/connection'>;
}
declare module 'ioredis/test/functional/drop_buffer_support.js' {
  declare module.exports: $Exports<'ioredis/test/functional/drop_buffer_support'>;
}
declare module 'ioredis/test/functional/exports.js' {
  declare module.exports: $Exports<'ioredis/test/functional/exports'>;
}
declare module 'ioredis/test/functional/fatal_error.js' {
  declare module.exports: $Exports<'ioredis/test/functional/fatal_error'>;
}
declare module 'ioredis/test/functional/lazy_connect.js' {
  declare module.exports: $Exports<'ioredis/test/functional/lazy_connect'>;
}
declare module 'ioredis/test/functional/monitor.js' {
  declare module.exports: $Exports<'ioredis/test/functional/monitor'>;
}
declare module 'ioredis/test/functional/pipeline.js' {
  declare module.exports: $Exports<'ioredis/test/functional/pipeline'>;
}
declare module 'ioredis/test/functional/pub_sub.js' {
  declare module.exports: $Exports<'ioredis/test/functional/pub_sub'>;
}
declare module 'ioredis/test/functional/ready_check.js' {
  declare module.exports: $Exports<'ioredis/test/functional/ready_check'>;
}
declare module 'ioredis/test/functional/reconnect_on_error.js' {
  declare module.exports: $Exports<'ioredis/test/functional/reconnect_on_error'>;
}
declare module 'ioredis/test/functional/scan_stream.js' {
  declare module.exports: $Exports<'ioredis/test/functional/scan_stream'>;
}
declare module 'ioredis/test/functional/scripting.js' {
  declare module.exports: $Exports<'ioredis/test/functional/scripting'>;
}
declare module 'ioredis/test/functional/select.js' {
  declare module.exports: $Exports<'ioredis/test/functional/select'>;
}
declare module 'ioredis/test/functional/send_command.js' {
  declare module.exports: $Exports<'ioredis/test/functional/send_command'>;
}
declare module 'ioredis/test/functional/sentinel.js' {
  declare module.exports: $Exports<'ioredis/test/functional/sentinel'>;
}
declare module 'ioredis/test/functional/show_friendly_error_stack.js' {
  declare module.exports: $Exports<'ioredis/test/functional/show_friendly_error_stack'>;
}
declare module 'ioredis/test/functional/string_numbers.js' {
  declare module.exports: $Exports<'ioredis/test/functional/string_numbers'>;
}
declare module 'ioredis/test/functional/transaction.js' {
  declare module.exports: $Exports<'ioredis/test/functional/transaction'>;
}
declare module 'ioredis/test/functional/transformer.js' {
  declare module.exports: $Exports<'ioredis/test/functional/transformer'>;
}
declare module 'ioredis/test/functional/watch-exec.js' {
  declare module.exports: $Exports<'ioredis/test/functional/watch-exec'>;
}
declare module 'ioredis/test/helpers/global.js' {
  declare module.exports: $Exports<'ioredis/test/helpers/global'>;
}
declare module 'ioredis/test/helpers/mock_server.js' {
  declare module.exports: $Exports<'ioredis/test/helpers/mock_server'>;
}
declare module 'ioredis/test/unit/cluster.js' {
  declare module.exports: $Exports<'ioredis/test/unit/cluster'>;
}
declare module 'ioredis/test/unit/command.js' {
  declare module.exports: $Exports<'ioredis/test/unit/command'>;
}
declare module 'ioredis/test/unit/commander.js' {
  declare module.exports: $Exports<'ioredis/test/unit/commander'>;
}
declare module 'ioredis/test/unit/connectors/connector.js' {
  declare module.exports: $Exports<'ioredis/test/unit/connectors/connector'>;
}
declare module 'ioredis/test/unit/index.js' {
  declare module.exports: $Exports<'ioredis/test/unit/index'>;
}
declare module 'ioredis/test/unit/redis.js' {
  declare module.exports: $Exports<'ioredis/test/unit/redis'>;
}
declare module 'ioredis/test/unit/utils.js' {
  declare module.exports: $Exports<'ioredis/test/unit/utils'>;
}
