// flow-typed signature: e12e9ab9bdcb41c9431e1beac9c95c6f
// flow-typed version: <<STUB>>/istanbul-lib-coverage_v^1.1.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'istanbul-lib-coverage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'istanbul-lib-coverage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'istanbul-lib-coverage/lib/coverage-map' {
  declare module.exports: any;
}

declare module 'istanbul-lib-coverage/lib/file' {
  declare module.exports: any;
}

// Filename aliases
declare module 'istanbul-lib-coverage/index' {
  declare module.exports: $Exports<'istanbul-lib-coverage'>;
}
declare module 'istanbul-lib-coverage/index.js' {
  declare module.exports: $Exports<'istanbul-lib-coverage'>;
}
declare module 'istanbul-lib-coverage/lib/coverage-map.js' {
  declare module.exports: $Exports<'istanbul-lib-coverage/lib/coverage-map'>;
}
declare module 'istanbul-lib-coverage/lib/file.js' {
  declare module.exports: $Exports<'istanbul-lib-coverage/lib/file'>;
}
