// flow-typed signature: f573f2208029fa5a8dbed2ff8d533363
// flow-typed version: <<STUB>>/jest-transform-graphql_v^2.1.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-transform-graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-transform-graphql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jest-transform-graphql/index' {
  declare module.exports: $Exports<'jest-transform-graphql'>;
}
declare module 'jest-transform-graphql/index.js' {
  declare module.exports: $Exports<'jest-transform-graphql'>;
}
