// flow-typed signature: 99917cd1ea2faec0705f7a312917323a
// flow-typed version: <<STUB>>/jest-enzyme_v^3.2.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-enzyme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-enzyme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-enzyme/lib/index' {
  declare module.exports: any;
}

declare module 'jest-enzyme/lib/toMatchSnapshot' {
  declare module.exports: any;
}

declare module 'jest-enzyme/src/__failing_tests__/toBeChecked.test' {
  declare module.exports: any;
}

declare module 'jest-enzyme/src/__failing_tests__/toBeDisabled.test' {
  declare module.exports: any;
}

declare module 'jest-enzyme/src/__failing_tests__/toBeEmpty.test' {
  declare module.exports: any;
}

declare module 'jest-enzyme/src/__failing_tests__/toBePresent.test' {
  declare module.exports: any;
}

declare module 'jest-enzyme/src/__failing_tests__/toContainReact.test' {
  declare module.exports: any;
}

declare module 'jest-enzyme/src/__failing_tests__/toHaveClassName.test' {
  declare module.exports: any;
}

declare module 'jest-enzyme/src/__failing_tests__/toHaveHTML.test' {
  declare module.exports: any;
}

declare module 'jest-enzyme/src/__failing_tests__/toHaveProp.test' {
  declare module.exports: any;
}

declare module 'jest-enzyme/src/__failing_tests__/toHaveRef.test' {
  declare module.exports: any;
}

declare module 'jest-enzyme/src/__failing_tests__/toHaveState.test' {
  declare module.exports: any;
}

declare module 'jest-enzyme/src/__failing_tests__/toHaveStyle.test' {
  declare module.exports: any;
}

declare module 'jest-enzyme/src/__failing_tests__/toHaveTagName.test' {
  declare module.exports: any;
}

declare module 'jest-enzyme/src/__failing_tests__/toHaveText.test' {
  declare module.exports: any;
}

declare module 'jest-enzyme/src/__failing_tests__/toHaveValue.test' {
  declare module.exports: any;
}

declare module 'jest-enzyme/src/__failing_tests__/toMatchSelector.test' {
  declare module.exports: any;
}

declare module 'jest-enzyme/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-enzyme/lib/index.js' {
  declare module.exports: $Exports<'jest-enzyme/lib/index'>;
}
declare module 'jest-enzyme/lib/toMatchSnapshot.js' {
  declare module.exports: $Exports<'jest-enzyme/lib/toMatchSnapshot'>;
}
declare module 'jest-enzyme/src/__failing_tests__/toBeChecked.test.js' {
  declare module.exports: $Exports<'jest-enzyme/src/__failing_tests__/toBeChecked.test'>;
}
declare module 'jest-enzyme/src/__failing_tests__/toBeDisabled.test.js' {
  declare module.exports: $Exports<'jest-enzyme/src/__failing_tests__/toBeDisabled.test'>;
}
declare module 'jest-enzyme/src/__failing_tests__/toBeEmpty.test.js' {
  declare module.exports: $Exports<'jest-enzyme/src/__failing_tests__/toBeEmpty.test'>;
}
declare module 'jest-enzyme/src/__failing_tests__/toBePresent.test.js' {
  declare module.exports: $Exports<'jest-enzyme/src/__failing_tests__/toBePresent.test'>;
}
declare module 'jest-enzyme/src/__failing_tests__/toContainReact.test.js' {
  declare module.exports: $Exports<'jest-enzyme/src/__failing_tests__/toContainReact.test'>;
}
declare module 'jest-enzyme/src/__failing_tests__/toHaveClassName.test.js' {
  declare module.exports: $Exports<'jest-enzyme/src/__failing_tests__/toHaveClassName.test'>;
}
declare module 'jest-enzyme/src/__failing_tests__/toHaveHTML.test.js' {
  declare module.exports: $Exports<'jest-enzyme/src/__failing_tests__/toHaveHTML.test'>;
}
declare module 'jest-enzyme/src/__failing_tests__/toHaveProp.test.js' {
  declare module.exports: $Exports<'jest-enzyme/src/__failing_tests__/toHaveProp.test'>;
}
declare module 'jest-enzyme/src/__failing_tests__/toHaveRef.test.js' {
  declare module.exports: $Exports<'jest-enzyme/src/__failing_tests__/toHaveRef.test'>;
}
declare module 'jest-enzyme/src/__failing_tests__/toHaveState.test.js' {
  declare module.exports: $Exports<'jest-enzyme/src/__failing_tests__/toHaveState.test'>;
}
declare module 'jest-enzyme/src/__failing_tests__/toHaveStyle.test.js' {
  declare module.exports: $Exports<'jest-enzyme/src/__failing_tests__/toHaveStyle.test'>;
}
declare module 'jest-enzyme/src/__failing_tests__/toHaveTagName.test.js' {
  declare module.exports: $Exports<'jest-enzyme/src/__failing_tests__/toHaveTagName.test'>;
}
declare module 'jest-enzyme/src/__failing_tests__/toHaveText.test.js' {
  declare module.exports: $Exports<'jest-enzyme/src/__failing_tests__/toHaveText.test'>;
}
declare module 'jest-enzyme/src/__failing_tests__/toHaveValue.test.js' {
  declare module.exports: $Exports<'jest-enzyme/src/__failing_tests__/toHaveValue.test'>;
}
declare module 'jest-enzyme/src/__failing_tests__/toMatchSelector.test.js' {
  declare module.exports: $Exports<'jest-enzyme/src/__failing_tests__/toMatchSelector.test'>;
}
declare module 'jest-enzyme/src/index.js' {
  declare module.exports: $Exports<'jest-enzyme/src/index'>;
}
