// flow-typed signature: f262182fffeb69c02ab1a66f91363e24
// flow-typed version: <<STUB>>/lint-staged_v^3.4.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lint-staged'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lint-staged' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lint-staged/src/findBin' {
  declare module.exports: any;
}

declare module 'lint-staged/src/generateTasks' {
  declare module.exports: any;
}

declare module 'lint-staged/src/index' {
  declare module.exports: any;
}

declare module 'lint-staged/src/runScript' {
  declare module.exports: any;
}

declare module 'lint-staged/wallaby' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lint-staged/index' {
  declare module.exports: $Exports<'lint-staged'>;
}
declare module 'lint-staged/index.js' {
  declare module.exports: $Exports<'lint-staged'>;
}
declare module 'lint-staged/src/findBin.js' {
  declare module.exports: $Exports<'lint-staged/src/findBin'>;
}
declare module 'lint-staged/src/generateTasks.js' {
  declare module.exports: $Exports<'lint-staged/src/generateTasks'>;
}
declare module 'lint-staged/src/index.js' {
  declare module.exports: $Exports<'lint-staged/src/index'>;
}
declare module 'lint-staged/src/runScript.js' {
  declare module.exports: $Exports<'lint-staged/src/runScript'>;
}
declare module 'lint-staged/wallaby.js' {
  declare module.exports: $Exports<'lint-staged/wallaby'>;
}
