// flow-typed signature: 72405be3db1bbc25ffeb53bc1c3b525d
// flow-typed version: <<STUB>>/multer-s3_v^2.4.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'multer-s3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'multer-s3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'multer-s3/test/basic' {
  declare module.exports: any;
}

declare module 'multer-s3/test/util/mock-s3' {
  declare module.exports: any;
}

// Filename aliases
declare module 'multer-s3/index' {
  declare module.exports: $Exports<'multer-s3'>;
}
declare module 'multer-s3/index.js' {
  declare module.exports: $Exports<'multer-s3'>;
}
declare module 'multer-s3/test/basic.js' {
  declare module.exports: $Exports<'multer-s3/test/basic'>;
}
declare module 'multer-s3/test/util/mock-s3.js' {
  declare module.exports: $Exports<'multer-s3/test/util/mock-s3'>;
}
