// flow-typed signature: 8774b2d9dacba0fe0bad7a2dd77d07e7
// flow-typed version: <<STUB>>/node-noop_v^1.0.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-noop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-noop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'node-noop/index' {
  declare module.exports: $Exports<'node-noop'>;
}
declare module 'node-noop/index.js' {
  declare module.exports: $Exports<'node-noop'>;
}
