// flow-typed signature: b67573671d74886720c9a874634cb8e1
// flow-typed version: <<STUB>>/null_v^1.0.1/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'null'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'null' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'null/index' {
  declare module.exports: $Exports<'null'>;
}
declare module 'null/index.js' {
  declare module.exports: $Exports<'null'>;
}
