// flow-typed signature: 865a3147eb1140a97c4504d9b5523506
// flow-typed version: <<STUB>>/objection-find_v^0.3.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'objection-find'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'objection-find' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'objection-find/lib/filters' {
  declare module.exports: any;
}

declare module 'objection-find/lib/FindQueryBuilder' {
  declare module.exports: any;
}

declare module 'objection-find/lib/PropertyRef' {
  declare module.exports: any;
}

declare module 'objection-find/lib/QueryParameter' {
  declare module.exports: any;
}

declare module 'objection-find/lib/utils' {
  declare module.exports: any;
}

declare module 'objection-find/objection-find' {
  declare module.exports: any;
}

// Filename aliases
declare module 'objection-find/lib/filters.js' {
  declare module.exports: $Exports<'objection-find/lib/filters'>;
}
declare module 'objection-find/lib/FindQueryBuilder.js' {
  declare module.exports: $Exports<'objection-find/lib/FindQueryBuilder'>;
}
declare module 'objection-find/lib/PropertyRef.js' {
  declare module.exports: $Exports<'objection-find/lib/PropertyRef'>;
}
declare module 'objection-find/lib/QueryParameter.js' {
  declare module.exports: $Exports<'objection-find/lib/QueryParameter'>;
}
declare module 'objection-find/lib/utils.js' {
  declare module.exports: $Exports<'objection-find/lib/utils'>;
}
declare module 'objection-find/objection-find.js' {
  declare module.exports: $Exports<'objection-find/objection-find'>;
}
