// flow-typed signature: debe49b6195e64e1642985dbfe52d572
// flow-typed version: <<STUB>>/objection-softdelete_v^1.0.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'objection-softdelete'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'objection-softdelete' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'objection-softdelete/index' {
  declare module.exports: $Exports<'objection-softdelete'>;
}
declare module 'objection-softdelete/index.js' {
  declare module.exports: $Exports<'objection-softdelete'>;
}
