// flow-typed signature: 564e6fbfd8ce2a99ab619e68856bdf42
// flow-typed version: <<STUB>>/objection_v^0.6.1/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'objection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'objection' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'objection/lib/model/inheritModel/index' {
  declare module.exports: any;
}

declare module 'objection/lib/model/inheritModel/inheritModelEs5' {
  declare module.exports: any;
}

declare module 'objection/lib/model/inheritModel/inheritModelEs6' {
  declare module.exports: any;
}

declare module 'objection/lib/model/Model' {
  declare module.exports: any;
}

declare module 'objection/lib/model/ModelBase' {
  declare module.exports: any;
}

declare module 'objection/lib/objection' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/decorators/queryBuilderOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/graphInserter/BelongsToOneDependency' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/graphInserter/Dependency' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/graphInserter/DependencyGraph' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/graphInserter/DependencyNode' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/graphInserter/GraphInserter' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/graphInserter/HasManyDependency' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/graphInserter/InterpolateValueDependency' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/graphInserter/ManyToManyConnection' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/graphInserter/ReplaceValueDependency' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/graphInserter/TableInsertion' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/DelegateOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/DeleteOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/EagerOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/FindOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/InsertAndFetchOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/InsertGraphAndFetchOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/InsertGraphOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/InsertOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/InstanceDeleteOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/InstanceFindOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/InstanceInsertOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/InstanceUpdateOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/JoinEagerOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/JoinRelationOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/jsonApi/postgresJsonApi' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/jsonApi/WhereJsonFieldPostgresOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/jsonApi/WhereJsonHasPostgresOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/jsonApi/WhereJsonNotObjectPostgresOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/jsonApi/WhereJsonPostgresOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/KnexOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/OnBuildOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/QueryBuilderOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/RunAfterOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/RunBeforeOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/SelectOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/UpdateAndFetchOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/UpdateOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/WhereCompositeOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/WhereInCompositeOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/WhereInCompositeSqliteOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/WhereInEagerOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/WhereRefOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/operations/WrappingQueryBuilderOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/parsers/jsonFieldExpressionParser' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/parsers/relationExpressionParser' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/QueryBuilder' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/QueryBuilderBase' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/QueryBuilderContext' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/QueryBuilderContextBase' {
  declare module.exports: any;
}

declare module 'objection/lib/queryBuilder/RelationExpression' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/belongsToOne/BelongsToOneInsertOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/belongsToOne/BelongsToOneRelateOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/belongsToOne/BelongsToOneRelation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/belongsToOne/BelongsToOneUnrelateOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/hasMany/HasManyInsertOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/hasMany/HasManyRelateOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/hasMany/HasManyRelation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/hasMany/HasManyUnrelateOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/hasOne/HasOneRelation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/manyToMany/ManyToManyDeleteOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/manyToMany/ManyToManyDeleteSqliteOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/manyToMany/ManyToManyFindOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/manyToMany/ManyToManyInsertOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/manyToMany/ManyToManyRelateOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/manyToMany/ManyToManyRelation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/manyToMany/ManyToManyUnrelateOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/manyToMany/ManyToManyUnrelateSqliteOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/manyToMany/ManyToManyUpdateOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/manyToMany/ManyToManyUpdateSqliteOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/Relation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/RelationDeleteOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/RelationFindOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/relations/RelationUpdateOperation' {
  declare module.exports: any;
}

declare module 'objection/lib/transaction' {
  declare module.exports: any;
}

declare module 'objection/lib/utils/classUtils' {
  declare module.exports: any;
}

declare module 'objection/lib/utils/dbUtils' {
  declare module.exports: any;
}

declare module 'objection/lib/utils/decorators/deprecated' {
  declare module.exports: any;
}

declare module 'objection/lib/utils/decorators/hiddenData' {
  declare module.exports: any;
}

declare module 'objection/lib/utils/decorators/memoize' {
  declare module.exports: any;
}

declare module 'objection/lib/utils/hiddenData' {
  declare module.exports: any;
}

declare module 'objection/lib/utils/normalizeIds' {
  declare module.exports: any;
}

declare module 'objection/lib/utils/promiseUtils' {
  declare module.exports: any;
}

declare module 'objection/lib/utils/splitQueryProps' {
  declare module.exports: any;
}

declare module 'objection/lib/ValidationError' {
  declare module.exports: any;
}

declare module 'objection/src/model/inheritModel/index' {
  declare module.exports: any;
}

declare module 'objection/src/model/inheritModel/inheritModelEs5' {
  declare module.exports: any;
}

declare module 'objection/src/model/inheritModel/inheritModelEs6' {
  declare module.exports: any;
}

declare module 'objection/src/model/Model' {
  declare module.exports: any;
}

declare module 'objection/src/model/ModelBase' {
  declare module.exports: any;
}

declare module 'objection/src/objection' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/decorators/queryBuilderOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/graphInserter/BelongsToOneDependency' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/graphInserter/Dependency' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/graphInserter/DependencyGraph' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/graphInserter/DependencyNode' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/graphInserter/GraphInserter' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/graphInserter/HasManyDependency' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/graphInserter/InterpolateValueDependency' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/graphInserter/ManyToManyConnection' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/graphInserter/ReplaceValueDependency' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/graphInserter/TableInsertion' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/DelegateOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/DeleteOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/EagerOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/FindOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/InsertAndFetchOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/InsertGraphAndFetchOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/InsertGraphOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/InsertOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/InstanceDeleteOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/InstanceFindOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/InstanceInsertOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/InstanceUpdateOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/JoinEagerOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/JoinRelationOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/jsonApi/postgresJsonApi' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/jsonApi/WhereJsonFieldPostgresOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/jsonApi/WhereJsonHasPostgresOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/jsonApi/WhereJsonNotObjectPostgresOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/jsonApi/WhereJsonPostgresOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/KnexOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/OnBuildOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/QueryBuilderOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/RunAfterOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/RunBeforeOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/SelectOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/UpdateAndFetchOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/UpdateOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/WhereCompositeOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/WhereInCompositeOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/WhereInCompositeSqliteOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/WhereInEagerOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/WhereRefOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/operations/WrappingQueryBuilderOperation' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/parsers/jsonFieldExpressionParser' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/parsers/relationExpressionParser' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/QueryBuilder' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/QueryBuilderBase' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/QueryBuilderContext' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/QueryBuilderContextBase' {
  declare module.exports: any;
}

declare module 'objection/src/queryBuilder/RelationExpression' {
  declare module.exports: any;
}

declare module 'objection/src/relations/belongsToOne/BelongsToOneInsertOperation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/belongsToOne/BelongsToOneRelateOperation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/belongsToOne/BelongsToOneRelation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/belongsToOne/BelongsToOneUnrelateOperation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/hasMany/HasManyInsertOperation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/hasMany/HasManyRelateOperation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/hasMany/HasManyRelation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/hasMany/HasManyUnrelateOperation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/hasOne/HasOneRelation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/manyToMany/ManyToManyDeleteOperation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/manyToMany/ManyToManyDeleteSqliteOperation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/manyToMany/ManyToManyFindOperation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/manyToMany/ManyToManyInsertOperation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/manyToMany/ManyToManyRelateOperation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/manyToMany/ManyToManyRelation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/manyToMany/ManyToManyUnrelateOperation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/manyToMany/ManyToManyUnrelateSqliteOperation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/manyToMany/ManyToManyUpdateOperation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/manyToMany/ManyToManyUpdateSqliteOperation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/Relation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/RelationDeleteOperation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/RelationFindOperation' {
  declare module.exports: any;
}

declare module 'objection/src/relations/RelationUpdateOperation' {
  declare module.exports: any;
}

declare module 'objection/src/transaction' {
  declare module.exports: any;
}

declare module 'objection/src/utils/classUtils' {
  declare module.exports: any;
}

declare module 'objection/src/utils/dbUtils' {
  declare module.exports: any;
}

declare module 'objection/src/utils/decorators/deprecated' {
  declare module.exports: any;
}

declare module 'objection/src/utils/decorators/hiddenData' {
  declare module.exports: any;
}

declare module 'objection/src/utils/decorators/memoize' {
  declare module.exports: any;
}

declare module 'objection/src/utils/hiddenData' {
  declare module.exports: any;
}

declare module 'objection/src/utils/normalizeIds' {
  declare module.exports: any;
}

declare module 'objection/src/utils/promiseUtils' {
  declare module.exports: any;
}

declare module 'objection/src/utils/splitQueryProps' {
  declare module.exports: any;
}

declare module 'objection/src/ValidationError' {
  declare module.exports: any;
}

// Filename aliases
declare module 'objection/lib/model/inheritModel/index.js' {
  declare module.exports: $Exports<'objection/lib/model/inheritModel/index'>;
}
declare module 'objection/lib/model/inheritModel/inheritModelEs5.js' {
  declare module.exports: $Exports<'objection/lib/model/inheritModel/inheritModelEs5'>;
}
declare module 'objection/lib/model/inheritModel/inheritModelEs6.js' {
  declare module.exports: $Exports<'objection/lib/model/inheritModel/inheritModelEs6'>;
}
declare module 'objection/lib/model/Model.js' {
  declare module.exports: $Exports<'objection/lib/model/Model'>;
}
declare module 'objection/lib/model/ModelBase.js' {
  declare module.exports: $Exports<'objection/lib/model/ModelBase'>;
}
declare module 'objection/lib/objection.js' {
  declare module.exports: $Exports<'objection/lib/objection'>;
}
declare module 'objection/lib/queryBuilder/decorators/queryBuilderOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/decorators/queryBuilderOperation'>;
}
declare module 'objection/lib/queryBuilder/graphInserter/BelongsToOneDependency.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/graphInserter/BelongsToOneDependency'>;
}
declare module 'objection/lib/queryBuilder/graphInserter/Dependency.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/graphInserter/Dependency'>;
}
declare module 'objection/lib/queryBuilder/graphInserter/DependencyGraph.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/graphInserter/DependencyGraph'>;
}
declare module 'objection/lib/queryBuilder/graphInserter/DependencyNode.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/graphInserter/DependencyNode'>;
}
declare module 'objection/lib/queryBuilder/graphInserter/GraphInserter.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/graphInserter/GraphInserter'>;
}
declare module 'objection/lib/queryBuilder/graphInserter/HasManyDependency.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/graphInserter/HasManyDependency'>;
}
declare module 'objection/lib/queryBuilder/graphInserter/InterpolateValueDependency.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/graphInserter/InterpolateValueDependency'>;
}
declare module 'objection/lib/queryBuilder/graphInserter/ManyToManyConnection.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/graphInserter/ManyToManyConnection'>;
}
declare module 'objection/lib/queryBuilder/graphInserter/ReplaceValueDependency.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/graphInserter/ReplaceValueDependency'>;
}
declare module 'objection/lib/queryBuilder/graphInserter/TableInsertion.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/graphInserter/TableInsertion'>;
}
declare module 'objection/lib/queryBuilder/operations/DelegateOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/DelegateOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/DeleteOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/DeleteOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/EagerOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/EagerOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/FindOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/FindOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/InsertAndFetchOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/InsertAndFetchOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/InsertGraphAndFetchOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/InsertGraphAndFetchOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/InsertGraphOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/InsertGraphOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/InsertOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/InsertOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/InstanceDeleteOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/InstanceDeleteOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/InstanceFindOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/InstanceFindOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/InstanceInsertOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/InstanceInsertOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/InstanceUpdateOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/InstanceUpdateOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/JoinEagerOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/JoinEagerOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/JoinRelationOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/JoinRelationOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/jsonApi/postgresJsonApi.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/jsonApi/postgresJsonApi'>;
}
declare module 'objection/lib/queryBuilder/operations/jsonApi/WhereJsonFieldPostgresOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/jsonApi/WhereJsonFieldPostgresOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/jsonApi/WhereJsonHasPostgresOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/jsonApi/WhereJsonHasPostgresOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/jsonApi/WhereJsonNotObjectPostgresOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/jsonApi/WhereJsonNotObjectPostgresOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/jsonApi/WhereJsonPostgresOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/jsonApi/WhereJsonPostgresOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/KnexOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/KnexOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/OnBuildOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/OnBuildOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/QueryBuilderOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/QueryBuilderOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/RunAfterOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/RunAfterOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/RunBeforeOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/RunBeforeOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/SelectOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/SelectOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/UpdateAndFetchOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/UpdateAndFetchOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/UpdateOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/UpdateOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/WhereCompositeOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/WhereCompositeOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/WhereInCompositeOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/WhereInCompositeOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/WhereInCompositeSqliteOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/WhereInCompositeSqliteOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/WhereInEagerOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/WhereInEagerOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/WhereRefOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/WhereRefOperation'>;
}
declare module 'objection/lib/queryBuilder/operations/WrappingQueryBuilderOperation.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/operations/WrappingQueryBuilderOperation'>;
}
declare module 'objection/lib/queryBuilder/parsers/jsonFieldExpressionParser.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/parsers/jsonFieldExpressionParser'>;
}
declare module 'objection/lib/queryBuilder/parsers/relationExpressionParser.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/parsers/relationExpressionParser'>;
}
declare module 'objection/lib/queryBuilder/QueryBuilder.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/QueryBuilder'>;
}
declare module 'objection/lib/queryBuilder/QueryBuilderBase.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/QueryBuilderBase'>;
}
declare module 'objection/lib/queryBuilder/QueryBuilderContext.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/QueryBuilderContext'>;
}
declare module 'objection/lib/queryBuilder/QueryBuilderContextBase.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/QueryBuilderContextBase'>;
}
declare module 'objection/lib/queryBuilder/RelationExpression.js' {
  declare module.exports: $Exports<'objection/lib/queryBuilder/RelationExpression'>;
}
declare module 'objection/lib/relations/belongsToOne/BelongsToOneInsertOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/belongsToOne/BelongsToOneInsertOperation'>;
}
declare module 'objection/lib/relations/belongsToOne/BelongsToOneRelateOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/belongsToOne/BelongsToOneRelateOperation'>;
}
declare module 'objection/lib/relations/belongsToOne/BelongsToOneRelation.js' {
  declare module.exports: $Exports<'objection/lib/relations/belongsToOne/BelongsToOneRelation'>;
}
declare module 'objection/lib/relations/belongsToOne/BelongsToOneUnrelateOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/belongsToOne/BelongsToOneUnrelateOperation'>;
}
declare module 'objection/lib/relations/hasMany/HasManyInsertOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/hasMany/HasManyInsertOperation'>;
}
declare module 'objection/lib/relations/hasMany/HasManyRelateOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/hasMany/HasManyRelateOperation'>;
}
declare module 'objection/lib/relations/hasMany/HasManyRelation.js' {
  declare module.exports: $Exports<'objection/lib/relations/hasMany/HasManyRelation'>;
}
declare module 'objection/lib/relations/hasMany/HasManyUnrelateOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/hasMany/HasManyUnrelateOperation'>;
}
declare module 'objection/lib/relations/hasOne/HasOneRelation.js' {
  declare module.exports: $Exports<'objection/lib/relations/hasOne/HasOneRelation'>;
}
declare module 'objection/lib/relations/manyToMany/ManyToManyDeleteOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/manyToMany/ManyToManyDeleteOperation'>;
}
declare module 'objection/lib/relations/manyToMany/ManyToManyDeleteSqliteOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/manyToMany/ManyToManyDeleteSqliteOperation'>;
}
declare module 'objection/lib/relations/manyToMany/ManyToManyFindOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/manyToMany/ManyToManyFindOperation'>;
}
declare module 'objection/lib/relations/manyToMany/ManyToManyInsertOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/manyToMany/ManyToManyInsertOperation'>;
}
declare module 'objection/lib/relations/manyToMany/ManyToManyRelateOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/manyToMany/ManyToManyRelateOperation'>;
}
declare module 'objection/lib/relations/manyToMany/ManyToManyRelation.js' {
  declare module.exports: $Exports<'objection/lib/relations/manyToMany/ManyToManyRelation'>;
}
declare module 'objection/lib/relations/manyToMany/ManyToManyUnrelateOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/manyToMany/ManyToManyUnrelateOperation'>;
}
declare module 'objection/lib/relations/manyToMany/ManyToManyUnrelateSqliteOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/manyToMany/ManyToManyUnrelateSqliteOperation'>;
}
declare module 'objection/lib/relations/manyToMany/ManyToManyUpdateOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/manyToMany/ManyToManyUpdateOperation'>;
}
declare module 'objection/lib/relations/manyToMany/ManyToManyUpdateSqliteOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/manyToMany/ManyToManyUpdateSqliteOperation'>;
}
declare module 'objection/lib/relations/Relation.js' {
  declare module.exports: $Exports<'objection/lib/relations/Relation'>;
}
declare module 'objection/lib/relations/RelationDeleteOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/RelationDeleteOperation'>;
}
declare module 'objection/lib/relations/RelationFindOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/RelationFindOperation'>;
}
declare module 'objection/lib/relations/RelationUpdateOperation.js' {
  declare module.exports: $Exports<'objection/lib/relations/RelationUpdateOperation'>;
}
declare module 'objection/lib/transaction.js' {
  declare module.exports: $Exports<'objection/lib/transaction'>;
}
declare module 'objection/lib/utils/classUtils.js' {
  declare module.exports: $Exports<'objection/lib/utils/classUtils'>;
}
declare module 'objection/lib/utils/dbUtils.js' {
  declare module.exports: $Exports<'objection/lib/utils/dbUtils'>;
}
declare module 'objection/lib/utils/decorators/deprecated.js' {
  declare module.exports: $Exports<'objection/lib/utils/decorators/deprecated'>;
}
declare module 'objection/lib/utils/decorators/hiddenData.js' {
  declare module.exports: $Exports<'objection/lib/utils/decorators/hiddenData'>;
}
declare module 'objection/lib/utils/decorators/memoize.js' {
  declare module.exports: $Exports<'objection/lib/utils/decorators/memoize'>;
}
declare module 'objection/lib/utils/hiddenData.js' {
  declare module.exports: $Exports<'objection/lib/utils/hiddenData'>;
}
declare module 'objection/lib/utils/normalizeIds.js' {
  declare module.exports: $Exports<'objection/lib/utils/normalizeIds'>;
}
declare module 'objection/lib/utils/promiseUtils.js' {
  declare module.exports: $Exports<'objection/lib/utils/promiseUtils'>;
}
declare module 'objection/lib/utils/splitQueryProps.js' {
  declare module.exports: $Exports<'objection/lib/utils/splitQueryProps'>;
}
declare module 'objection/lib/ValidationError.js' {
  declare module.exports: $Exports<'objection/lib/ValidationError'>;
}
declare module 'objection/src/model/inheritModel/index.js' {
  declare module.exports: $Exports<'objection/src/model/inheritModel/index'>;
}
declare module 'objection/src/model/inheritModel/inheritModelEs5.js' {
  declare module.exports: $Exports<'objection/src/model/inheritModel/inheritModelEs5'>;
}
declare module 'objection/src/model/inheritModel/inheritModelEs6.js' {
  declare module.exports: $Exports<'objection/src/model/inheritModel/inheritModelEs6'>;
}
declare module 'objection/src/model/Model.js' {
  declare module.exports: $Exports<'objection/src/model/Model'>;
}
declare module 'objection/src/model/ModelBase.js' {
  declare module.exports: $Exports<'objection/src/model/ModelBase'>;
}
declare module 'objection/src/objection.js' {
  declare module.exports: $Exports<'objection/src/objection'>;
}
declare module 'objection/src/queryBuilder/decorators/queryBuilderOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/decorators/queryBuilderOperation'>;
}
declare module 'objection/src/queryBuilder/graphInserter/BelongsToOneDependency.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/graphInserter/BelongsToOneDependency'>;
}
declare module 'objection/src/queryBuilder/graphInserter/Dependency.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/graphInserter/Dependency'>;
}
declare module 'objection/src/queryBuilder/graphInserter/DependencyGraph.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/graphInserter/DependencyGraph'>;
}
declare module 'objection/src/queryBuilder/graphInserter/DependencyNode.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/graphInserter/DependencyNode'>;
}
declare module 'objection/src/queryBuilder/graphInserter/GraphInserter.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/graphInserter/GraphInserter'>;
}
declare module 'objection/src/queryBuilder/graphInserter/HasManyDependency.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/graphInserter/HasManyDependency'>;
}
declare module 'objection/src/queryBuilder/graphInserter/InterpolateValueDependency.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/graphInserter/InterpolateValueDependency'>;
}
declare module 'objection/src/queryBuilder/graphInserter/ManyToManyConnection.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/graphInserter/ManyToManyConnection'>;
}
declare module 'objection/src/queryBuilder/graphInserter/ReplaceValueDependency.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/graphInserter/ReplaceValueDependency'>;
}
declare module 'objection/src/queryBuilder/graphInserter/TableInsertion.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/graphInserter/TableInsertion'>;
}
declare module 'objection/src/queryBuilder/operations/DelegateOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/DelegateOperation'>;
}
declare module 'objection/src/queryBuilder/operations/DeleteOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/DeleteOperation'>;
}
declare module 'objection/src/queryBuilder/operations/EagerOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/EagerOperation'>;
}
declare module 'objection/src/queryBuilder/operations/FindOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/FindOperation'>;
}
declare module 'objection/src/queryBuilder/operations/InsertAndFetchOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/InsertAndFetchOperation'>;
}
declare module 'objection/src/queryBuilder/operations/InsertGraphAndFetchOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/InsertGraphAndFetchOperation'>;
}
declare module 'objection/src/queryBuilder/operations/InsertGraphOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/InsertGraphOperation'>;
}
declare module 'objection/src/queryBuilder/operations/InsertOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/InsertOperation'>;
}
declare module 'objection/src/queryBuilder/operations/InstanceDeleteOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/InstanceDeleteOperation'>;
}
declare module 'objection/src/queryBuilder/operations/InstanceFindOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/InstanceFindOperation'>;
}
declare module 'objection/src/queryBuilder/operations/InstanceInsertOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/InstanceInsertOperation'>;
}
declare module 'objection/src/queryBuilder/operations/InstanceUpdateOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/InstanceUpdateOperation'>;
}
declare module 'objection/src/queryBuilder/operations/JoinEagerOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/JoinEagerOperation'>;
}
declare module 'objection/src/queryBuilder/operations/JoinRelationOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/JoinRelationOperation'>;
}
declare module 'objection/src/queryBuilder/operations/jsonApi/postgresJsonApi.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/jsonApi/postgresJsonApi'>;
}
declare module 'objection/src/queryBuilder/operations/jsonApi/WhereJsonFieldPostgresOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/jsonApi/WhereJsonFieldPostgresOperation'>;
}
declare module 'objection/src/queryBuilder/operations/jsonApi/WhereJsonHasPostgresOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/jsonApi/WhereJsonHasPostgresOperation'>;
}
declare module 'objection/src/queryBuilder/operations/jsonApi/WhereJsonNotObjectPostgresOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/jsonApi/WhereJsonNotObjectPostgresOperation'>;
}
declare module 'objection/src/queryBuilder/operations/jsonApi/WhereJsonPostgresOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/jsonApi/WhereJsonPostgresOperation'>;
}
declare module 'objection/src/queryBuilder/operations/KnexOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/KnexOperation'>;
}
declare module 'objection/src/queryBuilder/operations/OnBuildOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/OnBuildOperation'>;
}
declare module 'objection/src/queryBuilder/operations/QueryBuilderOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/QueryBuilderOperation'>;
}
declare module 'objection/src/queryBuilder/operations/RunAfterOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/RunAfterOperation'>;
}
declare module 'objection/src/queryBuilder/operations/RunBeforeOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/RunBeforeOperation'>;
}
declare module 'objection/src/queryBuilder/operations/SelectOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/SelectOperation'>;
}
declare module 'objection/src/queryBuilder/operations/UpdateAndFetchOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/UpdateAndFetchOperation'>;
}
declare module 'objection/src/queryBuilder/operations/UpdateOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/UpdateOperation'>;
}
declare module 'objection/src/queryBuilder/operations/WhereCompositeOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/WhereCompositeOperation'>;
}
declare module 'objection/src/queryBuilder/operations/WhereInCompositeOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/WhereInCompositeOperation'>;
}
declare module 'objection/src/queryBuilder/operations/WhereInCompositeSqliteOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/WhereInCompositeSqliteOperation'>;
}
declare module 'objection/src/queryBuilder/operations/WhereInEagerOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/WhereInEagerOperation'>;
}
declare module 'objection/src/queryBuilder/operations/WhereRefOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/WhereRefOperation'>;
}
declare module 'objection/src/queryBuilder/operations/WrappingQueryBuilderOperation.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/operations/WrappingQueryBuilderOperation'>;
}
declare module 'objection/src/queryBuilder/parsers/jsonFieldExpressionParser.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/parsers/jsonFieldExpressionParser'>;
}
declare module 'objection/src/queryBuilder/parsers/relationExpressionParser.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/parsers/relationExpressionParser'>;
}
declare module 'objection/src/queryBuilder/QueryBuilder.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/QueryBuilder'>;
}
declare module 'objection/src/queryBuilder/QueryBuilderBase.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/QueryBuilderBase'>;
}
declare module 'objection/src/queryBuilder/QueryBuilderContext.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/QueryBuilderContext'>;
}
declare module 'objection/src/queryBuilder/QueryBuilderContextBase.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/QueryBuilderContextBase'>;
}
declare module 'objection/src/queryBuilder/RelationExpression.js' {
  declare module.exports: $Exports<'objection/src/queryBuilder/RelationExpression'>;
}
declare module 'objection/src/relations/belongsToOne/BelongsToOneInsertOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/belongsToOne/BelongsToOneInsertOperation'>;
}
declare module 'objection/src/relations/belongsToOne/BelongsToOneRelateOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/belongsToOne/BelongsToOneRelateOperation'>;
}
declare module 'objection/src/relations/belongsToOne/BelongsToOneRelation.js' {
  declare module.exports: $Exports<'objection/src/relations/belongsToOne/BelongsToOneRelation'>;
}
declare module 'objection/src/relations/belongsToOne/BelongsToOneUnrelateOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/belongsToOne/BelongsToOneUnrelateOperation'>;
}
declare module 'objection/src/relations/hasMany/HasManyInsertOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/hasMany/HasManyInsertOperation'>;
}
declare module 'objection/src/relations/hasMany/HasManyRelateOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/hasMany/HasManyRelateOperation'>;
}
declare module 'objection/src/relations/hasMany/HasManyRelation.js' {
  declare module.exports: $Exports<'objection/src/relations/hasMany/HasManyRelation'>;
}
declare module 'objection/src/relations/hasMany/HasManyUnrelateOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/hasMany/HasManyUnrelateOperation'>;
}
declare module 'objection/src/relations/hasOne/HasOneRelation.js' {
  declare module.exports: $Exports<'objection/src/relations/hasOne/HasOneRelation'>;
}
declare module 'objection/src/relations/manyToMany/ManyToManyDeleteOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/manyToMany/ManyToManyDeleteOperation'>;
}
declare module 'objection/src/relations/manyToMany/ManyToManyDeleteSqliteOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/manyToMany/ManyToManyDeleteSqliteOperation'>;
}
declare module 'objection/src/relations/manyToMany/ManyToManyFindOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/manyToMany/ManyToManyFindOperation'>;
}
declare module 'objection/src/relations/manyToMany/ManyToManyInsertOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/manyToMany/ManyToManyInsertOperation'>;
}
declare module 'objection/src/relations/manyToMany/ManyToManyRelateOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/manyToMany/ManyToManyRelateOperation'>;
}
declare module 'objection/src/relations/manyToMany/ManyToManyRelation.js' {
  declare module.exports: $Exports<'objection/src/relations/manyToMany/ManyToManyRelation'>;
}
declare module 'objection/src/relations/manyToMany/ManyToManyUnrelateOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/manyToMany/ManyToManyUnrelateOperation'>;
}
declare module 'objection/src/relations/manyToMany/ManyToManyUnrelateSqliteOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/manyToMany/ManyToManyUnrelateSqliteOperation'>;
}
declare module 'objection/src/relations/manyToMany/ManyToManyUpdateOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/manyToMany/ManyToManyUpdateOperation'>;
}
declare module 'objection/src/relations/manyToMany/ManyToManyUpdateSqliteOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/manyToMany/ManyToManyUpdateSqliteOperation'>;
}
declare module 'objection/src/relations/Relation.js' {
  declare module.exports: $Exports<'objection/src/relations/Relation'>;
}
declare module 'objection/src/relations/RelationDeleteOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/RelationDeleteOperation'>;
}
declare module 'objection/src/relations/RelationFindOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/RelationFindOperation'>;
}
declare module 'objection/src/relations/RelationUpdateOperation.js' {
  declare module.exports: $Exports<'objection/src/relations/RelationUpdateOperation'>;
}
declare module 'objection/src/transaction.js' {
  declare module.exports: $Exports<'objection/src/transaction'>;
}
declare module 'objection/src/utils/classUtils.js' {
  declare module.exports: $Exports<'objection/src/utils/classUtils'>;
}
declare module 'objection/src/utils/dbUtils.js' {
  declare module.exports: $Exports<'objection/src/utils/dbUtils'>;
}
declare module 'objection/src/utils/decorators/deprecated.js' {
  declare module.exports: $Exports<'objection/src/utils/decorators/deprecated'>;
}
declare module 'objection/src/utils/decorators/hiddenData.js' {
  declare module.exports: $Exports<'objection/src/utils/decorators/hiddenData'>;
}
declare module 'objection/src/utils/decorators/memoize.js' {
  declare module.exports: $Exports<'objection/src/utils/decorators/memoize'>;
}
declare module 'objection/src/utils/hiddenData.js' {
  declare module.exports: $Exports<'objection/src/utils/hiddenData'>;
}
declare module 'objection/src/utils/normalizeIds.js' {
  declare module.exports: $Exports<'objection/src/utils/normalizeIds'>;
}
declare module 'objection/src/utils/promiseUtils.js' {
  declare module.exports: $Exports<'objection/src/utils/promiseUtils'>;
}
declare module 'objection/src/utils/splitQueryProps.js' {
  declare module.exports: $Exports<'objection/src/utils/splitQueryProps'>;
}
declare module 'objection/src/ValidationError.js' {
  declare module.exports: $Exports<'objection/src/ValidationError'>;
}
