// flow-typed signature: 1bfa54390cb4155710a05c507e0a9392
// flow-typed version: <<STUB>>/passport-jwt_v^2.1.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-jwt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-jwt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-jwt/lib/auth_header' {
  declare module.exports: any;
}

declare module 'passport-jwt/lib/extract_jwt' {
  declare module.exports: any;
}

declare module 'passport-jwt/lib/index' {
  declare module.exports: any;
}

declare module 'passport-jwt/lib/strategy' {
  declare module.exports: any;
}

declare module 'passport-jwt/lib/verify_jwt' {
  declare module.exports: any;
}

declare module 'passport-jwt/test/auth_header-test' {
  declare module.exports: any;
}

declare module 'passport-jwt/test/bootstrap' {
  declare module.exports: any;
}

declare module 'passport-jwt/test/extrators-test' {
  declare module.exports: any;
}

declare module 'passport-jwt/test/mock_request' {
  declare module.exports: any;
}

declare module 'passport-jwt/test/strategy-init-test' {
  declare module.exports: any;
}

declare module 'passport-jwt/test/strategy-requests-test' {
  declare module.exports: any;
}

declare module 'passport-jwt/test/strategy-validation-test' {
  declare module.exports: any;
}

declare module 'passport-jwt/test/strategy-verify-test' {
  declare module.exports: any;
}

declare module 'passport-jwt/test/testdata' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-jwt/lib/auth_header.js' {
  declare module.exports: $Exports<'passport-jwt/lib/auth_header'>;
}
declare module 'passport-jwt/lib/extract_jwt.js' {
  declare module.exports: $Exports<'passport-jwt/lib/extract_jwt'>;
}
declare module 'passport-jwt/lib/index.js' {
  declare module.exports: $Exports<'passport-jwt/lib/index'>;
}
declare module 'passport-jwt/lib/strategy.js' {
  declare module.exports: $Exports<'passport-jwt/lib/strategy'>;
}
declare module 'passport-jwt/lib/verify_jwt.js' {
  declare module.exports: $Exports<'passport-jwt/lib/verify_jwt'>;
}
declare module 'passport-jwt/test/auth_header-test.js' {
  declare module.exports: $Exports<'passport-jwt/test/auth_header-test'>;
}
declare module 'passport-jwt/test/bootstrap.js' {
  declare module.exports: $Exports<'passport-jwt/test/bootstrap'>;
}
declare module 'passport-jwt/test/extrators-test.js' {
  declare module.exports: $Exports<'passport-jwt/test/extrators-test'>;
}
declare module 'passport-jwt/test/mock_request.js' {
  declare module.exports: $Exports<'passport-jwt/test/mock_request'>;
}
declare module 'passport-jwt/test/strategy-init-test.js' {
  declare module.exports: $Exports<'passport-jwt/test/strategy-init-test'>;
}
declare module 'passport-jwt/test/strategy-requests-test.js' {
  declare module.exports: $Exports<'passport-jwt/test/strategy-requests-test'>;
}
declare module 'passport-jwt/test/strategy-validation-test.js' {
  declare module.exports: $Exports<'passport-jwt/test/strategy-validation-test'>;
}
declare module 'passport-jwt/test/strategy-verify-test.js' {
  declare module.exports: $Exports<'passport-jwt/test/strategy-verify-test'>;
}
declare module 'passport-jwt/test/testdata.js' {
  declare module.exports: $Exports<'passport-jwt/test/testdata'>;
}
