// flow-typed signature: aeb8784f9702d7a2c48cfe79be69ae77
// flow-typed version: <<STUB>>/progress-bar-webpack-plugin_v^1.9.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'progress-bar-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'progress-bar-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'progress-bar-webpack-plugin/index' {
  declare module.exports: $Exports<'progress-bar-webpack-plugin'>;
}
declare module 'progress-bar-webpack-plugin/index.js' {
  declare module.exports: $Exports<'progress-bar-webpack-plugin'>;
}
