// flow-typed signature: 87f98e5c2118268b34a8996b5a5af136
// flow-typed version: <<STUB>>/react-draft-wysiwyg_v^1.9.9/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-draft-wysiwyg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-draft-wysiwyg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-draft-wysiwyg/dist/react-draft-wysiwyg' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-draft-wysiwyg/dist/react-draft-wysiwyg.js' {
  declare module.exports: $Exports<'react-draft-wysiwyg/dist/react-draft-wysiwyg'>;
}
