// flow-typed signature: 094e6ed505213e776437b3da077f8785
// flow-typed version: <<STUB>>/react-addons-perf_v^15.4.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-addons-perf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-addons-perf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-addons-perf/index' {
  declare module.exports: $Exports<'react-addons-perf'>;
}
declare module 'react-addons-perf/index.js' {
  declare module.exports: $Exports<'react-addons-perf'>;
}
