// flow-typed signature: 86e444e0df03dba529925437e1f2bc31
// flow-typed version: <<STUB>>/react-dropzone_v^3.13.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dropzone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dropzone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dropzone/dist/index' {
  declare module.exports: any;
}

declare module 'react-dropzone/src/getDataTransferItems' {
  declare module.exports: any;
}

declare module 'react-dropzone/src/getDataTransferItems.spec' {
  declare module.exports: any;
}

declare module 'react-dropzone/src/index' {
  declare module.exports: any;
}

declare module 'react-dropzone/src/index.spec' {
  declare module.exports: any;
}

declare module 'react-dropzone/styleguide.config' {
  declare module.exports: any;
}

declare module 'react-dropzone/testSetup' {
  declare module.exports: any;
}

declare module 'react-dropzone/wallaby.config' {
  declare module.exports: any;
}

declare module 'react-dropzone/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dropzone/dist/index.js' {
  declare module.exports: $Exports<'react-dropzone/dist/index'>;
}
declare module 'react-dropzone/src/getDataTransferItems.js' {
  declare module.exports: $Exports<'react-dropzone/src/getDataTransferItems'>;
}
declare module 'react-dropzone/src/getDataTransferItems.spec.js' {
  declare module.exports: $Exports<'react-dropzone/src/getDataTransferItems.spec'>;
}
declare module 'react-dropzone/src/index.js' {
  declare module.exports: $Exports<'react-dropzone/src/index'>;
}
declare module 'react-dropzone/src/index.spec.js' {
  declare module.exports: $Exports<'react-dropzone/src/index.spec'>;
}
declare module 'react-dropzone/styleguide.config.js' {
  declare module.exports: $Exports<'react-dropzone/styleguide.config'>;
}
declare module 'react-dropzone/testSetup.js' {
  declare module.exports: $Exports<'react-dropzone/testSetup'>;
}
declare module 'react-dropzone/wallaby.config.js' {
  declare module.exports: $Exports<'react-dropzone/wallaby.config'>;
}
declare module 'react-dropzone/webpack.config.js' {
  declare module.exports: $Exports<'react-dropzone/webpack.config'>;
}
