// flow-typed signature: 753c6487e3f355f106b170c29f2e49b4
// flow-typed version: <<STUB>>/redux-connect_v^4.0.2/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-connect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-connect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-connect/lib/components/AsyncConnect' {
  declare module.exports: any;
}

declare module 'redux-connect/lib/containers/AsyncConnect' {
  declare module.exports: any;
}

declare module 'redux-connect/lib/containers/decorator' {
  declare module.exports: any;
}

declare module 'redux-connect/lib/helpers/state' {
  declare module.exports: any;
}

declare module 'redux-connect/lib/helpers/utils' {
  declare module.exports: any;
}

declare module 'redux-connect/lib/index' {
  declare module.exports: any;
}

declare module 'redux-connect/lib/store' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-connect/lib/components/AsyncConnect.js' {
  declare module.exports: $Exports<'redux-connect/lib/components/AsyncConnect'>;
}
declare module 'redux-connect/lib/containers/AsyncConnect.js' {
  declare module.exports: $Exports<'redux-connect/lib/containers/AsyncConnect'>;
}
declare module 'redux-connect/lib/containers/decorator.js' {
  declare module.exports: $Exports<'redux-connect/lib/containers/decorator'>;
}
declare module 'redux-connect/lib/helpers/state.js' {
  declare module.exports: $Exports<'redux-connect/lib/helpers/state'>;
}
declare module 'redux-connect/lib/helpers/utils.js' {
  declare module.exports: $Exports<'redux-connect/lib/helpers/utils'>;
}
declare module 'redux-connect/lib/index.js' {
  declare module.exports: $Exports<'redux-connect/lib/index'>;
}
declare module 'redux-connect/lib/store.js' {
  declare module.exports: $Exports<'redux-connect/lib/store'>;
}
