// flow-typed signature: c79f0c24291fb83d5ce18309a111491e
// flow-typed version: <<STUB>>/require-from-string_v^1.2.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'require-from-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'require-from-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'require-from-string/index' {
  declare module.exports: $Exports<'require-from-string'>;
}
declare module 'require-from-string/index.js' {
  declare module.exports: $Exports<'require-from-string'>;
}
