// flow-typed signature: 7bb90b5651f54498e7ee6c3969dd0b28
// flow-typed version: <<STUB>>/sassdoc_v^2.3.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sassdoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sassdoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sassdoc/dist/annotation/annotations/access' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/alias' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/author' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/content' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/deprecated' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/example' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/group' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/ignore' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/index' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/link' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/name' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/output' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/parameter' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/property' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/require' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/return' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/see' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/since' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/throw' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/todo' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/annotations/type' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/annotation/index' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/cli' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/environment' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/errors' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/exclude' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/logger' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/notifier' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/parser' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/recurse' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/sassdoc' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/sorter' {
  declare module.exports: any;
}

declare module 'sassdoc/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sassdoc/dist/annotation/annotations/access.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/access'>;
}
declare module 'sassdoc/dist/annotation/annotations/alias.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/alias'>;
}
declare module 'sassdoc/dist/annotation/annotations/author.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/author'>;
}
declare module 'sassdoc/dist/annotation/annotations/content.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/content'>;
}
declare module 'sassdoc/dist/annotation/annotations/deprecated.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/deprecated'>;
}
declare module 'sassdoc/dist/annotation/annotations/example.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/example'>;
}
declare module 'sassdoc/dist/annotation/annotations/group.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/group'>;
}
declare module 'sassdoc/dist/annotation/annotations/ignore.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/ignore'>;
}
declare module 'sassdoc/dist/annotation/annotations/index.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/index'>;
}
declare module 'sassdoc/dist/annotation/annotations/link.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/link'>;
}
declare module 'sassdoc/dist/annotation/annotations/name.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/name'>;
}
declare module 'sassdoc/dist/annotation/annotations/output.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/output'>;
}
declare module 'sassdoc/dist/annotation/annotations/parameter.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/parameter'>;
}
declare module 'sassdoc/dist/annotation/annotations/property.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/property'>;
}
declare module 'sassdoc/dist/annotation/annotations/require.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/require'>;
}
declare module 'sassdoc/dist/annotation/annotations/return.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/return'>;
}
declare module 'sassdoc/dist/annotation/annotations/see.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/see'>;
}
declare module 'sassdoc/dist/annotation/annotations/since.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/since'>;
}
declare module 'sassdoc/dist/annotation/annotations/throw.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/throw'>;
}
declare module 'sassdoc/dist/annotation/annotations/todo.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/todo'>;
}
declare module 'sassdoc/dist/annotation/annotations/type.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/annotations/type'>;
}
declare module 'sassdoc/dist/annotation/index.js' {
  declare module.exports: $Exports<'sassdoc/dist/annotation/index'>;
}
declare module 'sassdoc/dist/cli.js' {
  declare module.exports: $Exports<'sassdoc/dist/cli'>;
}
declare module 'sassdoc/dist/environment.js' {
  declare module.exports: $Exports<'sassdoc/dist/environment'>;
}
declare module 'sassdoc/dist/errors.js' {
  declare module.exports: $Exports<'sassdoc/dist/errors'>;
}
declare module 'sassdoc/dist/exclude.js' {
  declare module.exports: $Exports<'sassdoc/dist/exclude'>;
}
declare module 'sassdoc/dist/logger.js' {
  declare module.exports: $Exports<'sassdoc/dist/logger'>;
}
declare module 'sassdoc/dist/notifier.js' {
  declare module.exports: $Exports<'sassdoc/dist/notifier'>;
}
declare module 'sassdoc/dist/parser.js' {
  declare module.exports: $Exports<'sassdoc/dist/parser'>;
}
declare module 'sassdoc/dist/recurse.js' {
  declare module.exports: $Exports<'sassdoc/dist/recurse'>;
}
declare module 'sassdoc/dist/sassdoc.js' {
  declare module.exports: $Exports<'sassdoc/dist/sassdoc'>;
}
declare module 'sassdoc/dist/sorter.js' {
  declare module.exports: $Exports<'sassdoc/dist/sorter'>;
}
declare module 'sassdoc/dist/utils.js' {
  declare module.exports: $Exports<'sassdoc/dist/utils'>;
}
declare module 'sassdoc/index' {
  declare module.exports: $Exports<'sassdoc'>;
}
declare module 'sassdoc/index.js' {
  declare module.exports: $Exports<'sassdoc'>;
}
