// flow-typed signature: 977afa6c1eff7090577d92df5c82e419
// flow-typed version: <<STUB>>/sharp_v^0.17.3/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sharp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sharp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sharp/binding' {
  declare module.exports: any;
}

declare module 'sharp/lib/channel' {
  declare module.exports: any;
}

declare module 'sharp/lib/colour' {
  declare module.exports: any;
}

declare module 'sharp/lib/composite' {
  declare module.exports: any;
}

declare module 'sharp/lib/constructor' {
  declare module.exports: any;
}

declare module 'sharp/lib/index' {
  declare module.exports: any;
}

declare module 'sharp/lib/input' {
  declare module.exports: any;
}

declare module 'sharp/lib/is' {
  declare module.exports: any;
}

declare module 'sharp/lib/operation' {
  declare module.exports: any;
}

declare module 'sharp/lib/output' {
  declare module.exports: any;
}

declare module 'sharp/lib/resize' {
  declare module.exports: any;
}

declare module 'sharp/lib/utility' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sharp/binding.js' {
  declare module.exports: $Exports<'sharp/binding'>;
}
declare module 'sharp/lib/channel.js' {
  declare module.exports: $Exports<'sharp/lib/channel'>;
}
declare module 'sharp/lib/colour.js' {
  declare module.exports: $Exports<'sharp/lib/colour'>;
}
declare module 'sharp/lib/composite.js' {
  declare module.exports: $Exports<'sharp/lib/composite'>;
}
declare module 'sharp/lib/constructor.js' {
  declare module.exports: $Exports<'sharp/lib/constructor'>;
}
declare module 'sharp/lib/index.js' {
  declare module.exports: $Exports<'sharp/lib/index'>;
}
declare module 'sharp/lib/input.js' {
  declare module.exports: $Exports<'sharp/lib/input'>;
}
declare module 'sharp/lib/is.js' {
  declare module.exports: $Exports<'sharp/lib/is'>;
}
declare module 'sharp/lib/operation.js' {
  declare module.exports: $Exports<'sharp/lib/operation'>;
}
declare module 'sharp/lib/output.js' {
  declare module.exports: $Exports<'sharp/lib/output'>;
}
declare module 'sharp/lib/resize.js' {
  declare module.exports: $Exports<'sharp/lib/resize'>;
}
declare module 'sharp/lib/utility.js' {
  declare module.exports: $Exports<'sharp/lib/utility'>;
}
