// flow-typed signature: 89822fb1a104289352585d34b326a6c6
// flow-typed version: <<STUB>>/shrink-ray_v^0.1.3/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shrink-ray'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'shrink-ray' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'shrink-ray/index' {
  declare module.exports: $Exports<'shrink-ray'>;
}
declare module 'shrink-ray/index.js' {
  declare module.exports: $Exports<'shrink-ray'>;
}
