// flow-typed signature: 8ef79a1975eef0d1a2f34315f0077438
// flow-typed version: <<STUB>>/stylelint-config-boldr_v^0.1.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-boldr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-boldr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-config-boldr/rules/core/at-rule' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/block' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/color' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/comment' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/custom-media' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/custom-property' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/declaration-block' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/declaration' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/font-family' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/font-weight' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/function' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/general' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/index' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/keyframe-declaration' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/length' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/media-feature' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/media-query-list' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/number' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/property' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/root-rule' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/rule' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/selector-list' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/selector' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/shorthand-property' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/string' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/stylelint-disable-comment' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/time' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/unit' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/value-list' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/core/value' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/order/index' {
  declare module.exports: any;
}

declare module 'stylelint-config-boldr/rules/scss/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-config-boldr/index' {
  declare module.exports: $Exports<'stylelint-config-boldr'>;
}
declare module 'stylelint-config-boldr/index.js' {
  declare module.exports: $Exports<'stylelint-config-boldr'>;
}
declare module 'stylelint-config-boldr/rules/core/at-rule.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/at-rule'>;
}
declare module 'stylelint-config-boldr/rules/core/block.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/block'>;
}
declare module 'stylelint-config-boldr/rules/core/color.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/color'>;
}
declare module 'stylelint-config-boldr/rules/core/comment.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/comment'>;
}
declare module 'stylelint-config-boldr/rules/core/custom-media.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/custom-media'>;
}
declare module 'stylelint-config-boldr/rules/core/custom-property.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/custom-property'>;
}
declare module 'stylelint-config-boldr/rules/core/declaration-block.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/declaration-block'>;
}
declare module 'stylelint-config-boldr/rules/core/declaration.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/declaration'>;
}
declare module 'stylelint-config-boldr/rules/core/font-family.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/font-family'>;
}
declare module 'stylelint-config-boldr/rules/core/font-weight.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/font-weight'>;
}
declare module 'stylelint-config-boldr/rules/core/function.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/function'>;
}
declare module 'stylelint-config-boldr/rules/core/general.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/general'>;
}
declare module 'stylelint-config-boldr/rules/core/index.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/index'>;
}
declare module 'stylelint-config-boldr/rules/core/keyframe-declaration.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/keyframe-declaration'>;
}
declare module 'stylelint-config-boldr/rules/core/length.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/length'>;
}
declare module 'stylelint-config-boldr/rules/core/media-feature.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/media-feature'>;
}
declare module 'stylelint-config-boldr/rules/core/media-query-list.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/media-query-list'>;
}
declare module 'stylelint-config-boldr/rules/core/number.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/number'>;
}
declare module 'stylelint-config-boldr/rules/core/property.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/property'>;
}
declare module 'stylelint-config-boldr/rules/core/root-rule.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/root-rule'>;
}
declare module 'stylelint-config-boldr/rules/core/rule.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/rule'>;
}
declare module 'stylelint-config-boldr/rules/core/selector-list.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/selector-list'>;
}
declare module 'stylelint-config-boldr/rules/core/selector.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/selector'>;
}
declare module 'stylelint-config-boldr/rules/core/shorthand-property.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/shorthand-property'>;
}
declare module 'stylelint-config-boldr/rules/core/string.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/string'>;
}
declare module 'stylelint-config-boldr/rules/core/stylelint-disable-comment.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/stylelint-disable-comment'>;
}
declare module 'stylelint-config-boldr/rules/core/time.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/time'>;
}
declare module 'stylelint-config-boldr/rules/core/unit.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/unit'>;
}
declare module 'stylelint-config-boldr/rules/core/value-list.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/value-list'>;
}
declare module 'stylelint-config-boldr/rules/core/value.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/core/value'>;
}
declare module 'stylelint-config-boldr/rules/order/index.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/order/index'>;
}
declare module 'stylelint-config-boldr/rules/scss/index.js' {
  declare module.exports: $Exports<'stylelint-config-boldr/rules/scss/index'>;
}
