// flow-typed signature: c3b53728e914dfd8a0286ab29e2186f0
// flow-typed version: <<STUB>>/sw-precache-webpack-plugin_v^0.6.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sw-precache-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sw-precache-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sw-precache-webpack-plugin/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sw-precache-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'sw-precache-webpack-plugin/lib/index'>;
}
