// flow-typed signature: 816e7d0e4b9b91f75af0a1cd26e2ac37
// flow-typed version: <<STUB>>/yarn-add-webpack-plugin_v^0.1.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yarn-add-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yarn-add-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yarn-add-webpack-plugin/lib/installer' {
  declare module.exports: any;
}

declare module 'yarn-add-webpack-plugin/lib/normalizeLoader' {
  declare module.exports: any;
}

declare module 'yarn-add-webpack-plugin/lib/yarnAddWebpackPlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yarn-add-webpack-plugin/index' {
  declare module.exports: $Exports<'yarn-add-webpack-plugin'>;
}
declare module 'yarn-add-webpack-plugin/index.js' {
  declare module.exports: $Exports<'yarn-add-webpack-plugin'>;
}
declare module 'yarn-add-webpack-plugin/lib/installer.js' {
  declare module.exports: $Exports<'yarn-add-webpack-plugin/lib/installer'>;
}
declare module 'yarn-add-webpack-plugin/lib/normalizeLoader.js' {
  declare module.exports: $Exports<'yarn-add-webpack-plugin/lib/normalizeLoader'>;
}
declare module 'yarn-add-webpack-plugin/lib/yarnAddWebpackPlugin.js' {
  declare module.exports: $Exports<'yarn-add-webpack-plugin/lib/yarnAddWebpackPlugin'>;
}
