export const GET_MAIN_MENU_REQUEST = '@boldr/menu/GET_MAIN_MENU_REQUEST';
export const GET_MAIN_MENU_SUCCESS = '@boldr/menu/GET_MAIN_MENU_SUCCESS';
export const GET_MAIN_MENU_FAILURE = '@boldr/menu/FETCH_MENUS_FAILURE';

export const UPDATE_MENU_REQUEST = '@boldr/MENU/UPDATE_MENU_REQUEST';
export const UPDATE_MENU_SUCCESS = '@boldr/MENU/UPDATE_MENU_SUCCESS';
export const UPDATE_MENU_FAILURE = '@boldr/MENU/UPDATE_MENU_FAILURE';

export const ADD_MENU_DETAIL_REQUEST = '@boldr/MENU/ADD_MENU_DETAIL_REQUEST';
export const ADD_MENU_DETAIL_SUCCESS = '@boldr/MENU/ADD_MENU_DETAIL_SUCCESS';
export const ADD_MENU_DETAIL_FAILURE = '@boldr/MENU/ADD_MENU_DETAIL_FAILURE';
