export const DELETE_ATTACHMENT_REQUEST = 'DELETE_ATTACHMENT_REQUEST';
export const DELETE_ATTACHMENT_SUCCESS = 'DELETE_ATTACHMENT_SUCCESS';
export const DELETE_ATTACHMENT_FAILURE = 'DELETE_ATTACHMENT_FAILURE';

export const GET_ATTACHMENT_REQUEST = 'GET_ATTACHMENT_REQUEST';
export const GET_ATTACHMENT_SUCCESS = 'GET_ATTACHMENT_SUCCESS';
export const GET_ATTACHMENT_FAILURE = 'GET_ATTACHMENT_FAILURE';

export const UPLOAD_ATTACHMENT_REQUEST = 'UPLOAD_ATTACHMENT_REQUEST';
export const UPLOAD_ATTACHMENT_SUCCESS = 'UPLOAD_ATTACHMENT_SUCCESS';
export const UPLOAD_ATTACHMENT_FAILURE = 'UPLOAD_ATTACHMENT_FAILURE';

export const UPLOAD_POST_IMG_REQUEST = '@boldr/admin/UPLOAD_POST_IMG_REQUEST';
export const UPLOAD_POST_IMG_SUCCESS = '@boldr/admin/UPLOAD_POST_IMG_SUCCESS';
export const UPLOAD_POST_IMG_FAILURE = '@boldr/admin/UPLOAD_POST_IMG_FAILURE';

export const SELECT_FILE = '@boldr/admin/attachments/SELECT_FILE';
