// @flow
import type { EditorState } from 'draft-js';
import type { ToolbarConfig } from './core/config';

export type ChangeHandler = (value: any) => any;

export type BoldrEditorType = {
  onChange?: ChangeHandler,
  onEditorStateChange?: ChangeHandler,
  onContentStateChange?: ChangeHandler,
  defaultContentState?: EditorState,
  contentState?: EditorState,
  editorState?: EditorState,
  defaultEditorState?: EditorState,
  toolbarOnFocus?: Function,
  spellcheck?: boolean,
  stripPastedStyles?: boolean,
  toolbar?: ToolbarConfig,
  toolbarCustomButtons?: Array<any>,
  toolbarHidden?: boolean,
  locale?: string,
  contentFormat?: string,
  importContent?: any,
  localization?: Object,
  editorClassName?: string,
  wrapperClassName?: string,
  editorStyle?: Object,
  wrapperStyle?: Object,
  uploadCallback?: Function,
  onFocus?: Function,
  onBlur?: Function,
  onTab?: Function,
  mention?: Object,
  hashtag?: Object,
  textAlignment?: string,
  readOnly?: boolean,
  tabIndex?: number,
  placeholder?: string,
  ariaLabel?: string,
  ariaOwneeID?: string,
  ariaActiveDescendantID?: string,
  ariaAutoComplete?: string,
  ariaDescribedBy?: string,
  ariaExpanded?: string,
  ariaHasPopup?: string,
  customBlockRenderFunc?: Function,
  wrapperId?: string,
  customDecorators?: Array<any>,
};
