export const BOLDR_NS = 'boldrui-';

export const StyleClasses = {
  APP: 'boldrui-app',
  BREADCRUMB: 'boldrui-breadcrumb',
  BREADCRUMB_ITEM: 'boldrui-breadcrumb-item',
  CARD: 'boldrui-card',
  DASHBOARD_FOOTER: 'boldrui-dash-footer',
  DIVIDER: 'boldrui-divider',
  FOOTER: 'boldrui-footer',
  HEADER: 'boldrui-header',
  HEADING: 'boldrui-heading',
  IMAGE: 'boldrui-image',
  LOADER: 'boldrui-loader',
  MEDIA: 'boldrui-media',
  MEDIA_OVERLAY: 'boldrui-media-overlay',
  PAPER: 'boldrui-paper',
  ARTICLE_CARD: 'boldrui-article-card',
  ARTICLE_SIDEBAR: 'boldrui-article-sidebar',
  ARTICLE_SIDEBAR_TAGS: 'boldrui-article-sidebar__tags',
  ARTICLE_SIDEBAR_AUTHOR: 'boldrui-article-sidebar__author',
  PROFILE_DETAIL: 'boldrui-profile-detail',
  PROFILE: 'boldrui-profile',
  SIDEBAR: 'boldrui-sidebar',
  SIDEBAR_NAV: 'boldrui-sidebar-nav',
  SIDEBAR_NAV_ITEM: 'boldrui-sidebar-nav-item',
  SIDEBAR_TITLE: 'boldrui-sidebar-title',
  SIDEBAR_LINK: 'boldrui-sidebar-link',
  SIDEBAR_LINK_ACT: 'boldrui-sidebar-link__active',
  SINGLE_POST: 'boldrui-single-post',
  STATS_WIDGET: 'boldrui-widget__stats',
  STATS_LABEL: 'boldrui-widget__stats-label',
  STATS_VALUE: 'boldrui-widget__stats-value',
  TAG: 'boldrui-tag',
  TAG_BLOCK: 'boldrui-tagblock',
  TEXT: 'boldrui-text',
  TOPBAR: 'boldrui-topbar',
  TOPBAR_CHILD: 'boldrui-topbar-child',
  TOPBAR_SEARCH: 'boldrui-topbar-search',
  WIDGET: 'boldrui-widget',
};
