version: '2'
services:

  postgres:
    container_name: boldr_pg
    build: ./db
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      # - POSTGRES_DB=boldr
    ports:
      - "5432:5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data
    networks:
      - boldr

  redis:
    image: redis:3.2.3-alpine
    container_name: boldr_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
    networks:
      - boldr

  boldr:
    build: .
    container_name: boldr_cms
    restart: always
    environment:
      POSTGRES_CONN_URI: postgres://postgres:password@postgres:5432/boldr
      REDIS_CONN_URI: redis://redis:6379/1
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    networks:
      - boldr
    volumes:
      - "./public:/app/public"

networks:
  boldr:
    driver: bridge

volumes:
  pg_volume:
    driver: local
  redis_volume:
    driver: local
