// flow-typed signature: fd5612bb9f51cbe07197582b56d17a1d
// flow-typed version: <<STUB>>/prepublish_v^1.1.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prepublish'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prepublish' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prepublish/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prepublish/rollup.config.js' {
  declare module.exports: $Exports<'prepublish/rollup.config'>;
}
