// flow-typed signature: bcbccdddcbf88519eaf392030530df3a
// flow-typed version: <<STUB>>/webpack-subresource-integrity_v^1.0.1/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-subresource-integrity'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-subresource-integrity' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-subresource-integrity/index' {
  declare module.exports: $Exports<'webpack-subresource-integrity'>;
}
declare module 'webpack-subresource-integrity/index.js' {
  declare module.exports: $Exports<'webpack-subresource-integrity'>;
}
