export const FETCH_MENUS_REQUEST = '@boldr/MENU/FETCH_MENUS_REQUEST';
export const FETCH_MENUS_SUCCESS = '@boldr/MENU/FETCH_MENUS_SUCCESS';
export const FETCH_MENUS_FAILURE = '@boldr/MENU/FETCH_MENUS_FAILURE';

export const UPDATE_MENU_REQUEST = '@boldr/MENU/UPDATE_MENU_REQUEST';
export const UPDATE_MENU_SUCCESS = '@boldr/MENU/UPDATE_MENU_SUCCESS';
export const UPDATE_MENU_FAILURE = '@boldr/MENU/UPDATE_MENU_FAILURE';

export const ADD_MENU_DETAIL_REQUEST = '@boldr/MENU/ADD_MENU_DETAIL_REQUEST';
export const ADD_MENU_DETAIL_SUCCESS = '@boldr/MENU/ADD_MENU_DETAIL_SUCCESS';
export const ADD_MENU_DETAIL_FAILURE = '@boldr/MENU/ADD_MENU_DETAIL_FAILURE';
