// flow-typed signature: 645d8f4d9a0ec4d5f619b90b6885d99e
// flow-typed version: <<STUB>>/busboy_v^0.2.14/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'busboy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'busboy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'busboy/deps/encoding/encoding-indexes' {
  declare module.exports: any;
}

declare module 'busboy/deps/encoding/encoding' {
  declare module.exports: any;
}

declare module 'busboy/lib/main' {
  declare module.exports: any;
}

declare module 'busboy/lib/types/multipart' {
  declare module.exports: any;
}

declare module 'busboy/lib/types/urlencoded' {
  declare module.exports: any;
}

declare module 'busboy/lib/utils' {
  declare module.exports: any;
}

declare module 'busboy/test/test-types-multipart' {
  declare module.exports: any;
}

declare module 'busboy/test/test-types-urlencoded' {
  declare module.exports: any;
}

declare module 'busboy/test/test-utils-decoder' {
  declare module.exports: any;
}

declare module 'busboy/test/test-utils-parse-params' {
  declare module.exports: any;
}

declare module 'busboy/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'busboy/deps/encoding/encoding-indexes.js' {
  declare module.exports: $Exports<'busboy/deps/encoding/encoding-indexes'>;
}
declare module 'busboy/deps/encoding/encoding.js' {
  declare module.exports: $Exports<'busboy/deps/encoding/encoding'>;
}
declare module 'busboy/lib/main.js' {
  declare module.exports: $Exports<'busboy/lib/main'>;
}
declare module 'busboy/lib/types/multipart.js' {
  declare module.exports: $Exports<'busboy/lib/types/multipart'>;
}
declare module 'busboy/lib/types/urlencoded.js' {
  declare module.exports: $Exports<'busboy/lib/types/urlencoded'>;
}
declare module 'busboy/lib/utils.js' {
  declare module.exports: $Exports<'busboy/lib/utils'>;
}
declare module 'busboy/test/test-types-multipart.js' {
  declare module.exports: $Exports<'busboy/test/test-types-multipart'>;
}
declare module 'busboy/test/test-types-urlencoded.js' {
  declare module.exports: $Exports<'busboy/test/test-types-urlencoded'>;
}
declare module 'busboy/test/test-utils-decoder.js' {
  declare module.exports: $Exports<'busboy/test/test-utils-decoder'>;
}
declare module 'busboy/test/test-utils-parse-params.js' {
  declare module.exports: $Exports<'busboy/test/test-utils-parse-params'>;
}
declare module 'busboy/test/test.js' {
  declare module.exports: $Exports<'busboy/test/test'>;
}
