// flow-typed signature: 2243ea5ce24fb77d476145412c3cd76c
// flow-typed version: <<STUB>>/connect-busboy_v^0.0.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect-busboy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect-busboy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'connect-busboy/index' {
  declare module.exports: $Exports<'connect-busboy'>;
}
declare module 'connect-busboy/index.js' {
  declare module.exports: $Exports<'connect-busboy'>;
}
