// flow-typed signature: 393e9e02cff53406b370f34e3fa6fac8
// flow-typed version: <<STUB>>/express-redis-cache_v^0.5.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-redis-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-redis-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-redis-cache/bin/express-redis-cache' {
  declare module.exports: any;
}

declare module 'express-redis-cache/example/example' {
  declare module.exports: any;
}

declare module 'express-redis-cache/express/server' {
  declare module.exports: any;
}

declare module 'express-redis-cache/lib/ExpressRedisCache' {
  declare module.exports: any;
}

declare module 'express-redis-cache/lib/ExpressRedisCache/add' {
  declare module.exports: any;
}

declare module 'express-redis-cache/lib/ExpressRedisCache/del' {
  declare module.exports: any;
}

declare module 'express-redis-cache/lib/ExpressRedisCache/expire' {
  declare module.exports: any;
}

declare module 'express-redis-cache/lib/ExpressRedisCache/get' {
  declare module.exports: any;
}

declare module 'express-redis-cache/lib/ExpressRedisCache/route' {
  declare module.exports: any;
}

declare module 'express-redis-cache/lib/ExpressRedisCache/size' {
  declare module.exports: any;
}

declare module 'express-redis-cache/lib/sizeof' {
  declare module.exports: any;
}

declare module 'express-redis-cache/test/add' {
  declare module.exports: any;
}

declare module 'express-redis-cache/test/del' {
  declare module.exports: any;
}

declare module 'express-redis-cache/test/expire' {
  declare module.exports: any;
}

declare module 'express-redis-cache/test/express' {
  declare module.exports: any;
}

declare module 'express-redis-cache/test/ExpressRedisCache' {
  declare module.exports: any;
}

declare module 'express-redis-cache/test/get' {
  declare module.exports: any;
}

declare module 'express-redis-cache/test/route' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-redis-cache/bin/express-redis-cache.js' {
  declare module.exports: $Exports<'express-redis-cache/bin/express-redis-cache'>;
}
declare module 'express-redis-cache/example/example.js' {
  declare module.exports: $Exports<'express-redis-cache/example/example'>;
}
declare module 'express-redis-cache/express/server.js' {
  declare module.exports: $Exports<'express-redis-cache/express/server'>;
}
declare module 'express-redis-cache/index' {
  declare module.exports: $Exports<'express-redis-cache'>;
}
declare module 'express-redis-cache/index.js' {
  declare module.exports: $Exports<'express-redis-cache'>;
}
declare module 'express-redis-cache/lib/ExpressRedisCache.js' {
  declare module.exports: $Exports<'express-redis-cache/lib/ExpressRedisCache'>;
}
declare module 'express-redis-cache/lib/ExpressRedisCache/add.js' {
  declare module.exports: $Exports<'express-redis-cache/lib/ExpressRedisCache/add'>;
}
declare module 'express-redis-cache/lib/ExpressRedisCache/del.js' {
  declare module.exports: $Exports<'express-redis-cache/lib/ExpressRedisCache/del'>;
}
declare module 'express-redis-cache/lib/ExpressRedisCache/expire.js' {
  declare module.exports: $Exports<'express-redis-cache/lib/ExpressRedisCache/expire'>;
}
declare module 'express-redis-cache/lib/ExpressRedisCache/get.js' {
  declare module.exports: $Exports<'express-redis-cache/lib/ExpressRedisCache/get'>;
}
declare module 'express-redis-cache/lib/ExpressRedisCache/route.js' {
  declare module.exports: $Exports<'express-redis-cache/lib/ExpressRedisCache/route'>;
}
declare module 'express-redis-cache/lib/ExpressRedisCache/size.js' {
  declare module.exports: $Exports<'express-redis-cache/lib/ExpressRedisCache/size'>;
}
declare module 'express-redis-cache/lib/sizeof.js' {
  declare module.exports: $Exports<'express-redis-cache/lib/sizeof'>;
}
declare module 'express-redis-cache/test/add.js' {
  declare module.exports: $Exports<'express-redis-cache/test/add'>;
}
declare module 'express-redis-cache/test/del.js' {
  declare module.exports: $Exports<'express-redis-cache/test/del'>;
}
declare module 'express-redis-cache/test/expire.js' {
  declare module.exports: $Exports<'express-redis-cache/test/expire'>;
}
declare module 'express-redis-cache/test/express.js' {
  declare module.exports: $Exports<'express-redis-cache/test/express'>;
}
declare module 'express-redis-cache/test/ExpressRedisCache.js' {
  declare module.exports: $Exports<'express-redis-cache/test/ExpressRedisCache'>;
}
declare module 'express-redis-cache/test/get.js' {
  declare module.exports: $Exports<'express-redis-cache/test/get'>;
}
declare module 'express-redis-cache/test/route.js' {
  declare module.exports: $Exports<'express-redis-cache/test/route'>;
}
