// flow-typed signature: dd9090025f8b0381aac6c12ce9d3d1fd
// flow-typed version: <<STUB>>/express-validator_v^3.1.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-validator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-validator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-validator/lib/express_validator' {
  declare module.exports: any;
}

declare module 'express-validator/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-validator/index' {
  declare module.exports: $Exports<'express-validator'>;
}
declare module 'express-validator/index.js' {
  declare module.exports: $Exports<'express-validator'>;
}
declare module 'express-validator/lib/express_validator.js' {
  declare module.exports: $Exports<'express-validator/lib/express_validator'>;
}
declare module 'express-validator/lib/utils.js' {
  declare module.exports: $Exports<'express-validator/lib/utils'>;
}
