// flow-typed signature: f4e31784001088ed0afe94fc3fc3ed13
// flow-typed version: <<STUB>>/express-winston_v^2.3.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-winston'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-winston' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-winston/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-winston/index' {
  declare module.exports: $Exports<'express-winston'>;
}
declare module 'express-winston/index.js' {
  declare module.exports: $Exports<'express-winston'>;
}
declare module 'express-winston/test/test.js' {
  declare module.exports: $Exports<'express-winston/test/test'>;
}
