// flow-typed signature: d8d173595621559a9f02b3f8d1c1a958
// flow-typed version: <<STUB>>/express-flash_v^0.0.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-flash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-flash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-flash/lib/express-flash' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-flash/index' {
  declare module.exports: $Exports<'express-flash'>;
}
declare module 'express-flash/index.js' {
  declare module.exports: $Exports<'express-flash'>;
}
declare module 'express-flash/lib/express-flash.js' {
  declare module.exports: $Exports<'express-flash/lib/express-flash'>;
}
