export const BOLDR_NS = 'boldrui-';

export const StyleClasses = {
  APP: `${BOLDR_NS}app`,
  CARD: `${BOLDR_NS}card`,
  COMMENT_FORM: `${BOLDR_NS}comment-form`,
  FOOTER: `${BOLDR_NS}footer`,
  HEADER: `${BOLDR_NS}header`,
  HEADING: `${BOLDR_NS}heading`,
  IMAGE: `${BOLDR_NS}image`,
  POST_CARD: `${BOLDR_NS}post-card`,
  POST_SIDEBAR: `${BOLDR_NS}post-sidebar`,
  POST_SIDEBAR_TAGS: `${BOLDR_NS}sidebar-tags`,
  POST_SIDEBAR_AUTHOR: `${BOLDR_NS}sidebar-author`,
  PROFILE_DETAIL: `${BOLDR_NS}profile-detail`,
  PROFILE: `${BOLDR_NS}profile`,
  SINGLE_POST: `${BOLDR_NS}single-post`,
  STATS_WIDGET: `${BOLDR_NS}widget__stats`,
  STATS_LABEL: `${BOLDR_NS}widget__stats-label`,
  STATS_VALUE: `${BOLDR_NS}widget__stats-value`,
  TAG: `${BOLDR_NS}tag`,
  TAG_BLOCK: `${BOLDR_NS}tagblock`,
  TEXT: `${BOLDR_NS}text`,
  WIDGET: `${BOLDR_NS}widget`,
};
