export const BOLDR_NS = 'boldrui-';

export const StyleClasses = {
  APP: `${BOLDR_NS}app`,
  BREADCRUMB: `${BOLDR_NS}breadcrumb`,
  BREADCRUMB_ITEM: `${BOLDR_NS}breadcrumb-item`,
  CARD: `${BOLDR_NS}card`,
  DASHBOARD_FOOTER: `${BOLDR_NS}dash-footer`,
  DIVIDER: `${BOLDR_NS}divider`,
  FOOTER: `${BOLDR_NS}footer`,
  HEADER: `${BOLDR_NS}header`,
  HEADING: `${BOLDR_NS}heading`,
  IMAGE: `${BOLDR_NS}image`,
  LOADER: `${BOLDR_NS}loader`,
  MEDIA: `${BOLDR_NS}media`,
  MEDIA_OVERLAY: `${BOLDR_NS}media-overlay`,
  PAPER: `${BOLDR_NS}paper`,
  POST_CARD: `${BOLDR_NS}post-card`,
  POST_SIDEBAR: `${BOLDR_NS}post-sidebar`,
  POST_SIDEBAR_TAGS: `${BOLDR_NS}sidebar-tags`,
  POST_SIDEBAR_AUTHOR: `${BOLDR_NS}sidebar-author`,
  PROFILE_DETAIL: `${BOLDR_NS}profile-detail`,
  PROFILE: `${BOLDR_NS}profile`,
  SIDEBAR: `${BOLDR_NS}sidebar`,
  SIDEBAR_NAV: `${BOLDR_NS}sidebar-nav`,
  SIDEBAR_NAV_ITEM: `${BOLDR_NS}sidebar-nav-item`,
  SIDEBAR_TITLE: `${BOLDR_NS}sidebar-title`,
  SIDEBAR_LINK: `${BOLDR_NS}sidebar-link`,
  SIDEBAR_LINK_ACT: `${BOLDR_NS}sidebar-link__active`,
  SINGLE_POST: `${BOLDR_NS}single-post`,
  STATS_WIDGET: `${BOLDR_NS}widget__stats`,
  STATS_LABEL: `${BOLDR_NS}widget__stats-label`,
  STATS_VALUE: `${BOLDR_NS}widget__stats-value`,
  TAG: `${BOLDR_NS}tag`,
  TAG_BLOCK: `${BOLDR_NS}tagblock`,
  TEXT: `${BOLDR_NS}text`,
  TOPBAR: `${BOLDR_NS}topbar`,
  TOPBAR_CHILD: `${BOLDR_NS}topbar-child`,
  TOPBAR_SEARCH: `${BOLDR_NS}topbar-search`,
  WIDGET: `${BOLDR_NS}widget`,
};
