// flow-typed signature: f06493b95f6cc9319bcc08c31436b16d
// flow-typed version: <<STUB>>/@boldr/cli_v0.2.0-beta.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@boldr/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@boldr/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@boldr/cli/bin/boldr' {
  declare module.exports: any;
}

declare module '@boldr/cli/src/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module '@boldr/cli/bin/boldr.js' {
  declare module.exports: $Exports<'@boldr/cli/bin/boldr'>;
}
declare module '@boldr/cli/src/cli.js' {
  declare module.exports: $Exports<'@boldr/cli/src/cli'>;
}
