// flow-typed signature: 9d12f1f685dda983f71bc5582e393d52
// flow-typed version: <<STUB>>/@boldr/cli_v0.2.0-beta.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@boldr/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@boldr/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@boldr/cli/bin/boldr' {
  declare module.exports: any;
}

declare module '@boldr/cli/lib/cli' {
  declare module.exports: any;
}

declare module '@boldr/cli/lib/commands/clean' {
  declare module.exports: any;
}

declare module '@boldr/cli/lib/commands/dev' {
  declare module.exports: any;
}

declare module '@boldr/cli/lib/commands/init' {
  declare module.exports: any;
}

declare module '@boldr/cli/lib/commands/migrate' {
  declare module.exports: any;
}

declare module '@boldr/cli/lib/commands/migration' {
  declare module.exports: any;
}

declare module '@boldr/cli/lib/commands/seed' {
  declare module.exports: any;
}

declare module '@boldr/cli/lib/util/partialPkg' {
  declare module.exports: any;
}

declare module '@boldr/cli/src/cli' {
  declare module.exports: any;
}

declare module '@boldr/cli/src/commands/clean' {
  declare module.exports: any;
}

declare module '@boldr/cli/src/commands/dev' {
  declare module.exports: any;
}

declare module '@boldr/cli/src/commands/init' {
  declare module.exports: any;
}

declare module '@boldr/cli/src/commands/migrate' {
  declare module.exports: any;
}

declare module '@boldr/cli/src/commands/migration' {
  declare module.exports: any;
}

declare module '@boldr/cli/src/commands/seed' {
  declare module.exports: any;
}

declare module '@boldr/cli/src/util/partialPkg' {
  declare module.exports: any;
}

declare module '@boldr/cli/static/hello' {
  declare module.exports: any;
}

declare module '@boldr/cli/static/src/clientEntry' {
  declare module.exports: any;
}

declare module '@boldr/cli/static/src/reducers' {
  declare module.exports: any;
}

declare module '@boldr/cli/static/src/serverEntry' {
  declare module.exports: any;
}

// Filename aliases
declare module '@boldr/cli/bin/boldr.js' {
  declare module.exports: $Exports<'@boldr/cli/bin/boldr'>;
}
declare module '@boldr/cli/lib/cli.js' {
  declare module.exports: $Exports<'@boldr/cli/lib/cli'>;
}
declare module '@boldr/cli/lib/commands/clean.js' {
  declare module.exports: $Exports<'@boldr/cli/lib/commands/clean'>;
}
declare module '@boldr/cli/lib/commands/dev.js' {
  declare module.exports: $Exports<'@boldr/cli/lib/commands/dev'>;
}
declare module '@boldr/cli/lib/commands/init.js' {
  declare module.exports: $Exports<'@boldr/cli/lib/commands/init'>;
}
declare module '@boldr/cli/lib/commands/migrate.js' {
  declare module.exports: $Exports<'@boldr/cli/lib/commands/migrate'>;
}
declare module '@boldr/cli/lib/commands/migration.js' {
  declare module.exports: $Exports<'@boldr/cli/lib/commands/migration'>;
}
declare module '@boldr/cli/lib/commands/seed.js' {
  declare module.exports: $Exports<'@boldr/cli/lib/commands/seed'>;
}
declare module '@boldr/cli/lib/util/partialPkg.js' {
  declare module.exports: $Exports<'@boldr/cli/lib/util/partialPkg'>;
}
declare module '@boldr/cli/src/cli.js' {
  declare module.exports: $Exports<'@boldr/cli/src/cli'>;
}
declare module '@boldr/cli/src/commands/clean.js' {
  declare module.exports: $Exports<'@boldr/cli/src/commands/clean'>;
}
declare module '@boldr/cli/src/commands/dev.js' {
  declare module.exports: $Exports<'@boldr/cli/src/commands/dev'>;
}
declare module '@boldr/cli/src/commands/init.js' {
  declare module.exports: $Exports<'@boldr/cli/src/commands/init'>;
}
declare module '@boldr/cli/src/commands/migrate.js' {
  declare module.exports: $Exports<'@boldr/cli/src/commands/migrate'>;
}
declare module '@boldr/cli/src/commands/migration.js' {
  declare module.exports: $Exports<'@boldr/cli/src/commands/migration'>;
}
declare module '@boldr/cli/src/commands/seed.js' {
  declare module.exports: $Exports<'@boldr/cli/src/commands/seed'>;
}
declare module '@boldr/cli/src/util/partialPkg.js' {
  declare module.exports: $Exports<'@boldr/cli/src/util/partialPkg'>;
}
declare module '@boldr/cli/static/hello.js' {
  declare module.exports: $Exports<'@boldr/cli/static/hello'>;
}
declare module '@boldr/cli/static/src/clientEntry.js' {
  declare module.exports: $Exports<'@boldr/cli/static/src/clientEntry'>;
}
declare module '@boldr/cli/static/src/reducers.js' {
  declare module.exports: $Exports<'@boldr/cli/static/src/reducers'>;
}
declare module '@boldr/cli/static/src/serverEntry.js' {
  declare module.exports: $Exports<'@boldr/cli/static/src/serverEntry'>;
}
