// flow-typed signature: 1fc2430d90dd52f7ccdfe4e1a5203f03
// flow-typed version: <<STUB>>/@boldr/config_v0.1.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@boldr/config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@boldr/config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@boldr/config/__tests__/__fixtures__/js-conf/default' {
  declare module.exports: any;
}

declare module '@boldr/config/__tests__/__fixtures__/js-conf/routes' {
  declare module.exports: any;
}

declare module '@boldr/config/__tests__/js-conf.test' {
  declare module.exports: any;
}

declare module '@boldr/config/__tests__/json-conf.test' {
  declare module.exports: any;
}

declare module '@boldr/config/__tests__/no-conf.test' {
  declare module.exports: any;
}

declare module '@boldr/config/config' {
  declare module.exports: any;
}

declare module '@boldr/config/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module '@boldr/config/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

// Filename aliases
declare module '@boldr/config/__tests__/__fixtures__/js-conf/default.js' {
  declare module.exports: $Exports<'@boldr/config/__tests__/__fixtures__/js-conf/default'>;
}
declare module '@boldr/config/__tests__/__fixtures__/js-conf/routes.js' {
  declare module.exports: $Exports<'@boldr/config/__tests__/__fixtures__/js-conf/routes'>;
}
declare module '@boldr/config/__tests__/js-conf.test.js' {
  declare module.exports: $Exports<'@boldr/config/__tests__/js-conf.test'>;
}
declare module '@boldr/config/__tests__/json-conf.test.js' {
  declare module.exports: $Exports<'@boldr/config/__tests__/json-conf.test'>;
}
declare module '@boldr/config/__tests__/no-conf.test.js' {
  declare module.exports: $Exports<'@boldr/config/__tests__/no-conf.test'>;
}
declare module '@boldr/config/config.js' {
  declare module.exports: $Exports<'@boldr/config/config'>;
}
declare module '@boldr/config/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'@boldr/config/coverage/lcov-report/prettify'>;
}
declare module '@boldr/config/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'@boldr/config/coverage/lcov-report/sorter'>;
}
