// flow-typed signature: c7f365609e8af3d1a3353114494ab951
// flow-typed version: <<STUB>>/@boldr/core_v0.1.0-beta.1-1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@boldr/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@boldr/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@boldr/core/lib/boldr-core.browser.es2015.esm' {
  declare module.exports: any;
}

declare module '@boldr/core/lib/boldr-core.browser.es5.esm' {
  declare module.exports: any;
}

declare module '@boldr/core/lib/boldr-core.node.es2015.cjs' {
  declare module.exports: any;
}

declare module '@boldr/core/lib/boldr-core.node.es2015.esm' {
  declare module.exports: any;
}

declare module '@boldr/core/lib/boldr-core.node.es5.cjs' {
  declare module.exports: any;
}

declare module '@boldr/core/lib/boldr-core.node.es5.esm' {
  declare module.exports: any;
}

declare module '@boldr/core/src/apollo/batchNetworkInterface' {
  declare module.exports: any;
}

declare module '@boldr/core/src/apollo/createApolloClient' {
  declare module.exports: any;
}

declare module '@boldr/core/src/apollo/createApolloClient.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/apollo/extractFiles' {
  declare module.exports: any;
}

declare module '@boldr/core/src/apollo/networkInterface' {
  declare module.exports: any;
}

declare module '@boldr/core/src/client' {
  declare module.exports: any;
}

declare module '@boldr/core/src/common' {
  declare module.exports: any;
}

declare module '@boldr/core/src/server' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/RouterConnection' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/wrapBoldrApp' {
  declare module.exports: any;
}

declare module '@boldr/core/src/state/boldr/actionTypes' {
  declare module.exports: any;
}

declare module '@boldr/core/src/state/boldr/index' {
  declare module.exports: any;
}

declare module '@boldr/core/src/state/boldr/notifications/actions' {
  declare module.exports: any;
}

declare module '@boldr/core/src/state/boldr/notifications/index' {
  declare module.exports: any;
}

declare module '@boldr/core/src/state/boldr/notifications/reducer' {
  declare module.exports: any;
}

declare module '@boldr/core/src/state/boldr/notifications/reducer.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/state/boldr/reducer' {
  declare module.exports: any;
}

declare module '@boldr/core/src/state/boldr/reducer.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/state/boldr/settings/reducer' {
  declare module.exports: any;
}

declare module '@boldr/core/src/state/boldr/ui/actions' {
  declare module.exports: any;
}

declare module '@boldr/core/src/state/boldr/ui/actions.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/state/boldr/ui/index' {
  declare module.exports: any;
}

declare module '@boldr/core/src/state/boldr/ui/reducer' {
  declare module.exports: any;
}

declare module '@boldr/core/src/state/boldr/ui/reducer.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/state/createBoldrStore' {
  declare module.exports: any;
}

declare module '@boldr/core/src/state/createBoldrStore.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/util/debug' {
  declare module.exports: any;
}

declare module '@boldr/core/src/util/flattenRoutes' {
  declare module.exports: any;
}

declare module '@boldr/core/src/util/validations' {
  declare module.exports: any;
}

// Filename aliases
declare module '@boldr/core/index' {
  declare module.exports: $Exports<'@boldr/core'>;
}
declare module '@boldr/core/index.js' {
  declare module.exports: $Exports<'@boldr/core'>;
}
declare module '@boldr/core/lib/boldr-core.browser.es2015.esm.js' {
  declare module.exports: $Exports<'@boldr/core/lib/boldr-core.browser.es2015.esm'>;
}
declare module '@boldr/core/lib/boldr-core.browser.es5.esm.js' {
  declare module.exports: $Exports<'@boldr/core/lib/boldr-core.browser.es5.esm'>;
}
declare module '@boldr/core/lib/boldr-core.node.es2015.cjs.js' {
  declare module.exports: $Exports<'@boldr/core/lib/boldr-core.node.es2015.cjs'>;
}
declare module '@boldr/core/lib/boldr-core.node.es2015.esm.js' {
  declare module.exports: $Exports<'@boldr/core/lib/boldr-core.node.es2015.esm'>;
}
declare module '@boldr/core/lib/boldr-core.node.es5.cjs.js' {
  declare module.exports: $Exports<'@boldr/core/lib/boldr-core.node.es5.cjs'>;
}
declare module '@boldr/core/lib/boldr-core.node.es5.esm.js' {
  declare module.exports: $Exports<'@boldr/core/lib/boldr-core.node.es5.esm'>;
}
declare module '@boldr/core/src/apollo/batchNetworkInterface.js' {
  declare module.exports: $Exports<'@boldr/core/src/apollo/batchNetworkInterface'>;
}
declare module '@boldr/core/src/apollo/createApolloClient.js' {
  declare module.exports: $Exports<'@boldr/core/src/apollo/createApolloClient'>;
}
declare module '@boldr/core/src/apollo/createApolloClient.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/apollo/createApolloClient.test'>;
}
declare module '@boldr/core/src/apollo/extractFiles.js' {
  declare module.exports: $Exports<'@boldr/core/src/apollo/extractFiles'>;
}
declare module '@boldr/core/src/apollo/networkInterface.js' {
  declare module.exports: $Exports<'@boldr/core/src/apollo/networkInterface'>;
}
declare module '@boldr/core/src/client.js' {
  declare module.exports: $Exports<'@boldr/core/src/client'>;
}
declare module '@boldr/core/src/common.js' {
  declare module.exports: $Exports<'@boldr/core/src/common'>;
}
declare module '@boldr/core/src/server.js' {
  declare module.exports: $Exports<'@boldr/core/src/server'>;
}
declare module '@boldr/core/src/shared/RouterConnection.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/RouterConnection'>;
}
declare module '@boldr/core/src/shared/wrapBoldrApp.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/wrapBoldrApp'>;
}
declare module '@boldr/core/src/state/boldr/actionTypes.js' {
  declare module.exports: $Exports<'@boldr/core/src/state/boldr/actionTypes'>;
}
declare module '@boldr/core/src/state/boldr/index.js' {
  declare module.exports: $Exports<'@boldr/core/src/state/boldr/index'>;
}
declare module '@boldr/core/src/state/boldr/notifications/actions.js' {
  declare module.exports: $Exports<'@boldr/core/src/state/boldr/notifications/actions'>;
}
declare module '@boldr/core/src/state/boldr/notifications/index.js' {
  declare module.exports: $Exports<'@boldr/core/src/state/boldr/notifications/index'>;
}
declare module '@boldr/core/src/state/boldr/notifications/reducer.js' {
  declare module.exports: $Exports<'@boldr/core/src/state/boldr/notifications/reducer'>;
}
declare module '@boldr/core/src/state/boldr/notifications/reducer.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/state/boldr/notifications/reducer.test'>;
}
declare module '@boldr/core/src/state/boldr/reducer.js' {
  declare module.exports: $Exports<'@boldr/core/src/state/boldr/reducer'>;
}
declare module '@boldr/core/src/state/boldr/reducer.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/state/boldr/reducer.test'>;
}
declare module '@boldr/core/src/state/boldr/settings/reducer.js' {
  declare module.exports: $Exports<'@boldr/core/src/state/boldr/settings/reducer'>;
}
declare module '@boldr/core/src/state/boldr/ui/actions.js' {
  declare module.exports: $Exports<'@boldr/core/src/state/boldr/ui/actions'>;
}
declare module '@boldr/core/src/state/boldr/ui/actions.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/state/boldr/ui/actions.test'>;
}
declare module '@boldr/core/src/state/boldr/ui/index.js' {
  declare module.exports: $Exports<'@boldr/core/src/state/boldr/ui/index'>;
}
declare module '@boldr/core/src/state/boldr/ui/reducer.js' {
  declare module.exports: $Exports<'@boldr/core/src/state/boldr/ui/reducer'>;
}
declare module '@boldr/core/src/state/boldr/ui/reducer.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/state/boldr/ui/reducer.test'>;
}
declare module '@boldr/core/src/state/createBoldrStore.js' {
  declare module.exports: $Exports<'@boldr/core/src/state/createBoldrStore'>;
}
declare module '@boldr/core/src/state/createBoldrStore.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/state/createBoldrStore.test'>;
}
declare module '@boldr/core/src/util/debug.js' {
  declare module.exports: $Exports<'@boldr/core/src/util/debug'>;
}
declare module '@boldr/core/src/util/flattenRoutes.js' {
  declare module.exports: $Exports<'@boldr/core/src/util/flattenRoutes'>;
}
declare module '@boldr/core/src/util/validations.js' {
  declare module.exports: $Exports<'@boldr/core/src/util/validations'>;
}
