// flow-typed signature: 91886876ed873f6efb47d1b6aef4598f
// flow-typed version: <<STUB>>/@boldr/core_v0.1.0-beta.2/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@boldr/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@boldr/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@boldr/core/lib/boldr-core.browser.esm' {
  declare module.exports: any;
}

declare module '@boldr/core/lib/boldr-core.node.cjs' {
  declare module.exports: any;
}

declare module '@boldr/core/lib/boldr-core.node.esm' {
  declare module.exports: any;
}

declare module '@boldr/core/src/client' {
  declare module.exports: any;
}

declare module '@boldr/core/src/client/configBrowser' {
  declare module.exports: any;
}

declare module '@boldr/core/src/common' {
  declare module.exports: any;
}

declare module '@boldr/core/src/server' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/apollo/batchNetworkInterface' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/apollo/createApolloClient' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/apollo/createApolloClient.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/apollo/extractFiles' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/apollo/networkInterface' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/history' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/state/boldr/actionTypes' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/state/boldr/index' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/state/boldr/notifications/actions' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/state/boldr/notifications/index' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/state/boldr/notifications/reducer' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/state/boldr/notifications/reducer.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/state/boldr/reducer' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/state/boldr/reducer.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/state/boldr/settings/reducer' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/state/boldr/ui/actions' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/state/boldr/ui/actions.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/state/boldr/ui/index' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/state/boldr/ui/reducer' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/state/boldr/ui/reducer.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/state/createBoldrStore' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/state/createBoldrStore.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/storage/index' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/storage/storage' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/storage/storage.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/token' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/token.test' {
  declare module.exports: any;
}

declare module '@boldr/core/src/shared/wrapBoldrApp' {
  declare module.exports: any;
}

declare module '@boldr/core/src/types' {
  declare module.exports: any;
}

declare module '@boldr/core/src/util/flattenRoutes' {
  declare module.exports: any;
}

declare module '@boldr/core/src/util/validations' {
  declare module.exports: any;
}

// Filename aliases
declare module '@boldr/core/index' {
  declare module.exports: $Exports<'@boldr/core'>;
}
declare module '@boldr/core/index.js' {
  declare module.exports: $Exports<'@boldr/core'>;
}
declare module '@boldr/core/lib/boldr-core.browser.esm.js' {
  declare module.exports: $Exports<'@boldr/core/lib/boldr-core.browser.esm'>;
}
declare module '@boldr/core/lib/boldr-core.node.cjs.js' {
  declare module.exports: $Exports<'@boldr/core/lib/boldr-core.node.cjs'>;
}
declare module '@boldr/core/lib/boldr-core.node.esm.js' {
  declare module.exports: $Exports<'@boldr/core/lib/boldr-core.node.esm'>;
}
declare module '@boldr/core/src/client.js' {
  declare module.exports: $Exports<'@boldr/core/src/client'>;
}
declare module '@boldr/core/src/client/configBrowser.js' {
  declare module.exports: $Exports<'@boldr/core/src/client/configBrowser'>;
}
declare module '@boldr/core/src/common.js' {
  declare module.exports: $Exports<'@boldr/core/src/common'>;
}
declare module '@boldr/core/src/server.js' {
  declare module.exports: $Exports<'@boldr/core/src/server'>;
}
declare module '@boldr/core/src/shared/apollo/batchNetworkInterface.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/apollo/batchNetworkInterface'>;
}
declare module '@boldr/core/src/shared/apollo/createApolloClient.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/apollo/createApolloClient'>;
}
declare module '@boldr/core/src/shared/apollo/createApolloClient.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/apollo/createApolloClient.test'>;
}
declare module '@boldr/core/src/shared/apollo/extractFiles.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/apollo/extractFiles'>;
}
declare module '@boldr/core/src/shared/apollo/networkInterface.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/apollo/networkInterface'>;
}
declare module '@boldr/core/src/shared/history.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/history'>;
}
declare module '@boldr/core/src/shared/state/boldr/actionTypes.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/state/boldr/actionTypes'>;
}
declare module '@boldr/core/src/shared/state/boldr/index.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/state/boldr/index'>;
}
declare module '@boldr/core/src/shared/state/boldr/notifications/actions.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/state/boldr/notifications/actions'>;
}
declare module '@boldr/core/src/shared/state/boldr/notifications/index.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/state/boldr/notifications/index'>;
}
declare module '@boldr/core/src/shared/state/boldr/notifications/reducer.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/state/boldr/notifications/reducer'>;
}
declare module '@boldr/core/src/shared/state/boldr/notifications/reducer.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/state/boldr/notifications/reducer.test'>;
}
declare module '@boldr/core/src/shared/state/boldr/reducer.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/state/boldr/reducer'>;
}
declare module '@boldr/core/src/shared/state/boldr/reducer.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/state/boldr/reducer.test'>;
}
declare module '@boldr/core/src/shared/state/boldr/settings/reducer.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/state/boldr/settings/reducer'>;
}
declare module '@boldr/core/src/shared/state/boldr/ui/actions.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/state/boldr/ui/actions'>;
}
declare module '@boldr/core/src/shared/state/boldr/ui/actions.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/state/boldr/ui/actions.test'>;
}
declare module '@boldr/core/src/shared/state/boldr/ui/index.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/state/boldr/ui/index'>;
}
declare module '@boldr/core/src/shared/state/boldr/ui/reducer.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/state/boldr/ui/reducer'>;
}
declare module '@boldr/core/src/shared/state/boldr/ui/reducer.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/state/boldr/ui/reducer.test'>;
}
declare module '@boldr/core/src/shared/state/createBoldrStore.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/state/createBoldrStore'>;
}
declare module '@boldr/core/src/shared/state/createBoldrStore.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/state/createBoldrStore.test'>;
}
declare module '@boldr/core/src/shared/storage/index.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/storage/index'>;
}
declare module '@boldr/core/src/shared/storage/storage.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/storage/storage'>;
}
declare module '@boldr/core/src/shared/storage/storage.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/storage/storage.test'>;
}
declare module '@boldr/core/src/shared/token.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/token'>;
}
declare module '@boldr/core/src/shared/token.test.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/token.test'>;
}
declare module '@boldr/core/src/shared/wrapBoldrApp.js' {
  declare module.exports: $Exports<'@boldr/core/src/shared/wrapBoldrApp'>;
}
declare module '@boldr/core/src/types.js' {
  declare module.exports: $Exports<'@boldr/core/src/types'>;
}
declare module '@boldr/core/src/util/flattenRoutes.js' {
  declare module.exports: $Exports<'@boldr/core/src/util/flattenRoutes'>;
}
declare module '@boldr/core/src/util/validations.js' {
  declare module.exports: $Exports<'@boldr/core/src/util/validations'>;
}
