// flow-typed signature: 17043895e705c312a8c9c5311c1c9e47
// flow-typed version: <<STUB>>/@boldr/icons_v0.1.0-rc.2/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@boldr/icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@boldr/icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@boldr/icons/Activity' {
  declare module.exports: any;
}

declare module '@boldr/icons/Airplay' {
  declare module.exports: any;
}

declare module '@boldr/icons/AlertCircle' {
  declare module.exports: any;
}

declare module '@boldr/icons/AlertOctagon' {
  declare module.exports: any;
}

declare module '@boldr/icons/AlertTriangle' {
  declare module.exports: any;
}

declare module '@boldr/icons/AlignCenter' {
  declare module.exports: any;
}

declare module '@boldr/icons/AlignJustify' {
  declare module.exports: any;
}

declare module '@boldr/icons/AlignLeft' {
  declare module.exports: any;
}

declare module '@boldr/icons/AlignRight' {
  declare module.exports: any;
}

declare module '@boldr/icons/Anchor' {
  declare module.exports: any;
}

declare module '@boldr/icons/Aperture' {
  declare module.exports: any;
}

declare module '@boldr/icons/ArrowDown' {
  declare module.exports: any;
}

declare module '@boldr/icons/ArrowDownLeft' {
  declare module.exports: any;
}

declare module '@boldr/icons/ArrowDownRight' {
  declare module.exports: any;
}

declare module '@boldr/icons/ArrowLeft' {
  declare module.exports: any;
}

declare module '@boldr/icons/ArrowRight' {
  declare module.exports: any;
}

declare module '@boldr/icons/ArrowUp' {
  declare module.exports: any;
}

declare module '@boldr/icons/ArrowUpLeft' {
  declare module.exports: any;
}

declare module '@boldr/icons/ArrowUpRight' {
  declare module.exports: any;
}

declare module '@boldr/icons/AtSign' {
  declare module.exports: any;
}

declare module '@boldr/icons/Award' {
  declare module.exports: any;
}

declare module '@boldr/icons/BarChart' {
  declare module.exports: any;
}

declare module '@boldr/icons/BarChart2' {
  declare module.exports: any;
}

declare module '@boldr/icons/Battery' {
  declare module.exports: any;
}

declare module '@boldr/icons/BatteryCharging' {
  declare module.exports: any;
}

declare module '@boldr/icons/Bell' {
  declare module.exports: any;
}

declare module '@boldr/icons/BellOff' {
  declare module.exports: any;
}

declare module '@boldr/icons/Bluetooth' {
  declare module.exports: any;
}

declare module '@boldr/icons/Bold' {
  declare module.exports: any;
}

declare module '@boldr/icons/Book' {
  declare module.exports: any;
}

declare module '@boldr/icons/Bookmark' {
  declare module.exports: any;
}

declare module '@boldr/icons/Box' {
  declare module.exports: any;
}

declare module '@boldr/icons/Briefcase' {
  declare module.exports: any;
}

declare module '@boldr/icons/Calendar' {
  declare module.exports: any;
}

declare module '@boldr/icons/Camera' {
  declare module.exports: any;
}

declare module '@boldr/icons/CameraOff' {
  declare module.exports: any;
}

declare module '@boldr/icons/Cast' {
  declare module.exports: any;
}

declare module '@boldr/icons/Check' {
  declare module.exports: any;
}

declare module '@boldr/icons/CheckCircle' {
  declare module.exports: any;
}

declare module '@boldr/icons/CheckSquare' {
  declare module.exports: any;
}

declare module '@boldr/icons/ChevronDown' {
  declare module.exports: any;
}

declare module '@boldr/icons/ChevronLeft' {
  declare module.exports: any;
}

declare module '@boldr/icons/ChevronRight' {
  declare module.exports: any;
}

declare module '@boldr/icons/ChevronsDown' {
  declare module.exports: any;
}

declare module '@boldr/icons/ChevronsLeft' {
  declare module.exports: any;
}

declare module '@boldr/icons/ChevronsRight' {
  declare module.exports: any;
}

declare module '@boldr/icons/ChevronsUp' {
  declare module.exports: any;
}

declare module '@boldr/icons/ChevronUp' {
  declare module.exports: any;
}

declare module '@boldr/icons/Chrome' {
  declare module.exports: any;
}

declare module '@boldr/icons/Circle' {
  declare module.exports: any;
}

declare module '@boldr/icons/Clipboard' {
  declare module.exports: any;
}

declare module '@boldr/icons/Clock' {
  declare module.exports: any;
}

declare module '@boldr/icons/Cloud' {
  declare module.exports: any;
}

declare module '@boldr/icons/CloudDrizzle' {
  declare module.exports: any;
}

declare module '@boldr/icons/CloudLightning' {
  declare module.exports: any;
}

declare module '@boldr/icons/CloudOff' {
  declare module.exports: any;
}

declare module '@boldr/icons/CloudRain' {
  declare module.exports: any;
}

declare module '@boldr/icons/CloudSnow' {
  declare module.exports: any;
}

declare module '@boldr/icons/Code' {
  declare module.exports: any;
}

declare module '@boldr/icons/Codepen' {
  declare module.exports: any;
}

declare module '@boldr/icons/Command' {
  declare module.exports: any;
}

declare module '@boldr/icons/Compass' {
  declare module.exports: any;
}

declare module '@boldr/icons/Copy' {
  declare module.exports: any;
}

declare module '@boldr/icons/CornerDownLeft' {
  declare module.exports: any;
}

declare module '@boldr/icons/CornerDownRight' {
  declare module.exports: any;
}

declare module '@boldr/icons/CornerLeftDown' {
  declare module.exports: any;
}

declare module '@boldr/icons/CornerLeftUp' {
  declare module.exports: any;
}

declare module '@boldr/icons/CornerRightDown' {
  declare module.exports: any;
}

declare module '@boldr/icons/CornerRightUp' {
  declare module.exports: any;
}

declare module '@boldr/icons/CornerUpLeft' {
  declare module.exports: any;
}

declare module '@boldr/icons/CornerUpRight' {
  declare module.exports: any;
}

declare module '@boldr/icons/Cpu' {
  declare module.exports: any;
}

declare module '@boldr/icons/CreditCard' {
  declare module.exports: any;
}

declare module '@boldr/icons/Crop' {
  declare module.exports: any;
}

declare module '@boldr/icons/Crosshair' {
  declare module.exports: any;
}

declare module '@boldr/icons/Delete' {
  declare module.exports: any;
}

declare module '@boldr/icons/Disc' {
  declare module.exports: any;
}

declare module '@boldr/icons/Download' {
  declare module.exports: any;
}

declare module '@boldr/icons/DownloadCloud' {
  declare module.exports: any;
}

declare module '@boldr/icons/Droplet' {
  declare module.exports: any;
}

declare module '@boldr/icons/Edit' {
  declare module.exports: any;
}

declare module '@boldr/icons/Edit2' {
  declare module.exports: any;
}

declare module '@boldr/icons/Edit3' {
  declare module.exports: any;
}

declare module '@boldr/icons/Embedded' {
  declare module.exports: any;
}

declare module '@boldr/icons/Eraser' {
  declare module.exports: any;
}

declare module '@boldr/icons/ExternalLink' {
  declare module.exports: any;
}

declare module '@boldr/icons/Eye' {
  declare module.exports: any;
}

declare module '@boldr/icons/EyeOff' {
  declare module.exports: any;
}

declare module '@boldr/icons/Facebook' {
  declare module.exports: any;
}

declare module '@boldr/icons/FastForward' {
  declare module.exports: any;
}

declare module '@boldr/icons/Feather' {
  declare module.exports: any;
}

declare module '@boldr/icons/File' {
  declare module.exports: any;
}

declare module '@boldr/icons/FileMinus' {
  declare module.exports: any;
}

declare module '@boldr/icons/FilePlus' {
  declare module.exports: any;
}

declare module '@boldr/icons/FileText' {
  declare module.exports: any;
}

declare module '@boldr/icons/Film' {
  declare module.exports: any;
}

declare module '@boldr/icons/Filter' {
  declare module.exports: any;
}

declare module '@boldr/icons/Flag' {
  declare module.exports: any;
}

declare module '@boldr/icons/Folder' {
  declare module.exports: any;
}

declare module '@boldr/icons/Github' {
  declare module.exports: any;
}

declare module '@boldr/icons/Gitlab' {
  declare module.exports: any;
}

declare module '@boldr/icons/Globe' {
  declare module.exports: any;
}

declare module '@boldr/icons/Grid' {
  declare module.exports: any;
}

declare module '@boldr/icons/Hash' {
  declare module.exports: any;
}

declare module '@boldr/icons/Heading' {
  declare module.exports: any;
}

declare module '@boldr/icons/Heading1' {
  declare module.exports: any;
}

declare module '@boldr/icons/Heading2' {
  declare module.exports: any;
}

declare module '@boldr/icons/Heading3' {
  declare module.exports: any;
}

declare module '@boldr/icons/Headphones' {
  declare module.exports: any;
}

declare module '@boldr/icons/Heart' {
  declare module.exports: any;
}

declare module '@boldr/icons/HelpCircle' {
  declare module.exports: any;
}

declare module '@boldr/icons/Home' {
  declare module.exports: any;
}

declare module '@boldr/icons/Icon' {
  declare module.exports: any;
}

declare module '@boldr/icons/Image' {
  declare module.exports: any;
}

declare module '@boldr/icons/Inbox' {
  declare module.exports: any;
}

declare module '@boldr/icons/index.es' {
  declare module.exports: any;
}

declare module '@boldr/icons/Info' {
  declare module.exports: any;
}

declare module '@boldr/icons/Instagram' {
  declare module.exports: any;
}

declare module '@boldr/icons/Italic' {
  declare module.exports: any;
}

declare module '@boldr/icons/Layers' {
  declare module.exports: any;
}

declare module '@boldr/icons/Layout' {
  declare module.exports: any;
}

declare module '@boldr/icons/LifeBuoy' {
  declare module.exports: any;
}

declare module '@boldr/icons/Link' {
  declare module.exports: any;
}

declare module '@boldr/icons/Link2' {
  declare module.exports: any;
}

declare module '@boldr/icons/List' {
  declare module.exports: any;
}

declare module '@boldr/icons/ListOl' {
  declare module.exports: any;
}

declare module '@boldr/icons/Loader' {
  declare module.exports: any;
}

declare module '@boldr/icons/Lock' {
  declare module.exports: any;
}

declare module '@boldr/icons/LogIn' {
  declare module.exports: any;
}

declare module '@boldr/icons/LogOut' {
  declare module.exports: any;
}

declare module '@boldr/icons/Mail' {
  declare module.exports: any;
}

declare module '@boldr/icons/Map' {
  declare module.exports: any;
}

declare module '@boldr/icons/MapPin' {
  declare module.exports: any;
}

declare module '@boldr/icons/Maximize' {
  declare module.exports: any;
}

declare module '@boldr/icons/Maximize2' {
  declare module.exports: any;
}

declare module '@boldr/icons/Menu' {
  declare module.exports: any;
}

declare module '@boldr/icons/MessageCircle' {
  declare module.exports: any;
}

declare module '@boldr/icons/MessageSquare' {
  declare module.exports: any;
}

declare module '@boldr/icons/Mic' {
  declare module.exports: any;
}

declare module '@boldr/icons/MicOff' {
  declare module.exports: any;
}

declare module '@boldr/icons/Minimize' {
  declare module.exports: any;
}

declare module '@boldr/icons/Minimize2' {
  declare module.exports: any;
}

declare module '@boldr/icons/Minus' {
  declare module.exports: any;
}

declare module '@boldr/icons/MinusCircle' {
  declare module.exports: any;
}

declare module '@boldr/icons/MinusSquare' {
  declare module.exports: any;
}

declare module '@boldr/icons/Monitor' {
  declare module.exports: any;
}

declare module '@boldr/icons/Moon' {
  declare module.exports: any;
}

declare module '@boldr/icons/MoreHorizontal' {
  declare module.exports: any;
}

declare module '@boldr/icons/MoreVertical' {
  declare module.exports: any;
}

declare module '@boldr/icons/Move' {
  declare module.exports: any;
}

declare module '@boldr/icons/Music' {
  declare module.exports: any;
}

declare module '@boldr/icons/Navigation' {
  declare module.exports: any;
}

declare module '@boldr/icons/Navigation2' {
  declare module.exports: any;
}

declare module '@boldr/icons/Octagon' {
  declare module.exports: any;
}

declare module '@boldr/icons/Package' {
  declare module.exports: any;
}

declare module '@boldr/icons/PaintBrush' {
  declare module.exports: any;
}

declare module '@boldr/icons/Paperclip' {
  declare module.exports: any;
}

declare module '@boldr/icons/Paragraph' {
  declare module.exports: any;
}

declare module '@boldr/icons/Pause' {
  declare module.exports: any;
}

declare module '@boldr/icons/PauseCircle' {
  declare module.exports: any;
}

declare module '@boldr/icons/Percent' {
  declare module.exports: any;
}

declare module '@boldr/icons/Phone' {
  declare module.exports: any;
}

declare module '@boldr/icons/PhoneCall' {
  declare module.exports: any;
}

declare module '@boldr/icons/PhoneForwarded' {
  declare module.exports: any;
}

declare module '@boldr/icons/PhoneIncoming' {
  declare module.exports: any;
}

declare module '@boldr/icons/PhoneMissed' {
  declare module.exports: any;
}

declare module '@boldr/icons/PhoneOff' {
  declare module.exports: any;
}

declare module '@boldr/icons/PhoneOutgoing' {
  declare module.exports: any;
}

declare module '@boldr/icons/PieChart' {
  declare module.exports: any;
}

declare module '@boldr/icons/Play' {
  declare module.exports: any;
}

declare module '@boldr/icons/PlayCircle' {
  declare module.exports: any;
}

declare module '@boldr/icons/Plus' {
  declare module.exports: any;
}

declare module '@boldr/icons/PlusCircle' {
  declare module.exports: any;
}

declare module '@boldr/icons/PlusSquare' {
  declare module.exports: any;
}

declare module '@boldr/icons/Pocket' {
  declare module.exports: any;
}

declare module '@boldr/icons/Power' {
  declare module.exports: any;
}

declare module '@boldr/icons/Printer' {
  declare module.exports: any;
}

declare module '@boldr/icons/QuoteLeft' {
  declare module.exports: any;
}

declare module '@boldr/icons/QuoteRight' {
  declare module.exports: any;
}

declare module '@boldr/icons/Radio' {
  declare module.exports: any;
}

declare module '@boldr/icons/Redo' {
  declare module.exports: any;
}

declare module '@boldr/icons/RefreshCcw' {
  declare module.exports: any;
}

declare module '@boldr/icons/RefreshCw' {
  declare module.exports: any;
}

declare module '@boldr/icons/Repeat' {
  declare module.exports: any;
}

declare module '@boldr/icons/Rewind' {
  declare module.exports: any;
}

declare module '@boldr/icons/RotateCcw' {
  declare module.exports: any;
}

declare module '@boldr/icons/RotateCw' {
  declare module.exports: any;
}

declare module '@boldr/icons/Save' {
  declare module.exports: any;
}

declare module '@boldr/icons/Scissors' {
  declare module.exports: any;
}

declare module '@boldr/icons/Search' {
  declare module.exports: any;
}

declare module '@boldr/icons/Server' {
  declare module.exports: any;
}

declare module '@boldr/icons/Settings' {
  declare module.exports: any;
}

declare module '@boldr/icons/Share' {
  declare module.exports: any;
}

declare module '@boldr/icons/Share2' {
  declare module.exports: any;
}

declare module '@boldr/icons/Shield' {
  declare module.exports: any;
}

declare module '@boldr/icons/ShoppingCart' {
  declare module.exports: any;
}

declare module '@boldr/icons/Shuffle' {
  declare module.exports: any;
}

declare module '@boldr/icons/Sidebar' {
  declare module.exports: any;
}

declare module '@boldr/icons/SkipBack' {
  declare module.exports: any;
}

declare module '@boldr/icons/SkipForward' {
  declare module.exports: any;
}

declare module '@boldr/icons/Slack' {
  declare module.exports: any;
}

declare module '@boldr/icons/Slash' {
  declare module.exports: any;
}

declare module '@boldr/icons/Sliders' {
  declare module.exports: any;
}

declare module '@boldr/icons/Smartphone' {
  declare module.exports: any;
}

declare module '@boldr/icons/Smile' {
  declare module.exports: any;
}

declare module '@boldr/icons/Speaker' {
  declare module.exports: any;
}

declare module '@boldr/icons/Square' {
  declare module.exports: any;
}

declare module '@boldr/icons/Star' {
  declare module.exports: any;
}

declare module '@boldr/icons/StopCircle' {
  declare module.exports: any;
}

declare module '@boldr/icons/Strikethrough' {
  declare module.exports: any;
}

declare module '@boldr/icons/Subscript' {
  declare module.exports: any;
}

declare module '@boldr/icons/Sun' {
  declare module.exports: any;
}

declare module '@boldr/icons/Sunrise' {
  declare module.exports: any;
}

declare module '@boldr/icons/Sunset' {
  declare module.exports: any;
}

declare module '@boldr/icons/Superscript' {
  declare module.exports: any;
}

declare module '@boldr/icons/Table' {
  declare module.exports: any;
}

declare module '@boldr/icons/Tablet' {
  declare module.exports: any;
}

declare module '@boldr/icons/Tag' {
  declare module.exports: any;
}

declare module '@boldr/icons/Target' {
  declare module.exports: any;
}

declare module '@boldr/icons/Thermometer' {
  declare module.exports: any;
}

declare module '@boldr/icons/ThumbsDown' {
  declare module.exports: any;
}

declare module '@boldr/icons/ThumbsUp' {
  declare module.exports: any;
}

declare module '@boldr/icons/Times' {
  declare module.exports: any;
}

declare module '@boldr/icons/TimesCircle' {
  declare module.exports: any;
}

declare module '@boldr/icons/TimesSquare' {
  declare module.exports: any;
}

declare module '@boldr/icons/ToggleLeft' {
  declare module.exports: any;
}

declare module '@boldr/icons/ToggleRight' {
  declare module.exports: any;
}

declare module '@boldr/icons/Trash' {
  declare module.exports: any;
}

declare module '@boldr/icons/Trash2' {
  declare module.exports: any;
}

declare module '@boldr/icons/TrendingDown' {
  declare module.exports: any;
}

declare module '@boldr/icons/TrendingUp' {
  declare module.exports: any;
}

declare module '@boldr/icons/Triangle' {
  declare module.exports: any;
}

declare module '@boldr/icons/Tv' {
  declare module.exports: any;
}

declare module '@boldr/icons/Twitter' {
  declare module.exports: any;
}

declare module '@boldr/icons/Type' {
  declare module.exports: any;
}

declare module '@boldr/icons/Umbrella' {
  declare module.exports: any;
}

declare module '@boldr/icons/Underline' {
  declare module.exports: any;
}

declare module '@boldr/icons/Undo' {
  declare module.exports: any;
}

declare module '@boldr/icons/Unlink' {
  declare module.exports: any;
}

declare module '@boldr/icons/Unlock' {
  declare module.exports: any;
}

declare module '@boldr/icons/Upload' {
  declare module.exports: any;
}

declare module '@boldr/icons/UploadCloud' {
  declare module.exports: any;
}

declare module '@boldr/icons/User' {
  declare module.exports: any;
}

declare module '@boldr/icons/UserCheck' {
  declare module.exports: any;
}

declare module '@boldr/icons/UserMinus' {
  declare module.exports: any;
}

declare module '@boldr/icons/UserPlus' {
  declare module.exports: any;
}

declare module '@boldr/icons/Users' {
  declare module.exports: any;
}

declare module '@boldr/icons/UserX' {
  declare module.exports: any;
}

declare module '@boldr/icons/Video' {
  declare module.exports: any;
}

declare module '@boldr/icons/VideoOff' {
  declare module.exports: any;
}

declare module '@boldr/icons/Voicemail' {
  declare module.exports: any;
}

declare module '@boldr/icons/Volume' {
  declare module.exports: any;
}

declare module '@boldr/icons/Volume1' {
  declare module.exports: any;
}

declare module '@boldr/icons/Volume2' {
  declare module.exports: any;
}

declare module '@boldr/icons/VolumeX' {
  declare module.exports: any;
}

declare module '@boldr/icons/Watch' {
  declare module.exports: any;
}

declare module '@boldr/icons/Wifi' {
  declare module.exports: any;
}

declare module '@boldr/icons/WifiOff' {
  declare module.exports: any;
}

declare module '@boldr/icons/Wind' {
  declare module.exports: any;
}

declare module '@boldr/icons/Zap' {
  declare module.exports: any;
}

declare module '@boldr/icons/ZoomIn' {
  declare module.exports: any;
}

declare module '@boldr/icons/ZoomOut' {
  declare module.exports: any;
}

// Filename aliases
declare module '@boldr/icons/Activity.js' {
  declare module.exports: $Exports<'@boldr/icons/Activity'>;
}
declare module '@boldr/icons/Airplay.js' {
  declare module.exports: $Exports<'@boldr/icons/Airplay'>;
}
declare module '@boldr/icons/AlertCircle.js' {
  declare module.exports: $Exports<'@boldr/icons/AlertCircle'>;
}
declare module '@boldr/icons/AlertOctagon.js' {
  declare module.exports: $Exports<'@boldr/icons/AlertOctagon'>;
}
declare module '@boldr/icons/AlertTriangle.js' {
  declare module.exports: $Exports<'@boldr/icons/AlertTriangle'>;
}
declare module '@boldr/icons/AlignCenter.js' {
  declare module.exports: $Exports<'@boldr/icons/AlignCenter'>;
}
declare module '@boldr/icons/AlignJustify.js' {
  declare module.exports: $Exports<'@boldr/icons/AlignJustify'>;
}
declare module '@boldr/icons/AlignLeft.js' {
  declare module.exports: $Exports<'@boldr/icons/AlignLeft'>;
}
declare module '@boldr/icons/AlignRight.js' {
  declare module.exports: $Exports<'@boldr/icons/AlignRight'>;
}
declare module '@boldr/icons/Anchor.js' {
  declare module.exports: $Exports<'@boldr/icons/Anchor'>;
}
declare module '@boldr/icons/Aperture.js' {
  declare module.exports: $Exports<'@boldr/icons/Aperture'>;
}
declare module '@boldr/icons/ArrowDown.js' {
  declare module.exports: $Exports<'@boldr/icons/ArrowDown'>;
}
declare module '@boldr/icons/ArrowDownLeft.js' {
  declare module.exports: $Exports<'@boldr/icons/ArrowDownLeft'>;
}
declare module '@boldr/icons/ArrowDownRight.js' {
  declare module.exports: $Exports<'@boldr/icons/ArrowDownRight'>;
}
declare module '@boldr/icons/ArrowLeft.js' {
  declare module.exports: $Exports<'@boldr/icons/ArrowLeft'>;
}
declare module '@boldr/icons/ArrowRight.js' {
  declare module.exports: $Exports<'@boldr/icons/ArrowRight'>;
}
declare module '@boldr/icons/ArrowUp.js' {
  declare module.exports: $Exports<'@boldr/icons/ArrowUp'>;
}
declare module '@boldr/icons/ArrowUpLeft.js' {
  declare module.exports: $Exports<'@boldr/icons/ArrowUpLeft'>;
}
declare module '@boldr/icons/ArrowUpRight.js' {
  declare module.exports: $Exports<'@boldr/icons/ArrowUpRight'>;
}
declare module '@boldr/icons/AtSign.js' {
  declare module.exports: $Exports<'@boldr/icons/AtSign'>;
}
declare module '@boldr/icons/Award.js' {
  declare module.exports: $Exports<'@boldr/icons/Award'>;
}
declare module '@boldr/icons/BarChart.js' {
  declare module.exports: $Exports<'@boldr/icons/BarChart'>;
}
declare module '@boldr/icons/BarChart2.js' {
  declare module.exports: $Exports<'@boldr/icons/BarChart2'>;
}
declare module '@boldr/icons/Battery.js' {
  declare module.exports: $Exports<'@boldr/icons/Battery'>;
}
declare module '@boldr/icons/BatteryCharging.js' {
  declare module.exports: $Exports<'@boldr/icons/BatteryCharging'>;
}
declare module '@boldr/icons/Bell.js' {
  declare module.exports: $Exports<'@boldr/icons/Bell'>;
}
declare module '@boldr/icons/BellOff.js' {
  declare module.exports: $Exports<'@boldr/icons/BellOff'>;
}
declare module '@boldr/icons/Bluetooth.js' {
  declare module.exports: $Exports<'@boldr/icons/Bluetooth'>;
}
declare module '@boldr/icons/Bold.js' {
  declare module.exports: $Exports<'@boldr/icons/Bold'>;
}
declare module '@boldr/icons/Book.js' {
  declare module.exports: $Exports<'@boldr/icons/Book'>;
}
declare module '@boldr/icons/Bookmark.js' {
  declare module.exports: $Exports<'@boldr/icons/Bookmark'>;
}
declare module '@boldr/icons/Box.js' {
  declare module.exports: $Exports<'@boldr/icons/Box'>;
}
declare module '@boldr/icons/Briefcase.js' {
  declare module.exports: $Exports<'@boldr/icons/Briefcase'>;
}
declare module '@boldr/icons/Calendar.js' {
  declare module.exports: $Exports<'@boldr/icons/Calendar'>;
}
declare module '@boldr/icons/Camera.js' {
  declare module.exports: $Exports<'@boldr/icons/Camera'>;
}
declare module '@boldr/icons/CameraOff.js' {
  declare module.exports: $Exports<'@boldr/icons/CameraOff'>;
}
declare module '@boldr/icons/Cast.js' {
  declare module.exports: $Exports<'@boldr/icons/Cast'>;
}
declare module '@boldr/icons/Check.js' {
  declare module.exports: $Exports<'@boldr/icons/Check'>;
}
declare module '@boldr/icons/CheckCircle.js' {
  declare module.exports: $Exports<'@boldr/icons/CheckCircle'>;
}
declare module '@boldr/icons/CheckSquare.js' {
  declare module.exports: $Exports<'@boldr/icons/CheckSquare'>;
}
declare module '@boldr/icons/ChevronDown.js' {
  declare module.exports: $Exports<'@boldr/icons/ChevronDown'>;
}
declare module '@boldr/icons/ChevronLeft.js' {
  declare module.exports: $Exports<'@boldr/icons/ChevronLeft'>;
}
declare module '@boldr/icons/ChevronRight.js' {
  declare module.exports: $Exports<'@boldr/icons/ChevronRight'>;
}
declare module '@boldr/icons/ChevronsDown.js' {
  declare module.exports: $Exports<'@boldr/icons/ChevronsDown'>;
}
declare module '@boldr/icons/ChevronsLeft.js' {
  declare module.exports: $Exports<'@boldr/icons/ChevronsLeft'>;
}
declare module '@boldr/icons/ChevronsRight.js' {
  declare module.exports: $Exports<'@boldr/icons/ChevronsRight'>;
}
declare module '@boldr/icons/ChevronsUp.js' {
  declare module.exports: $Exports<'@boldr/icons/ChevronsUp'>;
}
declare module '@boldr/icons/ChevronUp.js' {
  declare module.exports: $Exports<'@boldr/icons/ChevronUp'>;
}
declare module '@boldr/icons/Chrome.js' {
  declare module.exports: $Exports<'@boldr/icons/Chrome'>;
}
declare module '@boldr/icons/Circle.js' {
  declare module.exports: $Exports<'@boldr/icons/Circle'>;
}
declare module '@boldr/icons/Clipboard.js' {
  declare module.exports: $Exports<'@boldr/icons/Clipboard'>;
}
declare module '@boldr/icons/Clock.js' {
  declare module.exports: $Exports<'@boldr/icons/Clock'>;
}
declare module '@boldr/icons/Cloud.js' {
  declare module.exports: $Exports<'@boldr/icons/Cloud'>;
}
declare module '@boldr/icons/CloudDrizzle.js' {
  declare module.exports: $Exports<'@boldr/icons/CloudDrizzle'>;
}
declare module '@boldr/icons/CloudLightning.js' {
  declare module.exports: $Exports<'@boldr/icons/CloudLightning'>;
}
declare module '@boldr/icons/CloudOff.js' {
  declare module.exports: $Exports<'@boldr/icons/CloudOff'>;
}
declare module '@boldr/icons/CloudRain.js' {
  declare module.exports: $Exports<'@boldr/icons/CloudRain'>;
}
declare module '@boldr/icons/CloudSnow.js' {
  declare module.exports: $Exports<'@boldr/icons/CloudSnow'>;
}
declare module '@boldr/icons/Code.js' {
  declare module.exports: $Exports<'@boldr/icons/Code'>;
}
declare module '@boldr/icons/Codepen.js' {
  declare module.exports: $Exports<'@boldr/icons/Codepen'>;
}
declare module '@boldr/icons/Command.js' {
  declare module.exports: $Exports<'@boldr/icons/Command'>;
}
declare module '@boldr/icons/Compass.js' {
  declare module.exports: $Exports<'@boldr/icons/Compass'>;
}
declare module '@boldr/icons/Copy.js' {
  declare module.exports: $Exports<'@boldr/icons/Copy'>;
}
declare module '@boldr/icons/CornerDownLeft.js' {
  declare module.exports: $Exports<'@boldr/icons/CornerDownLeft'>;
}
declare module '@boldr/icons/CornerDownRight.js' {
  declare module.exports: $Exports<'@boldr/icons/CornerDownRight'>;
}
declare module '@boldr/icons/CornerLeftDown.js' {
  declare module.exports: $Exports<'@boldr/icons/CornerLeftDown'>;
}
declare module '@boldr/icons/CornerLeftUp.js' {
  declare module.exports: $Exports<'@boldr/icons/CornerLeftUp'>;
}
declare module '@boldr/icons/CornerRightDown.js' {
  declare module.exports: $Exports<'@boldr/icons/CornerRightDown'>;
}
declare module '@boldr/icons/CornerRightUp.js' {
  declare module.exports: $Exports<'@boldr/icons/CornerRightUp'>;
}
declare module '@boldr/icons/CornerUpLeft.js' {
  declare module.exports: $Exports<'@boldr/icons/CornerUpLeft'>;
}
declare module '@boldr/icons/CornerUpRight.js' {
  declare module.exports: $Exports<'@boldr/icons/CornerUpRight'>;
}
declare module '@boldr/icons/Cpu.js' {
  declare module.exports: $Exports<'@boldr/icons/Cpu'>;
}
declare module '@boldr/icons/CreditCard.js' {
  declare module.exports: $Exports<'@boldr/icons/CreditCard'>;
}
declare module '@boldr/icons/Crop.js' {
  declare module.exports: $Exports<'@boldr/icons/Crop'>;
}
declare module '@boldr/icons/Crosshair.js' {
  declare module.exports: $Exports<'@boldr/icons/Crosshair'>;
}
declare module '@boldr/icons/Delete.js' {
  declare module.exports: $Exports<'@boldr/icons/Delete'>;
}
declare module '@boldr/icons/Disc.js' {
  declare module.exports: $Exports<'@boldr/icons/Disc'>;
}
declare module '@boldr/icons/Download.js' {
  declare module.exports: $Exports<'@boldr/icons/Download'>;
}
declare module '@boldr/icons/DownloadCloud.js' {
  declare module.exports: $Exports<'@boldr/icons/DownloadCloud'>;
}
declare module '@boldr/icons/Droplet.js' {
  declare module.exports: $Exports<'@boldr/icons/Droplet'>;
}
declare module '@boldr/icons/Edit.js' {
  declare module.exports: $Exports<'@boldr/icons/Edit'>;
}
declare module '@boldr/icons/Edit2.js' {
  declare module.exports: $Exports<'@boldr/icons/Edit2'>;
}
declare module '@boldr/icons/Edit3.js' {
  declare module.exports: $Exports<'@boldr/icons/Edit3'>;
}
declare module '@boldr/icons/Embedded.js' {
  declare module.exports: $Exports<'@boldr/icons/Embedded'>;
}
declare module '@boldr/icons/Eraser.js' {
  declare module.exports: $Exports<'@boldr/icons/Eraser'>;
}
declare module '@boldr/icons/ExternalLink.js' {
  declare module.exports: $Exports<'@boldr/icons/ExternalLink'>;
}
declare module '@boldr/icons/Eye.js' {
  declare module.exports: $Exports<'@boldr/icons/Eye'>;
}
declare module '@boldr/icons/EyeOff.js' {
  declare module.exports: $Exports<'@boldr/icons/EyeOff'>;
}
declare module '@boldr/icons/Facebook.js' {
  declare module.exports: $Exports<'@boldr/icons/Facebook'>;
}
declare module '@boldr/icons/FastForward.js' {
  declare module.exports: $Exports<'@boldr/icons/FastForward'>;
}
declare module '@boldr/icons/Feather.js' {
  declare module.exports: $Exports<'@boldr/icons/Feather'>;
}
declare module '@boldr/icons/File.js' {
  declare module.exports: $Exports<'@boldr/icons/File'>;
}
declare module '@boldr/icons/FileMinus.js' {
  declare module.exports: $Exports<'@boldr/icons/FileMinus'>;
}
declare module '@boldr/icons/FilePlus.js' {
  declare module.exports: $Exports<'@boldr/icons/FilePlus'>;
}
declare module '@boldr/icons/FileText.js' {
  declare module.exports: $Exports<'@boldr/icons/FileText'>;
}
declare module '@boldr/icons/Film.js' {
  declare module.exports: $Exports<'@boldr/icons/Film'>;
}
declare module '@boldr/icons/Filter.js' {
  declare module.exports: $Exports<'@boldr/icons/Filter'>;
}
declare module '@boldr/icons/Flag.js' {
  declare module.exports: $Exports<'@boldr/icons/Flag'>;
}
declare module '@boldr/icons/Folder.js' {
  declare module.exports: $Exports<'@boldr/icons/Folder'>;
}
declare module '@boldr/icons/Github.js' {
  declare module.exports: $Exports<'@boldr/icons/Github'>;
}
declare module '@boldr/icons/Gitlab.js' {
  declare module.exports: $Exports<'@boldr/icons/Gitlab'>;
}
declare module '@boldr/icons/Globe.js' {
  declare module.exports: $Exports<'@boldr/icons/Globe'>;
}
declare module '@boldr/icons/Grid.js' {
  declare module.exports: $Exports<'@boldr/icons/Grid'>;
}
declare module '@boldr/icons/Hash.js' {
  declare module.exports: $Exports<'@boldr/icons/Hash'>;
}
declare module '@boldr/icons/Heading.js' {
  declare module.exports: $Exports<'@boldr/icons/Heading'>;
}
declare module '@boldr/icons/Heading1.js' {
  declare module.exports: $Exports<'@boldr/icons/Heading1'>;
}
declare module '@boldr/icons/Heading2.js' {
  declare module.exports: $Exports<'@boldr/icons/Heading2'>;
}
declare module '@boldr/icons/Heading3.js' {
  declare module.exports: $Exports<'@boldr/icons/Heading3'>;
}
declare module '@boldr/icons/Headphones.js' {
  declare module.exports: $Exports<'@boldr/icons/Headphones'>;
}
declare module '@boldr/icons/Heart.js' {
  declare module.exports: $Exports<'@boldr/icons/Heart'>;
}
declare module '@boldr/icons/HelpCircle.js' {
  declare module.exports: $Exports<'@boldr/icons/HelpCircle'>;
}
declare module '@boldr/icons/Home.js' {
  declare module.exports: $Exports<'@boldr/icons/Home'>;
}
declare module '@boldr/icons/Icon.js' {
  declare module.exports: $Exports<'@boldr/icons/Icon'>;
}
declare module '@boldr/icons/Image.js' {
  declare module.exports: $Exports<'@boldr/icons/Image'>;
}
declare module '@boldr/icons/Inbox.js' {
  declare module.exports: $Exports<'@boldr/icons/Inbox'>;
}
declare module '@boldr/icons/index.es.js' {
  declare module.exports: $Exports<'@boldr/icons/index.es'>;
}
declare module '@boldr/icons/index' {
  declare module.exports: $Exports<'@boldr/icons'>;
}
declare module '@boldr/icons/index.js' {
  declare module.exports: $Exports<'@boldr/icons'>;
}
declare module '@boldr/icons/Info.js' {
  declare module.exports: $Exports<'@boldr/icons/Info'>;
}
declare module '@boldr/icons/Instagram.js' {
  declare module.exports: $Exports<'@boldr/icons/Instagram'>;
}
declare module '@boldr/icons/Italic.js' {
  declare module.exports: $Exports<'@boldr/icons/Italic'>;
}
declare module '@boldr/icons/Layers.js' {
  declare module.exports: $Exports<'@boldr/icons/Layers'>;
}
declare module '@boldr/icons/Layout.js' {
  declare module.exports: $Exports<'@boldr/icons/Layout'>;
}
declare module '@boldr/icons/LifeBuoy.js' {
  declare module.exports: $Exports<'@boldr/icons/LifeBuoy'>;
}
declare module '@boldr/icons/Link.js' {
  declare module.exports: $Exports<'@boldr/icons/Link'>;
}
declare module '@boldr/icons/Link2.js' {
  declare module.exports: $Exports<'@boldr/icons/Link2'>;
}
declare module '@boldr/icons/List.js' {
  declare module.exports: $Exports<'@boldr/icons/List'>;
}
declare module '@boldr/icons/ListOl.js' {
  declare module.exports: $Exports<'@boldr/icons/ListOl'>;
}
declare module '@boldr/icons/Loader.js' {
  declare module.exports: $Exports<'@boldr/icons/Loader'>;
}
declare module '@boldr/icons/Lock.js' {
  declare module.exports: $Exports<'@boldr/icons/Lock'>;
}
declare module '@boldr/icons/LogIn.js' {
  declare module.exports: $Exports<'@boldr/icons/LogIn'>;
}
declare module '@boldr/icons/LogOut.js' {
  declare module.exports: $Exports<'@boldr/icons/LogOut'>;
}
declare module '@boldr/icons/Mail.js' {
  declare module.exports: $Exports<'@boldr/icons/Mail'>;
}
declare module '@boldr/icons/Map.js' {
  declare module.exports: $Exports<'@boldr/icons/Map'>;
}
declare module '@boldr/icons/MapPin.js' {
  declare module.exports: $Exports<'@boldr/icons/MapPin'>;
}
declare module '@boldr/icons/Maximize.js' {
  declare module.exports: $Exports<'@boldr/icons/Maximize'>;
}
declare module '@boldr/icons/Maximize2.js' {
  declare module.exports: $Exports<'@boldr/icons/Maximize2'>;
}
declare module '@boldr/icons/Menu.js' {
  declare module.exports: $Exports<'@boldr/icons/Menu'>;
}
declare module '@boldr/icons/MessageCircle.js' {
  declare module.exports: $Exports<'@boldr/icons/MessageCircle'>;
}
declare module '@boldr/icons/MessageSquare.js' {
  declare module.exports: $Exports<'@boldr/icons/MessageSquare'>;
}
declare module '@boldr/icons/Mic.js' {
  declare module.exports: $Exports<'@boldr/icons/Mic'>;
}
declare module '@boldr/icons/MicOff.js' {
  declare module.exports: $Exports<'@boldr/icons/MicOff'>;
}
declare module '@boldr/icons/Minimize.js' {
  declare module.exports: $Exports<'@boldr/icons/Minimize'>;
}
declare module '@boldr/icons/Minimize2.js' {
  declare module.exports: $Exports<'@boldr/icons/Minimize2'>;
}
declare module '@boldr/icons/Minus.js' {
  declare module.exports: $Exports<'@boldr/icons/Minus'>;
}
declare module '@boldr/icons/MinusCircle.js' {
  declare module.exports: $Exports<'@boldr/icons/MinusCircle'>;
}
declare module '@boldr/icons/MinusSquare.js' {
  declare module.exports: $Exports<'@boldr/icons/MinusSquare'>;
}
declare module '@boldr/icons/Monitor.js' {
  declare module.exports: $Exports<'@boldr/icons/Monitor'>;
}
declare module '@boldr/icons/Moon.js' {
  declare module.exports: $Exports<'@boldr/icons/Moon'>;
}
declare module '@boldr/icons/MoreHorizontal.js' {
  declare module.exports: $Exports<'@boldr/icons/MoreHorizontal'>;
}
declare module '@boldr/icons/MoreVertical.js' {
  declare module.exports: $Exports<'@boldr/icons/MoreVertical'>;
}
declare module '@boldr/icons/Move.js' {
  declare module.exports: $Exports<'@boldr/icons/Move'>;
}
declare module '@boldr/icons/Music.js' {
  declare module.exports: $Exports<'@boldr/icons/Music'>;
}
declare module '@boldr/icons/Navigation.js' {
  declare module.exports: $Exports<'@boldr/icons/Navigation'>;
}
declare module '@boldr/icons/Navigation2.js' {
  declare module.exports: $Exports<'@boldr/icons/Navigation2'>;
}
declare module '@boldr/icons/Octagon.js' {
  declare module.exports: $Exports<'@boldr/icons/Octagon'>;
}
declare module '@boldr/icons/Package.js' {
  declare module.exports: $Exports<'@boldr/icons/Package'>;
}
declare module '@boldr/icons/PaintBrush.js' {
  declare module.exports: $Exports<'@boldr/icons/PaintBrush'>;
}
declare module '@boldr/icons/Paperclip.js' {
  declare module.exports: $Exports<'@boldr/icons/Paperclip'>;
}
declare module '@boldr/icons/Paragraph.js' {
  declare module.exports: $Exports<'@boldr/icons/Paragraph'>;
}
declare module '@boldr/icons/Pause.js' {
  declare module.exports: $Exports<'@boldr/icons/Pause'>;
}
declare module '@boldr/icons/PauseCircle.js' {
  declare module.exports: $Exports<'@boldr/icons/PauseCircle'>;
}
declare module '@boldr/icons/Percent.js' {
  declare module.exports: $Exports<'@boldr/icons/Percent'>;
}
declare module '@boldr/icons/Phone.js' {
  declare module.exports: $Exports<'@boldr/icons/Phone'>;
}
declare module '@boldr/icons/PhoneCall.js' {
  declare module.exports: $Exports<'@boldr/icons/PhoneCall'>;
}
declare module '@boldr/icons/PhoneForwarded.js' {
  declare module.exports: $Exports<'@boldr/icons/PhoneForwarded'>;
}
declare module '@boldr/icons/PhoneIncoming.js' {
  declare module.exports: $Exports<'@boldr/icons/PhoneIncoming'>;
}
declare module '@boldr/icons/PhoneMissed.js' {
  declare module.exports: $Exports<'@boldr/icons/PhoneMissed'>;
}
declare module '@boldr/icons/PhoneOff.js' {
  declare module.exports: $Exports<'@boldr/icons/PhoneOff'>;
}
declare module '@boldr/icons/PhoneOutgoing.js' {
  declare module.exports: $Exports<'@boldr/icons/PhoneOutgoing'>;
}
declare module '@boldr/icons/PieChart.js' {
  declare module.exports: $Exports<'@boldr/icons/PieChart'>;
}
declare module '@boldr/icons/Play.js' {
  declare module.exports: $Exports<'@boldr/icons/Play'>;
}
declare module '@boldr/icons/PlayCircle.js' {
  declare module.exports: $Exports<'@boldr/icons/PlayCircle'>;
}
declare module '@boldr/icons/Plus.js' {
  declare module.exports: $Exports<'@boldr/icons/Plus'>;
}
declare module '@boldr/icons/PlusCircle.js' {
  declare module.exports: $Exports<'@boldr/icons/PlusCircle'>;
}
declare module '@boldr/icons/PlusSquare.js' {
  declare module.exports: $Exports<'@boldr/icons/PlusSquare'>;
}
declare module '@boldr/icons/Pocket.js' {
  declare module.exports: $Exports<'@boldr/icons/Pocket'>;
}
declare module '@boldr/icons/Power.js' {
  declare module.exports: $Exports<'@boldr/icons/Power'>;
}
declare module '@boldr/icons/Printer.js' {
  declare module.exports: $Exports<'@boldr/icons/Printer'>;
}
declare module '@boldr/icons/QuoteLeft.js' {
  declare module.exports: $Exports<'@boldr/icons/QuoteLeft'>;
}
declare module '@boldr/icons/QuoteRight.js' {
  declare module.exports: $Exports<'@boldr/icons/QuoteRight'>;
}
declare module '@boldr/icons/Radio.js' {
  declare module.exports: $Exports<'@boldr/icons/Radio'>;
}
declare module '@boldr/icons/Redo.js' {
  declare module.exports: $Exports<'@boldr/icons/Redo'>;
}
declare module '@boldr/icons/RefreshCcw.js' {
  declare module.exports: $Exports<'@boldr/icons/RefreshCcw'>;
}
declare module '@boldr/icons/RefreshCw.js' {
  declare module.exports: $Exports<'@boldr/icons/RefreshCw'>;
}
declare module '@boldr/icons/Repeat.js' {
  declare module.exports: $Exports<'@boldr/icons/Repeat'>;
}
declare module '@boldr/icons/Rewind.js' {
  declare module.exports: $Exports<'@boldr/icons/Rewind'>;
}
declare module '@boldr/icons/RotateCcw.js' {
  declare module.exports: $Exports<'@boldr/icons/RotateCcw'>;
}
declare module '@boldr/icons/RotateCw.js' {
  declare module.exports: $Exports<'@boldr/icons/RotateCw'>;
}
declare module '@boldr/icons/Save.js' {
  declare module.exports: $Exports<'@boldr/icons/Save'>;
}
declare module '@boldr/icons/Scissors.js' {
  declare module.exports: $Exports<'@boldr/icons/Scissors'>;
}
declare module '@boldr/icons/Search.js' {
  declare module.exports: $Exports<'@boldr/icons/Search'>;
}
declare module '@boldr/icons/Server.js' {
  declare module.exports: $Exports<'@boldr/icons/Server'>;
}
declare module '@boldr/icons/Settings.js' {
  declare module.exports: $Exports<'@boldr/icons/Settings'>;
}
declare module '@boldr/icons/Share.js' {
  declare module.exports: $Exports<'@boldr/icons/Share'>;
}
declare module '@boldr/icons/Share2.js' {
  declare module.exports: $Exports<'@boldr/icons/Share2'>;
}
declare module '@boldr/icons/Shield.js' {
  declare module.exports: $Exports<'@boldr/icons/Shield'>;
}
declare module '@boldr/icons/ShoppingCart.js' {
  declare module.exports: $Exports<'@boldr/icons/ShoppingCart'>;
}
declare module '@boldr/icons/Shuffle.js' {
  declare module.exports: $Exports<'@boldr/icons/Shuffle'>;
}
declare module '@boldr/icons/Sidebar.js' {
  declare module.exports: $Exports<'@boldr/icons/Sidebar'>;
}
declare module '@boldr/icons/SkipBack.js' {
  declare module.exports: $Exports<'@boldr/icons/SkipBack'>;
}
declare module '@boldr/icons/SkipForward.js' {
  declare module.exports: $Exports<'@boldr/icons/SkipForward'>;
}
declare module '@boldr/icons/Slack.js' {
  declare module.exports: $Exports<'@boldr/icons/Slack'>;
}
declare module '@boldr/icons/Slash.js' {
  declare module.exports: $Exports<'@boldr/icons/Slash'>;
}
declare module '@boldr/icons/Sliders.js' {
  declare module.exports: $Exports<'@boldr/icons/Sliders'>;
}
declare module '@boldr/icons/Smartphone.js' {
  declare module.exports: $Exports<'@boldr/icons/Smartphone'>;
}
declare module '@boldr/icons/Smile.js' {
  declare module.exports: $Exports<'@boldr/icons/Smile'>;
}
declare module '@boldr/icons/Speaker.js' {
  declare module.exports: $Exports<'@boldr/icons/Speaker'>;
}
declare module '@boldr/icons/Square.js' {
  declare module.exports: $Exports<'@boldr/icons/Square'>;
}
declare module '@boldr/icons/Star.js' {
  declare module.exports: $Exports<'@boldr/icons/Star'>;
}
declare module '@boldr/icons/StopCircle.js' {
  declare module.exports: $Exports<'@boldr/icons/StopCircle'>;
}
declare module '@boldr/icons/Strikethrough.js' {
  declare module.exports: $Exports<'@boldr/icons/Strikethrough'>;
}
declare module '@boldr/icons/Subscript.js' {
  declare module.exports: $Exports<'@boldr/icons/Subscript'>;
}
declare module '@boldr/icons/Sun.js' {
  declare module.exports: $Exports<'@boldr/icons/Sun'>;
}
declare module '@boldr/icons/Sunrise.js' {
  declare module.exports: $Exports<'@boldr/icons/Sunrise'>;
}
declare module '@boldr/icons/Sunset.js' {
  declare module.exports: $Exports<'@boldr/icons/Sunset'>;
}
declare module '@boldr/icons/Superscript.js' {
  declare module.exports: $Exports<'@boldr/icons/Superscript'>;
}
declare module '@boldr/icons/Table.js' {
  declare module.exports: $Exports<'@boldr/icons/Table'>;
}
declare module '@boldr/icons/Tablet.js' {
  declare module.exports: $Exports<'@boldr/icons/Tablet'>;
}
declare module '@boldr/icons/Tag.js' {
  declare module.exports: $Exports<'@boldr/icons/Tag'>;
}
declare module '@boldr/icons/Target.js' {
  declare module.exports: $Exports<'@boldr/icons/Target'>;
}
declare module '@boldr/icons/Thermometer.js' {
  declare module.exports: $Exports<'@boldr/icons/Thermometer'>;
}
declare module '@boldr/icons/ThumbsDown.js' {
  declare module.exports: $Exports<'@boldr/icons/ThumbsDown'>;
}
declare module '@boldr/icons/ThumbsUp.js' {
  declare module.exports: $Exports<'@boldr/icons/ThumbsUp'>;
}
declare module '@boldr/icons/Times.js' {
  declare module.exports: $Exports<'@boldr/icons/Times'>;
}
declare module '@boldr/icons/TimesCircle.js' {
  declare module.exports: $Exports<'@boldr/icons/TimesCircle'>;
}
declare module '@boldr/icons/TimesSquare.js' {
  declare module.exports: $Exports<'@boldr/icons/TimesSquare'>;
}
declare module '@boldr/icons/ToggleLeft.js' {
  declare module.exports: $Exports<'@boldr/icons/ToggleLeft'>;
}
declare module '@boldr/icons/ToggleRight.js' {
  declare module.exports: $Exports<'@boldr/icons/ToggleRight'>;
}
declare module '@boldr/icons/Trash.js' {
  declare module.exports: $Exports<'@boldr/icons/Trash'>;
}
declare module '@boldr/icons/Trash2.js' {
  declare module.exports: $Exports<'@boldr/icons/Trash2'>;
}
declare module '@boldr/icons/TrendingDown.js' {
  declare module.exports: $Exports<'@boldr/icons/TrendingDown'>;
}
declare module '@boldr/icons/TrendingUp.js' {
  declare module.exports: $Exports<'@boldr/icons/TrendingUp'>;
}
declare module '@boldr/icons/Triangle.js' {
  declare module.exports: $Exports<'@boldr/icons/Triangle'>;
}
declare module '@boldr/icons/Tv.js' {
  declare module.exports: $Exports<'@boldr/icons/Tv'>;
}
declare module '@boldr/icons/Twitter.js' {
  declare module.exports: $Exports<'@boldr/icons/Twitter'>;
}
declare module '@boldr/icons/Type.js' {
  declare module.exports: $Exports<'@boldr/icons/Type'>;
}
declare module '@boldr/icons/Umbrella.js' {
  declare module.exports: $Exports<'@boldr/icons/Umbrella'>;
}
declare module '@boldr/icons/Underline.js' {
  declare module.exports: $Exports<'@boldr/icons/Underline'>;
}
declare module '@boldr/icons/Undo.js' {
  declare module.exports: $Exports<'@boldr/icons/Undo'>;
}
declare module '@boldr/icons/Unlink.js' {
  declare module.exports: $Exports<'@boldr/icons/Unlink'>;
}
declare module '@boldr/icons/Unlock.js' {
  declare module.exports: $Exports<'@boldr/icons/Unlock'>;
}
declare module '@boldr/icons/Upload.js' {
  declare module.exports: $Exports<'@boldr/icons/Upload'>;
}
declare module '@boldr/icons/UploadCloud.js' {
  declare module.exports: $Exports<'@boldr/icons/UploadCloud'>;
}
declare module '@boldr/icons/User.js' {
  declare module.exports: $Exports<'@boldr/icons/User'>;
}
declare module '@boldr/icons/UserCheck.js' {
  declare module.exports: $Exports<'@boldr/icons/UserCheck'>;
}
declare module '@boldr/icons/UserMinus.js' {
  declare module.exports: $Exports<'@boldr/icons/UserMinus'>;
}
declare module '@boldr/icons/UserPlus.js' {
  declare module.exports: $Exports<'@boldr/icons/UserPlus'>;
}
declare module '@boldr/icons/Users.js' {
  declare module.exports: $Exports<'@boldr/icons/Users'>;
}
declare module '@boldr/icons/UserX.js' {
  declare module.exports: $Exports<'@boldr/icons/UserX'>;
}
declare module '@boldr/icons/Video.js' {
  declare module.exports: $Exports<'@boldr/icons/Video'>;
}
declare module '@boldr/icons/VideoOff.js' {
  declare module.exports: $Exports<'@boldr/icons/VideoOff'>;
}
declare module '@boldr/icons/Voicemail.js' {
  declare module.exports: $Exports<'@boldr/icons/Voicemail'>;
}
declare module '@boldr/icons/Volume.js' {
  declare module.exports: $Exports<'@boldr/icons/Volume'>;
}
declare module '@boldr/icons/Volume1.js' {
  declare module.exports: $Exports<'@boldr/icons/Volume1'>;
}
declare module '@boldr/icons/Volume2.js' {
  declare module.exports: $Exports<'@boldr/icons/Volume2'>;
}
declare module '@boldr/icons/VolumeX.js' {
  declare module.exports: $Exports<'@boldr/icons/VolumeX'>;
}
declare module '@boldr/icons/Watch.js' {
  declare module.exports: $Exports<'@boldr/icons/Watch'>;
}
declare module '@boldr/icons/Wifi.js' {
  declare module.exports: $Exports<'@boldr/icons/Wifi'>;
}
declare module '@boldr/icons/WifiOff.js' {
  declare module.exports: $Exports<'@boldr/icons/WifiOff'>;
}
declare module '@boldr/icons/Wind.js' {
  declare module.exports: $Exports<'@boldr/icons/Wind'>;
}
declare module '@boldr/icons/Zap.js' {
  declare module.exports: $Exports<'@boldr/icons/Zap'>;
}
declare module '@boldr/icons/ZoomIn.js' {
  declare module.exports: $Exports<'@boldr/icons/ZoomIn'>;
}
declare module '@boldr/icons/ZoomOut.js' {
  declare module.exports: $Exports<'@boldr/icons/ZoomOut'>;
}
