export const FETCH_TEMPLATES_REQUEST = '@boldr/templates/FETCH_TEMPLATES_REQUEST';
export const FETCH_TEMPLATES_SUCCESS = '@boldr/pages/FETCH_TEMPLATES_SUCCESS';
export const FETCH_TEMPLATES_FAILURE = '@boldr/pages/FETCH_TEMPLATES_FAILURE';

export const FETCH_TEMPLATE_REQUEST = '@boldr/pages/FETCH_TEMPLATE_REQUEST';
export const FETCH_TEMPLATE_SUCCESS = '@boldr/pages/FETCH_TEMPLATE_SUCCESS';
export const FETCH_TEMPLATE_FAILURE = '@boldr/pages/FETCH_TEMPLATE_FAILURE';
